### ISSUE TITLE
Add ordsucsssuc to iset.mm

### ISSUE THREAD

**Issue by jkingdon** [metamath/set.mm#1032]
@digama0 said in #629 that ordsucsssuc is provable in iset.mm, "proof is a bit complicated and uses injectivity of suc". Do you remember the proof you had in mind? We do have suc11g in iset.mm so injectivity is available. I tried a little experimentation but just knowing to use suc11g didn't get me all that far.

As for why I'm asking about this one in particular, many paths to oasuc rely on ordsucsssuc .

**Comment by digama0** [comment]
I think the forward direction `A C_ B -> suc A C_ suc B` fails. It is basically asserting that `suc' B C_ suc B`, which is the unprovable implication. Specifically, consider our counterexample ordinal `X = {x | p} C_ 1o`. Assuming the theorem, `suc X C_ 2o` so `X e. 2o` so `X = (/)` (so p is false) or `X = 1o` (so p is true).

For the reverse implication, suppose `suc A C_ suc B` and `x e. A`. Then `x e. suc B`, so either `x e. B` and we are done, or `x = B`. In the latter case, `B e. A`, but `A e. suc B` as well and both `A e. B` and `A = B` yield an elementhood cycle.

**Comment by jkingdon** [comment]
Ah yes, I had been working with `A e. suc B -> suc A C_ suc B` (from `ordsucss`) but I had not noticed that the converse also holds (from `ordelsuc`).

I have formalized both of the above proofs in #1034 ; thanks!
