### ISSUE TITLE
Incorrect df-mpt2 comment

### ISSUE THREAD

**Issue by zengxu-yang** [metamath/set.mm#1033]
In df-mpt2 of set.mm:

> $( Define maps-to notation for defining an operation via a rule.  Read as
       "the operation defined by the map from ` x , y ` (in ` A X. B ` ) to
       ` B ( x , y ) ` ."  An extension of ~ df-mpt for two arguments.
       (Contributed by NM, 17-Feb-2008.) $)

I think B (x, y) should be C (x, y). Is it a typo?

**Comment by nmegill** [comment]
Yes, it is a typo, thanks for reporting it.  Fixed in commit 9f78cd4.
