### ISSUE TITLE
Prove Cayley-Hamilton Theorem (Metamath 100 #49)

### ISSUE THREAD

**Issue by avekens** [metamath/set.mm#1056]
I am currently working on the Cayley-Hamilton Theorem, No. 49 in the Metamath 100 list. Although there is still a lot to do, I am making good progress, so I hope I can provide the proof in some weeks...

See also Methamath Mailing List https://groups.google.com/d/msg/metamath/lcdsXFNnBvU/-d8tO07cDQAJ.

**Comment by avekens** [comment]
Unfortunately, I cannot assign this issue to me (to anyone), and i also cannot set a label...

**Comment by benjub** [comment]
Good luck!  I also wish I knew how to assign issues: this probably requires privileges, but maybe assigning to oneself is still possible.

**Comment by jkingdon** [comment]
Hmm, apparently it does require write permissions to assign issues. I assigned this one, but I don't know, it does seem like this may limit how useful the assignment feature ends up being.

**Comment by david-a-wheeler** [comment]
@avekens - best of luck!!

**Comment by avekens** [comment]
Hi, after about four month and a lot of work (not full time of course), I succeeded in proving the Cayley-Hamilton theorem today! I just started the PR (hopefully it will pass the Travis checks), so that the theorem (and all the theorems and definitions required for its proof) will be available soon.

My proof is based on the direct algebraic proof shown in Wikipedia. This is a "brute force" approach, but it works. More elegant proofs using polynomials with matrix coefficients over specially constructed commutative rings (centralizer of the matrix) and special evaluation maps should be possible (and maybe could be performed more easily using my theorems). I started with such an "elegant" appoach, but it turned out to seem to be more effortful. Some (not yet used) theorems are the remnants of this endeavor...

@david-a-wheeler could you inform Freek again, please? And update the Metamath pages about the 100 Theorem List? Thanks a lot!

**Comment by david-a-wheeler** [comment]
@avekens - Congrats!!! That is fantastic. I will definitely add that and alert Freek. It may be slightly delayed because I'm fighting strep, but I will get there!

**Comment by avekens** [comment]
Thank you, Norm and David (get well soon!), for "publishing" my contribution so quickly. 
I knew that there were some editorial imperfections, and detected some more now the theorems are available on the web site (especially the HTML in section "The Cayley-Hamilton theorem"), I will improve the comments and maybe restructure/rearrange the theorems in the next days. Since the main theorem is (and remains) proven, I'll close this issue.
