### ISSUE TITLE
Semirings

### ISSUE THREAD

**Issue by avekens** [metamath/set.mm#1063]
On my way towards proving the Cayley-Hamilton theorem (see #1056), I need the binomial theorem for arbitrary rings. Unfortunately, it was only available for complex numbers (~ binom ). Therefore, I had to prove it by myself (see PR #1062, ~ crngbinom ). To be most general, I proved it for semirings ( ~ srgbinom ). Semirings are, however, defined in TA's Mathbox only (@tirix : great work, most theorems I needed were provided by you already), and I had to prove some additional theorems which I needed to proof the binomial theorem and which are already available for rings. 

I think the concept of semirings is very important and therefore worth to be moved to the main part of set.mm (and since theorems in my Mathbox depend on it, the corresponding definition and theorems should be moved also by convention).

The question is where to place the corresponding section "Semirings" of TA's Mathbox: Since semirings are more general than rings, it should be placed before (or at the beginning of) section "10.4 Rings". On the other hand, semiring are some kind of special, so section "Semirings" could also be placed after section "10.8.5 Left regular elements. More kinds of rings". 

@nmegill  @digama0 @tirix @benjub Are there any suggestions/preferences where to place it? I would prefer to place it between "10.4.1 Multiplicative Group" and "10.4.2 Definition and basic properties").

If there are no objections, I would move section "Semirings" of TA's Mathbox and some related theorems from my Mathbox to the main part in the near future.

**Comment by tirix** [comment]
Sounds great!

I agree the semirings are more general than rings, so we shall place them before, rather than in the other section which would be special rings.

**Comment by benjub** [comment]
Congratulations to @avekens (and also to @tirix for the foundational work) ! Your suggestion sounds like a good place to insert this material.

A few remarks:
* Comment of df-srg: in the distributivity condition, addition and multiplication are switched.  I would write: "... and where multiplication is (left- and right-) distributive over addition."  At the end of the comment, I would also add: 'Note that our semirings are unital.  Semirings are sometimes called "rigs", being "rings without negatives".'
* It looks like the binomial theorem also holds in the non-unital case (that is, in a "rg") and actually, the additive unit is not needed either.  I don't know how much support there is for that, neither if it is worth formalizing this.  An example would be the integrable nonnegative (resp. positive) bounded functions on \R.
* nn0srg: nonnegative numbers --> nonnegative complex numbers ; rge0srg: non-negative --> nonnegative ; in both: the final period is misplaced.
* srgbinomlemA, srgbinomlemB : write lowercase a and b (I think capital letters in label are reserved for special cases such as OLD and ALT).
* I do not know the best way to signal important theorems... Maybe you could put in the head comment of your subsection "The binomial theorem for semirings" something like "In this section, we prove the binomial theorem for semirings, ~ srgbinom ."  This looks redundant, but this has the advantage of clearly signaling srgbinom as the main theorem of that subsection.

**Comment by avekens** [comment]
Done with PR #1083. @benjub thank you very much for your hints and proposals. I took all of them into account. Especially to mention the main theorem(s) in the section comment is a good idea.
