### ISSUE TITLE
iset.mm: construct positive rationals via equivalence classes

### ISSUE THREAD

**Issue by jkingdon** [metamath/set.mm#1085]
The current definition, of choosing a canonical fraction (the one with the smallest possible denominator), as seen in http://us2.metamath.org/ileuni/df-nq.html (copied from set.mm) seems to rely on "every set of natural numbers has a minimal element" (which we don't have as shown at https://github.com/metamath/set.mm/pull/1084 ) or similar propositions. This is seen for example in the use of rexnal at http://us2.metamath.org/mpeuni/nqereu.html .

Using quotients or equivalence classes is what the HoTT book does (and even what pre-2013 set.mm did if I remember right).

I'm putting this into a github issue in case someone wants to weigh in or sees a solution which is not apparent to me.

**Comment by digama0** [comment]
The correct intuitionistic analogue of that statement is "every decidable set of natural numbers has a minimal element". AFAIK there shouldn't be any problems porting the definition.

**Comment by jkingdon** [comment]
OK, "list numbers up to a given bound and return the first element" was one of the things I thought of. Maybe it is easier than I realize to formalize that.

I did get as far as proving
```
   |- (  ( ( a e. N. /\ b e. N. ) /\ z e. ( N. X. N. ) )
      -> DECID (  <. a , b >. ~Q z
                  -> -. ( 2nd ` z ) <N b ) )
```
but the problem seems to be somewhere in the vicinity of how you look at this across all possible z in ` ( N. X. N. ) ` .

Is the suggestion to introduce a notation, and/or some theorems, for "decidable set" and prove "every decidable (inhabited) set of natural numbers has a minimal element"? Or is there a way to express this using the notation we have so far?

And yes, the ability to express the gcd constructively (and therefore have a canonical fraction, which incidentally the HoTT book also mentions in the same section - section 11.1 if anyone wants to look) is something I've been assuming. Although I haven't been as sure whether this can be done without defining a lot more of arithmetic than set.mm has by this stage.

And as for whether a quotient set is easier (quite aside from whether it is necessary in the absence of excluded middle), that's also something I'm not super clear on. I see a quotient set at http://us2.metamath.org/mpeuni/df-nr.html but I haven't really read through a lot of the proofs which use that (or the canonical representation approach for that matter).

**Comment by jkingdon** [comment]
My work so far (using the quotient set approach) is at https://github.com/metamath/set.mm/compare/develop...jkingdon:iset-nqer in case anyone wants to follow along.

As far as I can tell, this is going to work (as far as positive fractions) without much fuss. If so I should have a pull request for this section within days (or maybe a bit longer, not because of any big problems, so far at least, just because there are renames and other minor differences between 2012 set.mm and current iset.mm).

**Comment by jkingdon** [comment]
OK, so "a few days" was overoptimistic. But this work seems to be going smoothly so far - at https://github.com/metamath/set.mm/compare/develop...jkingdon:iset-nqer . It is done through addcomnq and there are about 29 theorems left through archnq (which is the last theorem before starting to construct the reals).
