### ISSUE TITLE
Consistentify the name of Mel O'Cat

### ISSUE THREAD

**Issue by david-a-wheeler** [metamath/set.mm#1146]
@benjub noted in PR https://github.com/metamath/set.mm/pull/1144

> While you're looking at contributions, I noticed that in set.mm, there are:
> 19 occurrences of "ed by O'Cat"
> 1 occurrence of "ed by Mel L. O'Cat"
> and the key on line 34 associates "ML" with "Mel L. O'Cat".

I think we should use the key where possible, in this case,  "Mel L. O'Cat".

@nmegill - seem okay?

**Comment by nmegill** [comment]
> > and the key on line 34 associates "ML" with "Mel L. O'Cat".

Actually it is MO.

> 
> I think we should use the key where possible, in this case, "Mel L. O'Cat".

That's fine.

**Comment by wlammen** [comment]
@david-a-wheeler I noticed that (my version of) rewrap rips spelled out names like Mel L. O'Cat or mine apart again.  While this does not disturb IMO readability, your gource tools may choke on that.
Solutions?

**Comment by david-a-wheeler** [comment]
@wlammen - my gource tools should handle line breaks just fine. I expect them. Of course, it's possible there's a bug, but I would treat that as a bug and fix it. So please go ahead and rewrap and carry on.
