### ISSUE TITLE
Metamath 100 proof #74 (2/100) - use nnind by Norman Megill, not findes by Raph Levien

### ISSUE THREAD

**Issue by david-a-wheeler** [metamath/set.mm#1159]
We need to straighten out the entry of Metamath 100 proof # 74 (2/100), that is, the second proven proof in the Metamath 100. I think we should refer to nnind everywhere, and credit Norman Megill for it.  In notes we can note that there is a related proof by Raph Levien, findes, that was later contributed on 9-Jul-03.

This is part of an overall careful review of the Metamath 100 (I've found 6 things that are odd about the author data I need to check through, and this is the first one).

@nmegill - do you object to this change?  Here are the details.  I can make a proposed fix, but I first want to confirm that this is the right thing to do.

Currently we have a muddle, where nnind is referenced & is claimed to be done by Raph, which isn't quite true.

In https://docs.google.com/spreadsheets/d/1jcLOp_jF4sPrVPdPedL_ZWebXp8oYEQOSmbWb168YHE/edit#gid=0
It is currently listed as this:
1997-01-10 | 2 |   | 74 | The Principle of Mathematical Induction | Raph Levien | http://us.metamath.org/mpegif/nnind.html |  
-- | -- | -- | -- | -- | -- | -- | --

And in the page http://us.metamath.org/mm_100.html it says;
> 74. The Principle of Mathematical Induction (findes, by Raph Levien, 2003-07-09) - there are many versions of Mathematical Induction in set.mm; another version is nnind (by Norman Megill, 1997-01-10).

But when I do a git checkout ba18c14ef9713308a7efe1dfbc8049975f52f56a (archive name set.mm.2007-04-29-grothprim)

We see:

~~~~
  ${
    $d x y z $.  $d y z ph $.
    findes.1 $e |- [ (/) / x ] ph $.
    findes.2 $e |- ( x e. om -> ( ph -> [ suc x / x ] ph ) ) $.
    $( Finite induction with explicit substitution.  The first hypothesis is
       the basis and the second is the induction hypothesis.  Theorem Schema
       22 of [Suppes] p. 136. (Contributed by Raph Levien, 9-Jul-03.) $)
    findes $p |- ( x e. om -> ph ) $= .... $.      $( [29-Jul-2003] $)
  $}
~~~~

~~~~
    $( Principle of Mathematical Induction (inference schema).  The first
       four hypotheses give us the substitution instances we need; the last
       two are the basis and the induction hypothesis.  See ~ nnaddclt for
       an example of its use.  See ~ nn0ind for induction on nonnegative
       integers and ~ uzind , ~ uzind4 for induction on upper partitions of
       integers.  See ~ indstr for strong induction. $)
    nnind $p |- ( A e. NN -> ta ) $= ... $.
      $( [10-Jan-1997] $)
  $}
~~~~

When you checkout the current version you see that nnind was (Revised by Mario Carneiro, 16-Jun-2013.).

**Comment by nmegill** [comment]
Actually I believe the first induction proof was finds by me (14-Apr-1995).  I originally chose Raph's findes (9-Jul-2003) to display as an MM100 theorem because it was compact and more traditional-looking with explicit substitution.  I'm not sure how or when it was changed to nnind (10-Jan-1997).  Maybe it was me, I don't remember, but if it was, perhaps I thought NN is less obscure than ordinal numbers for non-mathematicians (although I think now I would have chosen findes again).

I am not that concerned about myself being credited and just wanted to pick a good representative example in set.mm.  But if you want to strictly follow precedence rules, finds should be used.  If you want what I would consider the best display example, it would be findes (credited to Raph).

**Comment by david-a-wheeler** [comment]
I think we should use `finds`. I think we should be strictly following precedence rules where we reasonably can, listing the primary label and author by "first appearance" - so the one that happened first gets the credit.  Also, ideally the "primary" one we reference would be between 1994-08-07 and 1998-06-08, because then we don't have to renumber the chronological order :-).

Current list by date:
> 1994-08-07 | 1 |   | 63 | Cantor's Theorem
> 1997-01-10 | 2 |   | 74 | The Principle of Mathematical Induction
> 1998-06-08 | 3 |   | 25 | Schroeder-Bernstein Theorem

We  must list a "primary" author name in the Google docs document and in Freek's list.  However, within Metamath 100 (which Freek points to) we can provide much more information and alternatives.

So I propose that in we make "finds" the primary (Contributed by NM, 14-Apr-1995.).  That is more accurately the first one.  That will require a small tweak to the Google docs (and lose Raph some credit, sorry!).  It'll also require a small tweak for Freek.

We'll also need to modify the Metamath 100 page, but we can then give lots of credit there. It currently says:

> 74. The Principle of Mathematical Induction (findes, by Raph Levien, 2003-07-09) - there are many versions of Mathematical Induction in set.mm; another version is nnind (by Norman Megill, 1997-01-10).

Proposed new version:

> 74. The Principle of Mathematical Induction (finds, by Norman Megill, 1995-04-14).  There are many versions of Mathematical Induction in set.mm. Theorem findes (by Raph Levien,  9-Jul-2003) is a compact and more traditional-looking version with explicit substitution. Another alternative is nnind (by Norman Megill, 10-Jan-1997), which uses natural numbers instead of ordinal numbers and might be less obscure for non-mathematicians.

**Comment by digama0** [comment]
I think in cases where this makes a difference, we should refer to both on
the MM 100 page: the chronologically first eligible result, and the
"preferred/modern" version of it, and their authors and dates. Perhaps
something like "Theorem of Foo (foo, by Some Guy, 2014-01-01, first proved
as fooALT by Other Guy, 1997-01-01)." Chronological order should follow
only the earlier date. (The same comment applies to demoivre vs
demoivreALT.)
