### ISSUE TITLE
Record within set.mm every Metamath 100 proof

### ISSUE THREAD

**Issue by david-a-wheeler** [metamath/set.mm#1162]
It's not obvious within set.mm when a proof is in the Metamath 100.  That matters, for example, when a theorem is renamed... it's a pain to track.  If there was text within set.mm, it'd be easy to verify that the "correct" one was referenced.  Also, I think some readers would want to know that, it certainly indicates some kind of "importance" to some people.

So for each Metamath 100 proof, I recommend adding this format within the set.mm comments just before the (Contributed by...) :

> This is Metamath 100 proof #NUMBER (chronologically ORDERNUM/100).

The NUMBER is the order of problems, while ORDERNUMBER is the order we solved (ORDERNUM=1 is the first one we solved).

For example in sii, it'd say:

> This is Metamath 100 proof # 78 (chronologically 13/100).

I can create the changes to add them, but I want to make sure it's okay first.

@nmegill @digama0 ?

**Comment by benjub** [comment]
To be honest, I think you're attaching way too much importance to this "100 theorems" list. Referring to it in set.mm would be like mentioning in Einstein's complete works that he was named "man of the year 1905" by the Time magazine.
Plus: this list is subjective, lacunary... I'm not sure who established it but probably not a mathematician or panel of mathematicians. That said, I still think it's nice to try and prove them in Metamath, for sport, and to show that Metamath can compete with other tools, but not much more.

**Comment by david-a-wheeler** [comment]
@benjub - It doesn't matter whether or not *I* think this list is important or useful. What matters is that many other people who develop and select math verification tools think this list is useful. A number of articles that try to identify the "leading" verifiers look to this challenge list, so being high up is important to many people. Also note that many tools are represented on this list;  you may think it's irrelevant, but other people do not and *do* track how well tools do against it.

Most of the challenges are not high-end mathematics, but that would be too much (today) to ask of today's math verifiers.

I think the effort to expand set.mm to cover some of these items has been useful to help expand set.mm.  In several cases people have expanded various areas so that a particular proof could be completed, and those areas were then reusable by others.  I think the same is true for other tools.  Thus, the number of completed proofs is at least a partial indicator of the completeness of a given verifier and its database.

Of course the list is subjective. Any such list would be subjective.  But it can still be *useful*.

**Comment by nmegill** [comment]
I encourage doing this because it will help prevent accidental renames.

**Comment by nmegill** [comment]
(I got pulled away; I'm back) 

I encourage doing this because it will help prevent renames in set.mm that aren't simultaneously made to the MM100 list.

However, I think it is sufficient to have just "This is a Metamath 100 theorem." or similar.  Including "# 78 (chronologically 13/100)" is redundant and means more work in the future maintaining it for new theorems.   I don't think many people care about the ordering, and if they do it can be found on the MM100 page.

**Comment by digama0** [comment]
I agree that the chronological order doesn't matter other than on the MM100 page, but the number of the theorem is useful for being able to find it in the list, and that ordering isn't likely to change.

**Comment by nmegill** [comment]
> I agree that the chronological order doesn't matter other than on the MM100 page, but the number of the theorem is useful for being able to find it in the list, and that ordering isn't likely to change.

I mainly care about identifying it as MM100 to help prevent future broken links, and otherwise don't have a strong preference.  I'll go along with Mario if he thinks that is useful.

**Comment by david-a-wheeler** [comment]
The main number of the metamath proof can't change, so I like Mario's suggestion. Let's do that.

**Comment by david-a-wheeler** [comment]
Basically, we will omit the chronological order but keep the main number so it can be easily found.

**Comment by david-a-wheeler** [comment]
We've completed this, so closing.
