### ISSUE TITLE
Add note to qnnen to explain contributed/revised

### ISSUE THREAD

**Issue by david-a-wheeler** [metamath/set.mm#1164]
I'm comparing Metamath 100 contribution statements with set.mm, and found a curious situation with qnnen.  The set.mm file has Norman Megill as the original contributor, with Mario revising it, but everything else refers to Mario's revision.

I propose that the following text be added to qnnen - is that reasonable?:

> For purposes of the Metamath 100 list, we are considering Mario's revision as the date this proof was completed.

Here's the background.

set.mm says:

> The rational numbers are countable. This proof does not use the Axiom of Choice, even though it uses an onto function, because the base set ( ZZ X. NN ) is numerable. Exercise 2 of [Enderton] p. 133. (Contributed by NM, 31-Jul-2004.) (Revised by Mario Carneiro, 3-Mar-2013.)

There was a qnnenOLD that was since deleted; set.mm says:
> 17-Feb-14 qnnenOLD  ---         deleted; see qnnen

The Google docs page on Metamath 100 says:
> 2013-03-03      19              3       The Denumerability of the Rational Numbers      Mario Carneiro  http://us.metamath.org/mpegif/qnnen.html

Metamath 100 #3 <http://us.metamath.org/mm_100.html#3> says:
>3. The Denumerability of the Rational Numbers (qnnen, revised by Mario Carneiro, 2013-03-03)

Freek's page http://www.cs.ru.nl/~freek/100/#3 :
> 3. The Denumerability of the Rational Numbers
>    Metamath, revised by Mario Carneiro: statement

**Comment by david-a-wheeler** [comment]
@nmegill @digama0 - seem reasonable?

**Comment by david-a-wheeler** [comment]
One reason to do this: If we use the date of NM's proof, we have to renumber the chronological order of almost all the Metamath 100 proofs.  Ugh.  It looks like the date of Mario's revision was intentionally used as the "real" date, and since that was intentional, let's be sure to document that.

**Comment by nmegill** [comment]
This is fine.  Do whatever is easiest.
