### ISSUE TITLE
iset.mm: show real addition/multiplication is closed

### ISSUE THREAD

**Issue by jkingdon** [metamath/set.mm#1216]
Many parts of this are already proved, basically that the sum/product is inhabited ( http://us2.metamath.org:88/ileuni/genpml.html ), rounded ( http://us2.metamath.org:88/ileuni/genprndl.html ), and disjoint ( http://us2.metamath.org:88/ileuni/genpdisj.html ). In the case of inhabited and rounded we'll need the upper cut too but that should be easy to prove using the same technique we did for the lower cut.

This leaves locatedness. If memory serves, one of my references (sorry, forget which one) described locatedness as "clasically superfluous" which if so reduces the places we can look for a literature reference.

The one published proof I was able to find was Lemma 11.16 on page 53 of Andrej Bauer and Paul Taylor (3 June 2009), "The Dedekind Reals in Abstract Stone Duality", http://www.paultaylor.eu/ASD/dedras.pdf . At first glance this proof requires formalizing sequences (for Proposition 11.15) and maybe subtraction (although perhaps using E. and addition, basically like http://us2.metamath.org:88/ileuni/ltexnqq.html does, would suffice for the latter).

If anyone has tips for (a) formalizing this proof, or (b) an alternative approach to proving locatedness of the sum/product, please post here.

**Comment by jkingdon** [comment]
The more I look at the proof in Bauer and Taylor (cited above), the less scary it looks.

My current plan is to prove the following which I think will follow easily enough from theorems like `halfnqq`. I may also need something like http://us.metamath.org/mpeuni/archnq.html but my current thinking is I don't really need sequences as such, just a large enough positive integer (I won't try to summarize the proof at the moment beyond just pointing to Bauer and Taylor).

```
    $( A Dedekind cut is arithmetically located.  Part of Proposition 11.15 of
       Andrej Bauer and Paul Taylor (3 June 2009), "The Dedekind Reals in
       Abstract Stone Duality", http://www.paultaylor.eu/ASD/dedras.pdf ,
       p. 52, slightly modified.  It states that given a tolerance ` P ` ,
       there are elements of the lower and upper cut which are within that
       tolerance of each other.  (Contributed by Jim Kingdon, 22-Oct-2019.) $)
    prarloc $p |- ( ( <. L , U >. e. P. /\ P e. Q. ) ->
      E. a e. L E. b e. U b <Q ( a +Q P ) ) $=
        ? $.
```

**Comment by jkingdon** [comment]
So on the one hand, the proof of arithmetical locatedness from Bauer and Taylor seems like the right approach, and I think I understand it relatively well.

Here's my thinking. Prove something like prarloclem3 below. The proof would be by induction on X, and the induction step goes like this: Given indexes `y` and `y + 2 + ( X + 1 )`, we know `y + 1 < y + 1 + ( X + 1 )`. By locatedness, either `element-at(y + 1) e. L` or `element-at(y + 1 + ( X + 1 )) e. U`.  If `element-at(y + 1) e. L`, then we can apply the induction hypothesis on the interval from y + 1 to `y + 2 + ( X + 1 )`. If `element-at(y + 1 + ( X + 1 )) e. U`, apply the induction hypothesis on the internal from y to `y + 1 + ( X + 1 )`.  (By element-at(z) I mean A + z times P).

```
  ${
    $( Contracting an interval which straddles a Dedekind cut.
      (Contributed by Jim Kingdon, 27-Oct-2019.) $)
    prarloclem3 $p |- ( ( ( <. L , U >. e. P. /\ A e. L ) /\
      ( X e. _om /\ P e. Q. ) /\
      E. y e. _om ( ( A +Q ( [ <. y , 1o >. ] ~Q .Q P ) ) e. L
        /\ ( A +Q
          ( [ <. ( ( y +o 2o ) +o X ) , 1o >. ] ~Q .Q P ) ) e. U ) ) ->
      E. j e. _om ( ( A +Q ( [ <. j , 1o >. ] ~Q .Q P ) ) e. L /\
        ( A +Q ( ( [ <. j , 1o >. ] ~Q +Q ( 1Q +Q 1Q ) ) .Q P ) ) e. U ) ) $=
      ? $.
  $}
```

The problem with formalizing the proof sketched out above is that it relies on having arithmetic on nonnegative rationals, not just positive rationals (pretty much everywhere there is a `e. _om`  it is so that zero is possible).

Developing a theory of nonnegative rationals (perhaps going as far back as `if`) is the obvious way out of this. It might be tempting to subtract ` P ` from ` A ` to get something which we could use a 1-based rather than a 0-based index on, but of course there is no assurance that ` A ` is greater than ` P ` (we're working on positive rationals, or cuts thereof, here).

Maybe there is a way to add one to the indexes (which might be part of "develop a theory of nonnegative rationals", sort of, but maybe easier than cases for zero or nonzero?). I'm open to suggestions if people have ideas.

**Comment by jkingdon** [comment]
Since it has been a while, I'll add a status report. The branch https://github.com/jkingdon/set.mm/tree/iset-prarloc contains most of the proof of Lemma 6.16 from [BauerTaylor] (well, actually a special case of that lemma, but I think it suffices for us):

```
    prarloclem $p |- ( ( ( <. L , U >. e. P. /\ A e. L ) /\
      ( N e. N. /\ P e. Q. /\ 1o <N N ) /\
      ( A +Q ( [ <. N , 1o >. ] ~Q .Q P ) ) e. U ) ->
      E. j e. _om ( ( A +Q0 ( [ <. j , 1o >. ] ~Q0 .Q0 P ) ) e. L /\
        ( A +Q ( [ <. ( j +o 2o ) , 1o >. ] ~Q .Q P ) ) e. U ) ) $=
```

The remaining pieces of that lemma are:

(1) a lot of development of arithmetic on non-negative fractions (as opposed to the positive fractions found in set.mm at this point). This is going OK but I'm currently in the process of developing new analogues to http://us.metamath.org/ileuni/oviec.html and its lemmas. The immediate need is because a positive fraction is an element of  `_om X. N.` and oviec requires `S X. S` where the two sets in the cartesian product are the same. I'm fixing that but also am doing all of this development by hardcoding non-negative fractions, rather than trying to make it all abstract for any operation. The goal here is to remove a number of layers of abstraction including the separate notation for "pre-multiplication" as found in iset.mm's development of positive fractions. We'll see what the result looks like at the end but so far I find this easier to work with and easier to read.

(2) there are a few details left for the lemma, but I think they are straightforward.

After the lemma, next will be formalizing the sentence "Then the Archimedean principle gives some
k : N with u − d < khp, where 0 < h + h < 1 by Lemma 11.4" from BauerTaylor. And I think that's most of what we need for arithmetic locatedness (`prarloc` on that branch).

And then I think closure of real addition/multiplication follows fairly easily, as described at the start of this issue.

**Comment by jkingdon** [comment]
Status report: all the hard parts of arithmetic locatedness (as described above) are done on the https://github.com/jkingdon/set.mm/tree/iset-prarloc branch. There just remain 7 helper theorems which I expect to be easy.

**Comment by david-a-wheeler** [comment]
Cool. This looks like big progress towards having "normal" numbers in iset.mm!

**Comment by jkingdon** [comment]
> Cool. This looks like big progress towards having "normal" numbers in iset.mm!

Heh. The IZF rationals are a lot more "normal" (e.g. http://us.metamath.org/ileuni/nqtri3or.html ) than the IZF reals. Having said that, I'm hoping we'll be able to have rationals and integers as subsets of complex numbers, as in set.mm. They should have the usual rational number properties as far as I know.

Also, the IZF reals are cool in their own way (for example, "don't compare reals for equality" is sort of a rule of thumb in computation but it also has an analogue in the math of IZF reals).

**Comment by jkingdon** [comment]
> Cool. This looks like big progress towards having "normal" numbers in iset.mm!

Thanks for the kind words. So here's roughly where we stand on closure:

1. In terms of roundedness, disjointness, and inhabitedness, there are a few details around upper cuts and http://us2.metamath.org/mpeuni/addclprlem2.html (or whatever we end up replacing it with) type stuff. Shouldn't be hard but it has been a while since I have thought about anything except locatedness. So I don't remember exactly how close this is.

2. Locatedness of addition (Lemma 11.16 of BauerTaylor) looks like a noticeable effort to formalize. I think we have most of the pieces, such as arithmetic locatedness, http://us.metamath.org/ileuni/ltbtwnnq.html , etc, but I haven't gone through the proof in enough detail to be sure (probably I'll do so as I start formalizing it, but the proof from BauerTaylor does look like the right approach).

3. Locatedness of multiplication appears to be pretty different than addition. See Lemma 12.9 of BauerTaylor which relies on some other concepts which might need to be developed. Therefore, I plan on focusing just on addition until addition is done.

**Comment by jkingdon** [comment]
Closure of addition is done. Closure of multiplication will come after http://us.metamath.org/mpeuni/nqpr.html and a few other things.
