### ISSUE TITLE
Improve English definition for poset

### ISSUE THREAD

**Issue by david-a-wheeler** [metamath/set.mm#1285]
PR #1281 provided a simple English definition for poset.

@benjub proposes improving that definition to something like this that is also precise, e.g.:

> A poset is a set equipped with a partial order, that is, a binary relation which is reflexive, antisymmetric, and transitive.

That is more precise, but if we do that, we probably need to make it clear that "is equal" is permitted (text TBD).

**Comment by david-a-wheeler** [comment]
For comparison, the current definition in df-poset is:

> Define the class of partially ordered sets (posets).  A poset is a set
> (the poset "base set") together with a binary relation indicating that,
> for certain pairs of elements in the set, one of the elements precedes
> or has the same position as the other in the ordering.

**Comment by david-a-wheeler** [comment]
I propose the following:

> Define the class of partially ordered sets (posets). A poset is a set equipped with a partial order, that is, a binary relation ( ` le ` ) which is reflexive, antisymmetric, and transitive. Unlike a total order, in a partial order there may be pairs of elements where neither precedes the other.

**Comment by benjub** [comment]
Thanks for the proposal. I'm not sure how your "(le)" is supposed to be rendered. Maybe remove the two parenthetical statements (about base set and le), and add the sentence:

> In our formalism of extensible structures, the base set of a poset \` f  \` is denoted by \` ( Base \` f ) \` and its partial order by \` ( le \` f ) \` (for "less than or equal to").

or something like that. But globally, I'm fine with your proposal.

**Comment by david-a-wheeler** [comment]
That makes sense. One nit: Inside a comment the "`" needs to doubled
if it's part of the expression.

I think this is the final result:

~~~~
Define the class of partially ordered sets (posets).
A poset is a set equipped with a partial order, that is,
a binary relation which is reflexive,
antisymmetric, and transitive.
Unlike a total order, in a partial order there may be pairs of elements
where neither precedes the other.
In our formalism of extensible structures, the base set of a poset ` f `
is denoted by ` ( Base `` f ) ` and its partial order by ` ( le `` f ) `
(for "less than or equal to").
~~~~

**Comment by benjub** [comment]
Sounds good.  I'm not sure of the grammatical correctness of "Unlike a total order, in a partial order..." So please check and submit !

**Comment by benjub** [comment]
@david-a-wheeler I just noticed that without knowing it, we actually arrived at a wording very close to that of df-preset !
