### ISSUE TITLE
Should "preset" be "proset"?

### ISSUE THREAD

**Issue by david-a-wheeler** [metamath/set.mm#1289]
@benjub recommended in pull request https://github.com/metamath/set.mm/pull/1286 the following (which I'm moving to its own issue):

> I advise to change
everywhere (i.e. in comments, labels, symbols) "preset" to "proset".
Indeed, "proset" can only mean "preordered set", whereas "preset" can mean
several things (including "set without an equality relation"). Plus,
"proset" is apparently more widely used.  If you don't like "proset"
(personally, I'm not fond of it and I think it is dangerously close to
"poset"), then only use the non-abbreviated "preordered set" in comments
(and still "proset" in labels and symbols).

**Comment by benjub** [comment]
I will go ahead and answer "yes" to the title question ! To build on what I wrote above:
1. "proset" is often used for "preordered set", see https://ncatlab.org/nlab/show/preorder and https://en.wikipedia.org/wiki/Preorder, which both mention "proset" but not "preset".
2. "preset" has a different meaning, see https://ncatlab.org/nlab/show/preset of "set without an equality relation".

I'm going to do a PR soon to make the change.
