### ISSUE TITLE
neqned vs. neneqad

### ISSUE THREAD

**Issue by avekens** [metamath/set.mm#1338]
See discussion in the Google group (https://groups.google.com/d/msg/metamath/8kC6sIXvhqw/SaGYfjlhCQAJ):

- On Saturday, December 21, 2019 at 10:32:09 AM UTC+1, ookami wrote: 

> neqned is a duplicate of neneqad. I suggest merging both into one, preferring the name, attributions and explanation of the older neneqad.

- On Saturday, December 21, 2019,  I replied:

> Ups, neneqad is directly following neqned - I didn't notice that (because I only looked for neneqd and copied neqned directly beneath it...)
> Of course both should be merged, and the attributions and explanation of the older neneqad should be kept. As for the name, however, I would suggest to take the new one "neqned" - it  is easier to remember, symmetric to "neneqd", shorter and, finally, I do not understand the meaning of the "a" in "neneqad".
> However, "neqned" is used 39 times, "neneqad" 81 times, but that's only a minor argument for "neneqad" (find&replace has to be done anyway).

Who will/wants to decide which name we should keep?

**Comment by benjub** [comment]
I agree with @avekens for the merging and the label (that is, neqned) for the reasons he gave.

**Comment by nmegill** [comment]
I also prefer neqned instead of neneqad, because it is the reverse of neneqd (so the name reverses "ne" for A =/= B and "neq" for -. A = B).

**Comment by avekens** [comment]
So we have a 3:0 for neqned now. @glacode @wlammen do you accept this? I would make the corresponding changes in set.mm then.

**Comment by wlammen** [comment]
Ok from me

**Comment by glacode** [comment]
On 22/12/2019 17:40, avekens wrote:
> So we have a 3:0 for neqned now. @glacode @wlammen do you accept this? I would make the corresponding changes in set.mm then.
>
Sure, no problem

**Comment by avekens** [comment]
Done by PR #1340.
