### ISSUE TITLE
Definition of the ring isomorphism relation

### ISSUE THREAD

**Issue by avekens** [metamath/set.mm#1357]
As pointed out by @benjub in #1339, a ring is isomorphic to every ring of scalar matrices over this ring with positive dimension. With PR #1356 , I provided a proof for this, see ~scmatric.  Moreover, I have shown several additional ring isomorphisms in my latest contributions.

To express these isomorphisms more concisely, I would like to have a definition of the ring isomorphism relation, analogous to ~ df-gic ( ` ~=g ` ). Although there is already such a definition in JM's mathbox (see ~ df-risc : ` ~=r ` ), this  cannot be used because it is based on the deprecated definition ` RingOps ` for rings, see ~ df-rngo . Therefore, I provided a new definition ~ df-ric in my mathbox, using the symbol ` ~=R ` . By this, I could prove ~ scmatric :

A = ( N Mat R ) & C = ( N ScMat R ) & S = ( A |`s C ) 
=> ( ( N e. Fin /\ N =/= (/) /\ R e. Ring ) -> R ~=R S )

I would like to move this definition and the related theorems to the main part of set.mm, using it also for the other ring isomorphisms. In the main part, however, the symbol ` ~=r ` should be used, because it corresponds to the symbol for the group isomorphism relation  ` ~=g `. @nmegill: is it allowed to switch the symbols, meaning that ~ df-risc will define ` ~=R ` (still in JM's mathbox only) and ~ df-ric will define ` ~=r `? Shall be JM be contacted/asked before? Do you have his contact data?

**Comment by nmegill** [comment]
> @nmegill: is it allowed to switch the symbols, meaning that ~ df-risc will define `~=R` (still in JM's mathbox only) and ~ df-ric will define `~=r`? Shall be JM be contacted/asked before? Do you have his contact data?

Feel free to swap the symbols.  Jeff's last contribution was 2011, so it's near certain that he wouldn't mind; anyway, we have a disclaimer in the ~mathbox comment.

He certainly contributed some fine work, though.  I have only an old email at Notre Dame, where he got his PhD.  Google shows he is now a math professor at Purdue.  But I don't think it is necessary to contact him about this.

**Comment by avekens** [comment]
Done with PR #1365
