### ISSUE TITLE
Add complex numbers to iset.mm

### ISSUE THREAD

**Issue by jkingdon** [metamath/set.mm#1398]
The process of adding complex numbers was begun in #1395 but this issue is more about the complex number axioms from set.mm.

Trichotomy, http://us.metamath.org/mpeuni/axpre-lttri.html , would presumably need to be changed to `<RR Or RR` (where `Or` is as in iset.mm, weak linearity as defined in http://us.metamath.org/ileuni/df-iso.html ) or something of the sort.

The hard part of course, is supremum. The Least Upper Bound property as stated in http://us.metamath.org/mpeuni/axpre-sup.html does not hold (my source is https://en.wikipedia.org/wiki/Constructive_analysis#The_least_upper_bound_principle_and_compact_sets ). Something like http://us.metamath.org/mpeuni/dedekind.html might be getting warmer, although I don't think it works as-is (most obviously, it is doing case elimination on whether ` A ` and ` B ` are empty, but I'm also not sure I fully understand the bits relating to `<` versus `<=` in a context without excluded middle.

As one data point, the proof of the intermediate value theorem for monotonic functions, Theorem 5.5 of [Bauer], constructs a Dedekind cut directly. It does not rely on any flavor of a supremum property.

So tactically in terms of taking on this work in manageable pieces, the options seem to be:

(1) define axioms as in set.mm as we go, just don't expect them to be a complete set for a while,

(2) just define theorems like http://us.metamath.org/mpeuni/cnex.html and skip the whole complex axiom context until later.

I guess my current thinking is that (1) is harmless, reduces the need to explain divergence from set.mm, and sets us up for a day in which we have defined a complete set of complex number axioms. The biggest downside is that certain pieces don't apply (for example http://us.metamath.org/mpeuni/cnexALT.html which relies on supremum) and we might end up with something which lacks coherence for a while.

**Comment by jkingdon** [comment]
By the way, the above list is not complete, for example "not equal to zero" needs to be changed to "apart from zero" in http://us.metamath.org/mpeuni/ax-rrecex.html . But the basic question of what to do until we have a complete set remains.

**Comment by sctfn** [comment]
You might want to consider adapting the constructive real number axioms at http://www.cs.ru.nl/~herman/PUBS/Types00-GeuversNiqui.pdf and/or https://users.dimi.uniud.it/~pietro.digianantonio/papers/copy_pdf/RealsAxioms.pdf. The first set has been used in Coq and the second is in the spirit of a tutorial. 

-Scott

**Comment by jkingdon** [comment]
> You might want to consider adapting the constructive real number axioms at http://www.cs.ru.nl/~herman/PUBS/Types00-GeuversNiqui.pdf and/or https://users.dimi.uniud.it/~pietro.digianantonio/papers/copy_pdf/RealsAxioms.pdf. The first set has been used in Coq and the second is in the spirit of a tutorial.

Thanks for the links!

There's a lot there (in both of those papers) but hopefully they'll be of use especially once we get past the simpler complex number axioms.
