### ISSUE TITLE
Label change proposals

### ISSUE THREAD

**Issue by benjub** [metamath/set.mm#1412]
I propose the three label changes:
> cabel --> cabl
> pgrple2abel --> pgrple2abl
> pgrpgt2nabel --> pgrpgt2nabl

(these last two are in @avekens's mathbox).

Rational: all other theorems about abelian groups use "abl" in their labels (beginning with df-abl).  In addition, "abel" is often used in theorems related to "ELements of class ABstractions".

Then, there is Abel's theorem abelth and its lemmas. I think they can stay as is.

If @nmegill and @avekens give me the green light, I will do these three changes and document only the first one at the top of set.mm, and then close the issue.

**Comment by nmegill** [comment]
I agree.

**Comment by avekens** [comment]
I also agree. I will change the three labels in my next update.

**Comment by avekens** [comment]
With PR #1415, the labelspgrple2abel and pgrpgt2nabel were changed.
Because cabel is used very often (219 times), and I had severe merge conflicts anyway, I did not change cabel yet. Maybe it would be better if a GitHub-Admin will do it (@nmegill ?).

**Comment by benjub** [comment]
Thanks @avekens .  @nmegill : is it better that you do the change cabel --> cabl as @avekens suggest, for fear of merge conflicts, or should I do it ?

**Comment by nmegill** [comment]
@benjub - OK, I will do this soon.
