### ISSUE TITLE
iscatd2's description is self-referential 

### ISSUE THREAD

**Issue by Prosfilaes** [metamath/set.mm#1436]
Theorem | iscatd2 14932* | Version of iscatd2 14932 with a uniform assumption list, for increased proof sharing capabilities.

I'm guessing this is supposed to say "Version of iscatd..."? Otherwise, the definition of what iscatd2 is supposed to be was lost somewhere along the line.

**Comment by tirix** [comment]
You're right, thanks! I've fixed that in #1440 .
