### ISSUE TITLE
GitHub fails to accept pull requests from NM

### ISSUE THREAD

**Issue by nmegill** [metamath/set.mm#1488]
I have wasted a lot of time this morning trying to resolve the following.  Whenever I try to create a PR for develop from my private repo nmfork, I get the following error page:

Looks like something went wrong!
We track these errors automatically, but if the problem persists feel free to contact us. In the meantime, try refreshing.
Contact Support — GitHub Status — @githubstatus

I have never seen this before and have given up trying to resolve it.  I found nothing relevant in from a Google search.  In the meantime, I committed the following update directly to develop:

Commit 9bb34c2 - set.mm - add 219 discouragements to 170 *ALT and *OLD stmts

So that I can move forward, I will keep committing directly until the issue is resolved and will post the commits here.

**Comment by nmegill** [comment]
I haven't had a chance to look into the GitHub problem and am still committing directly.

Commit 1c627add - set.mm - incorporates all minimizations from jobs 101 through 132

Effect on set.mm size:  set.mm has 2127 fewer lines and 172760 fewer bytes.

The minimizations from jobs 133-159 are still running.

**Comment by benjub** [comment]
Regarding Commit 1c627ad : I'm not sure the removals of the uses of ax-frege1 and ax-frege2 is what @arpie-steele intended ?

**Comment by arpie-steele** [comment]
@benjub @nmegill Thank you for your efforts. #1494 restores some of the proofs to their pre-minimized state and labels those axioms/proofs which are closest to the pure Frege1879 style as discouraged.
