### ISSUE TITLE
iset.mm should briefly explain why apartness is needed

### ISSUE THREAD

**Issue by david-a-wheeler** [metamath/set.mm#1498]
In iset.mm I see that `#` is defined using `#RR`, and `#RR = { <. x , y >. | ( ( x e. RR /\ y e. RR ) /\  ( x < y \/ y < x ) ) }`. But I didn't see any text in comments that explain *why* iset.mm needs to use "apartness" as something different from "not equal to". I guess I shouldn't be surprised that "not" causes complications, but I don't see any text briefly explaining the issue.

I think there should be a little text in iset.mm that explains iset.mm needs "apartness" to be different from "not equal". I'm sure the cited texts go into a lot of detail, but a hint within the text of iset.mm itself would be helpful.

This probably really a request for @jkingdon - but others are welcome to pipe in :-).

**Comment by jkingdon** [comment]
Yeah, there are intros in places like https://en.wikipedia.org/wiki/Apartness_relation but yeah, I agree it would be nice for the comment (especially of df-ap, to some extent df-reap) to have a few sentences with links to the relevant theorems in iset.mm. I can take a stab at this if no one else beats me to it.
