### ISSUE TITLE
mm100 points to sqr2irr not sqrt2irr

### ISSUE THREAD

**Issue by arpie-steele** [metamath/set.mm#1578]
@david-a-wheeler 
Some files still point to sqr2irr which was renamed sqrt2irr on 19-Jan-2020 in #1423

```
index.html
mmset.raw.html
mm_100.html
```

**Comment by arpie-steele** [comment]
Revised:
```
index.html (sqr2irr appears twice on line 862)
mm_100.html (sqr2irr appears twice on line 235)
mmhil.htm (sqr appears on line 967)
mmset.html (sqr2irr appears on line 2158)
mmset.raw.html (sqr2irr appears on line 2139)
scripts/gource-captions.txt (sqr2irr appears on line 11)
set-mathml.mmts (sqr or df-sqr appears 5 times between lines 416 and 1813)
symbols.html (sqr appears 9 times between lines 2835 and 2996)
```

digested from: `find . '(' -name .git -o -name '*~*' -o -name '*.BAK' -o -name '*.orig' -o -name '*.tmp*' -o -name '*.mm' -o -name discouraged ')' -prune -o -type f  -print0 | xargs -0 egrep -n --color 'sqr[^t]'`

**Comment by arpie-steele** [comment]
A separate issue but some of the the images linked in table "Theorems Involving Limits and Subspaces" in `mmhil.htm` are missing, possibly related to the removal of hypotheses.

Also `hlimunii` is a dead link, `hlimuni` is likely meant. 
And `pjth` doesn't link to what is described. `pjhtheu` is closer (a little stronger than described).

**Comment by david-a-wheeler** [comment]
@arpie-steele : Good catches on sqrt, thanks. I think I fixed them all in https://github.com/metamath/set.mm/pull/1580

Note: File `mmset.html` is a generated file, so fixing the raw file will fix it.

I did *not* try to fix the separate issue about missing images and dead links. Could you please create a separate issue for that?

**Comment by nmegill** [comment]
I will take care of the mmhil.html issues described.  I added it to my personal todo list, and there is no need to create a separate issue at this point.
