### ISSUE TITLE
New definition for "prefixes of words"

### ISSUE THREAD

**Issue by avekens** [metamath/set.mm#1648]
Motivated by the introduction of the new symbol ++ for the concatenation of words, and the discussion about the indices for words, starting either at 0 or 1 (see google group https://groups.google.com/d/topic/metamath/UwTUuNPgaB0/discussion), I looked at the theorems about words and could improve/shorten the proofs of a lot of them. Meanwhile, I observed that many theorems about subwords are actually about prefixes, i.e. subwords starting at the beginning of a word:  ` ( W substr <. 0 , L >. ) `.

I think this gives reason to provide a special definition/symbol for prefixes of words. You can find a proposal in my mathbox:

df-pref $a |- prefix = ( s e. _V , l e. NN0 |-> ( s substr <. 0 , l >. ) ) $.

By this definition, a prefix (of length ` L `) can be expressed as ` ( W prefix L ) ` instead of ` ( W substr <. 0 , L >. ) `, saving 10 characters in length (including blanks). Besides being shorter, such a definition has the advantage that it hides the "implementation detail" that the indexes of a word start with 0. Furthermore, having separate theorems for prefixes can shorten many proofs.

Because of these advantages, I like to ask for moving this definition and the related theorems into the main body of set.mm, section "5.7 Words over a set". After that, many existing theorems about prefixes could be revised accordingly (I identified already 30 of them, see theorems in my mathbox having "Could replace ~ ..." in their comments).

Regarding the names, labels and symbols, however, these could be discussed (see also the header comment of section "Prefixes of a word" in my mathbox): Would "pfx" be a better label (fragment) than "pref"? In general, is "prefix" an adequate name/symbol for subwords starting at the beginning of a word? Maybe "leading characters" or "leading symbols" or even "leading sequence of characters/symbols" would be more precise, but clumsier. A handy alternate symbol, however, could be "lead", the corresponding label (fragment) "ld" or even "lead" itself".

Searching for "prefix abbreviation" in the web, I found https://www.allacronyms.com/prefix/abbreviated, proposing "pfx" as abbreviation. Regarding the meaning of "prefix", I think it is different in automata theory/formal languages compared with linguistics, see Wikipedia "Substring" (https://en.wikipedia.org/wiki/Substring#Prefix), or https://math.stackexchange.com/questions/2190559/is-there-standard-terminology-notation-for-the-prefix-of-a-word).

As a consequence, I would like to use "pfx" as label (fragment) instead of "pref"  (1 character shorter, less ambiguous), but the symbol should remain "prefix". What do you think?

**Comment by nmegill** [comment]
Using "pfx" for the label sounds ok to me.

**Comment by david-a-wheeler** [comment]
I like this idea. It seems clearer to discuss prefixes of words then to discuss the array indices, when it is really a prefix.

**Comment by savask** [comment]
As I see it is not the case with others, but for me `( W pfx L )` or even `( W prefix L )` is a cryptic label, with the first interpretation coming to mind being "W is a prefix of L", while `( W substr <. 0 , L >. )` is understood immediately.

Also there are enough examples in set.mm where some common notion doesn't get a special symbol (for example `angval` defines an angle function on the complex plane, which is used in all our "geometry on CC" theorems). I seems that the general tactic was to avoid new symbols in the main part unless they really do simplify proofs/exposition/etc - so it would be nice to know what is the governing rule in this case.

**Comment by nmegill** [comment]
@savask - I think the discussion was mainly about using "pfx" as an abbreviation in labels, such as "pfxval", but keeping the math token as "prefix".  This would be similar to our use of "rn" for range in labels like "rnxp", but using "ran" as the math token.  Using the full word "prefix" in labels would make some of them rather long, and "pfx" seems a little less ambiguous to me than "pref".

The argument positions in "( W prefix L )" are based on our syntax for operation values.  It avoids introducing a new compound syntax and lets us use our library of operation value theorems.   If "prefix" were a predicate, "W is a prefix of L" would be expressed with the binary relation syntax "W prefix L" without parentheses.

**Comment by savask** [comment]
@nmegill I see, thank you for clarification. I completely missed the parenthesized/non-parenthesized distinction.

**Comment by david-a-wheeler** [comment]
@avekens - I think the key is that if you use "prefix" in ASCII, but "pfx" as the label fragment, you should note in the comment for its definition. Also, if you use "pfx" as the label fragment, its definition should be named "df-pfx"; in general, the label fragment is whatever is after "df-".

**Comment by avekens** [comment]
Since there were no objections against moving this definition and the related theorems to main, I would like to do that, so that this issue can be closed afterwards. The concerns of @savask are clarified by Norm, I think, and the naming was already adapted in my mathbox with PR #1651according to the discussions. Therefore, I see no reason to postpone this task further.

**Comment by avekens** [comment]
With PR #2890, the main work will be done. The obsolete theorems have due date 12-Oct-2022, so that they can be deleted all at the same time. The following OLD theorems, however, have to be replaced (they also will have due date 12-Oct-2022) - I will do this in the next days (if/after the PR is accepted and merged):

"2swrd1eqwrdeqOLD" is used by "clwwlkf1".
"2swrd1eqwrdeqOLD" is used by "wwlksnextinj".
"2swrd2eqwrdeqOLD" is used by "numclwwlk1lem2f1".
"disjxwrdOLD" is used by "disjxwwlkn".
"disjxwrdOLD" is used by "disjxwwlksn".
"reuccats1OLD" is used by "numclwlk2lem2f1o".
"swrd0fv0OLD" is used by "2clwwlklem".
"swrd0fv0OLD" is used by "clwwlkf".
"swrd0fv0OLD" is used by "clwwlkinwwlk".
"swrd0fv0OLD" is used by "clwwlknonclwlknonf1o".
"swrd0fv0OLD" is used by "clwwlkvbij".
"swrd0fv0OLD" is used by "numclwlk2lem2f".
"swrd0fv0OLD" is used by "wwlksnextproplem1".
"swrd0fv0OLD" is used by "wwlksnredwwlkn0".
"swrd0fvOLD" is used by "clwwlkf".
"swrd0fvOLD" is used by "clwwlkinwwlk".
"swrd0fvOLD" is used by "dlwwlknonclwlknonf1olem1".
"swrd0fvOLD" is used by "wwlksm1edg".
"swrd0fvOLD" is used by "wwlksnred".
"swrd0fvOLD" is used by "wwlksubclwwlk".
"swrd0fvlswOLD" is used by "clwwlkf".
"swrd0fvlswOLD" is used by "clwwlkinwwlk".
"swrd0fvlswOLD" is used by "numclwlk2lem2f".
"swrd0fvlswOLD" is used by "wwlksnextproplem2".
"swrd0fvlswOLD" is used by "wwlksnredwwlkn".
"swrd0len0OLD" is used by "wwlksnred".
"swrd0lenOLD" is used by "clwlkclwwlk".
"swrd0lenOLD" is used by "clwlknf1oclwwlknlem1".
"swrd0lenOLD" is used by "clwwlkf".
"swrd0lenOLD" is used by "clwwlkinwwlk".
"swrd0lenOLD" is used by "efgredlem".
"swrd0lenOLD" is used by "efgsres".
"swrd0lenOLD" is used by "signstfveq0".
"swrd0lenOLD" is used by "wlkreslem0".
"swrd0lenOLD" is used by "wwlksm1edg".
"swrd0lenOLD" is used by "wwlksnextproplem3".
"swrd0lenOLD" is used by "wwlksnred".
"swrd0lenOLD" is used by "wwlksubclwwlk".
"swrd0valOLD" is used by "efgredlem".
"swrd0valOLD" is used by "efgsres".
"swrd0valOLD" is used by "signsvtn0".
"swrd0valOLD" is used by "wlkreslem0".
"swrd0valOLD" is used by "wrdsplex".
"swrd0valOLD" is used by "wwlksm1edg".
"swrdccat1OLD" is used by "clwwlkfo".
"swrdccat1OLD" is used by "wwlksnextbi".
"swrdccat1OLD" is used by "wwlksnextsur".
"swrdccatidOLD" is used by "clwlkclwwlk2".
"swrdccatidOLD" is used by "clwlkclwwlkfo".
"swrdccatidOLD" is used by "numclwwlk1lem2fo".
"swrdccatidOLD" is used by "numclwwlk1lem2foalem".
"swrdccatwrdOLD" is used by "signstfveq0".
"swrdccatwrdOLD" is used by "signsvtn0".
"swrdccatwrdOLD" is used by "wwlksnextwrd".
"swrdeqOLD" is used by "clwlkclwwlkf1lem2".
"swrdidOLD" is used by "wrdsplex".
"swrdn0OLD" is used by "clwlkclwwlk".
"swrdn0OLD" is used by "clwwlkinwwlk".
"swrdn0OLD" is used by "wwlksnred".
"swrdtrcfv0OLD" is used by "clwlkclwwlk".
"swrdtrcfvOLD" is used by "clwlkclwwlk".
"swrdtrcfvlOLD" is used by "clwlkclwwlk".
"wrdcctswrdOLD" is used by "2clwwlk2clwwlk".

**Comment by avekens** [comment]
With PR #2926, this issue is done in principle. All obsolete theorems have due date 12-Oct-2022, so that they can be deleted all at the same time. Afterwards, this issue can be closed (it should remain open as a reminder for me to delete the OLD theorems in October 2023).

**Comment by benjub** [comment]
Thanks @avekens.  I'll then close this issue this weekend if it is not closed already. Indeed, the "`Obsolete as of 12-Oct-2022. `" comments are sufficient for anyone to remove the OLD theorems as of 12-Oct-202**3**. Cluttering the "Issues" list for one year with what is only "a reminder for you", as you write (or for any specific person, of course), is not good policy in my opinion.
