### ISSUE TITLE
"_" in labels not allowed

### ISSUE THREAD

**Issue by avekens** [metamath/set.mm#1693]
As discussed in PR #1691, the underscore "_" should not be allowed in labels. The few theorems with labels containing " _ " are already adapted accordingly (see PR #1692). In PR #1691, @nmegill proposed to enhance 'verify markup' to check for " _ " used in labels:

> This could be enforced with a 'verify markup' warning. Should we go that far? Maybe we should if it prevents label collisions in MM0.

**Comment by avekens** [comment]
I would support Norm's proposal to enhance 'verify markup' to check for " _ " used in labels. The travis checks for set.mm should reject any pull request which violates the rule.

**Comment by nmegill** [comment]
> I would support Norm's proposal to enhance 'verify markup' to check for " _ " used in labels. The travis checks for set.mm should reject any pull request which violates the rule.

OK I will do that.   I'll also add a /UNDERSCORE_SKIP qualifier (consistent with the other /xxx_SKIPs) to allow this check to be selectively bypassed for those who don't want to check for it.

@jkingdon iset.mm has an underscore in the label ~ r19.29_2a, which will change to r19.29vva in set.mm.  Could you update it?  Thanks.

**Comment by jkingdon** [comment]
Submitted as https://github.com/metamath/set.mm/pull/1694

**Comment by avekens** [comment]
There was a discussion in the Google group about underscores in labels: https://groups.google.com/d/topic/metamath/W9U3QNE4TSU/discussion
Here, it was decided not to use underscores (not in general, but for the discussed issue). Therefore, our decision not to use underscores in general is completely in line with the result of this discussion.

**Comment by avekens** [comment]
@nmegill  is 'verify markup' enhanced to check for " _ " used in labels already in the latest version 0.184 of the metamath program?

**Comment by nmegill** [comment]
> @nmegill is 'verify markup' enhanced to check for " _ " used in labels already in the latest version 0.184 of the metamath program?

Yes.
