### ISSUE TITLE
Where is weakening rule?

### ISSUE THREAD

**Issue by light42** [metamath/set.mm#1703]
Hi, I'm curious why there isn't any [weakening rule](https://en.wikipedia.org/wiki/Monotonicity_of_entailment) in [metamath's natural deduction rules](http://us.metamath.org/mpeuni/natded.html) . [QED game](https://teorth.github.io/QED/) heavily relied on this rule(the concept is introduced on section 4.1), and eventhough I can use it properly, I'm really curious what sort of axioms underlying this rule.

**Comment by digama0** [comment]
That's a fair point. The list is only illustrative, although it tries to be comprehensive of rules in the literature. The rule that looks most closely like weakening is [adantr](http://us.metamath.org/mpeuni/adantr.html), but it is only one of a large set of weakening rules, depending on how you want to reduce the context. [adantl](http://us.metamath.org/mpeuni/adantl.html) drops the left part of the context, and you can pop the last N elements of the context using [ad2antrr](http://us.metamath.org/mpeuni/ad2antrr.html), [ad3antrrr](http://us.metamath.org/mpeuni/ad3antrrr.html), [ad4antr](http://us.metamath.org/mpeuni/ad4antr.html), [ad5antr](http://us.metamath.org/mpeuni/ad5antr.html), ..., [ad10antr](http://us.metamath.org/mpeuni/ad10antr.html). There are many other theorems in the ad*ant* series that involve dropping conjuncts on the left side of the implication in different arrangements, which all equate to some kind of weakening rule in natural deduction.

**Comment by light42** [comment]
Thank you, adantr and adantl is good enough for me, the rest of it could be constructed from those two anyway.

**Comment by david-a-wheeler** [comment]
Should we mention that in [natded](http://us.metamath.org/mpeuni/natded.html)? We already list adantr and adantl, but we never mention the term "weakening rule".
