### ISSUE TITLE
shallow update not allowed

### ISSUE THREAD

**Issue by benjub** [metamath/set.mm#1754]
I just set up git, following exactly the instructions of Step 4 of https://github.com/metamath/set.mm/wiki/Getting-started-with-contributing
Then, I did
```
$ git pull upstream develop
```
which worked correctly, but then
```
MBP-de-benoit:set.mm benoit$ git push origin develop
Total 0 (delta 0), reused 0 (delta 0)
To https://github.com/benjub/set.mm.git
 ! [remote rejected] develop -> develop (shallow update not allowed)
error: failed to push some refs to 'https://github.com/benjub/set.mm.git'
```
Does someone know what is going on and how to fix this ?

Here is some information:
```
MBP-de-benoit:set.mm benoit$ git branch -v
* develop d908ac0 [ahead 4509] Merge pull request #1753 from ml-2/ml
MBP-de-benoit:set.mm benoit$ git remote -v
origin	https://github.com/benjub/set.mm.git (fetch)
origin	https://github.com/benjub/set.mm.git (push)
upstream	https://github.com/metamath/set.mm.git (fetch)
upstream	https://github.com/metamath/set.mm.git (push)
MBP-de-benoit:set.mm benoit$ git status -v
On branch develop
Your branch is ahead of 'origin/develop' by 4509 commits.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean
```

**Comment by nmegill** [comment]
I've seen this before when I was low on disk space and used "--depth 5", and a fix from stackexchange that worked for me once was
```
            git fetch --unshallow    (takes 1/2 hour)
            git push --set-upstream origin   (then worked ok)
```
But another time I tried to fix it this way it didn't work (can't remember the error message), so I nuked the GitHub directory and started from scratch.  My final solution was to buy a bigger disk for my system and omit the "--depth 5".

**Comment by david-a-wheeler** [comment]
A shallow copy works well *if* everything you do is covered by the portion done by the shallow copy... but otherwise it doesn't work at all.

**Comment by benjub** [comment]
Thanks @nmegill, it worked.
