### ISSUE TITLE
Definition for infimum

### ISSUE THREAD

**Issue by avekens** [metamath/set.mm#1805]
Currently, there is only a definition for the supremum in set.mm. The infimum is "simulated" by using the "reversed supremum" sup ( * , * , ``` ' R ) , which is often hard to understand at the first glance. As discussed in the Google group and supported by Norm, see https://groups.google.com/g/metamath/c/p5XIt_HdDik/m/pg84xtI2AAAJ, I want to provide a separate definition and related theorems (mainly the dual forms of the corresponding theorems for supremum) for the infimum (of a subset of a totally ordered set). Afterwards, definitions/theorems using the pattern sup ( * , * , ` ` ` ' R ) should be revised using the new definition.

(Remark: unfortunately, the symbol for the converse, see ~df-cnv, is not (always) displayed properly by GitHub...)

**Comment by avekens** [comment]
With PR #1806, I provide a separate definition and related theorems (mainly the dual forms of the corresponding theorems for supremum) for the infimum (of a subset of a totally ordered set) in my Mathbox. In addition, I also revised some theorems using the pattern sup ( * , * , ` ' R ) using the new definition. These are currently separate versions of the current theorems, marked by the suffix ALTV.

If there are no objections, I will move the separate definition and related theorems for the infimum to main set.mm, and will replace the current theorems using the pattern sup ( * , * , ` ' R ) by the version using the new definition, removing the suffix ALTV. The former versions of these theorems will be kept as OLD theorems.

By the way, I used the symbol "inf", and also "inf" as abbreviation in labels, It seems, however, that also "infm" was used until now. I think using "inf" is more consistent with the conventions used for the supremum ("sup" and not "supr" or "supm"), Therefore, I would propose to use "inf" consequently in the future.

**Comment by avekens** [comment]
With PR #1806, I provide a separate definition and related theorems (mainly the dual forms of the corresponding theorems for supremum) for the infimum (of a subset of a totally ordered set) in my Mathbox. In addition, I also revised some theorems using the pattern sup ( * , * , ` ' R ) using the new definition. These are currently separate versions of the current theorems, marked by the suffix ALTV.

If there are no objections, I will move the separate definition and related theorems for the infimum to main set.mm, and will replace the current theorems using the pattern sup ( * , * , ` ' R ) by the version using the new definition, removing the suffix ALTV. The former versions of these theorems will be kept as OLD theorems.

By the way, I used the symbol "inf", and also "inf" as abbreviation in labels, It seems, however, that also "infm" was used until now. I think using "inf" is more consistent with the conventions used for the supremum ("sup" and not "supr" or "supm"), Therefore, I would propose to use "inf" consequently in the future.

**Comment by avekens** [comment]
Since there were no objections, I started to revise set.mm regarding a new, separate definition for the infimum of ordered sets, see PR #1809 . There are 12(!) definitions which use the pattern sup ( * , * , ` ' R ), and which should be revised using the new definition:
* df-limsup
* df-pi
* df-lcm
* df-lcmf
* df-odz
* df-ram
* df-imas
* df-odz
* df-gex
* df-nmo
* df-ovol
* df-ig1p

I've done the revision of df-limsup already (see PR #1809), keeping all the theorems using the old definition as OLD version. These were already quite a lot of theorems, and I think I will not do it for the other definitions. I will only keep the theorems using the definition df-* directly as OLD version. 

I will continue with the next five definitions
* df-pi
* df-lcm
* df-lcmf
* df-odz
* df-ram

In addition, there are more than 100 theorems using OLD theorems which have to be revised.
Altogether, this will still be a lot of work to do (it will take some weeks I guess).

@tirix @glacode : your mathboxes are also affected - I made some changes already by PR #1809. I hope you don't bother if I perform the required revisions in your mathboxes also in the future.

**Comment by glacode** [comment]
Thanks for the advice, I have many local theorems relying on the pattern sup ( * , * , ` ' R ).

I hope it will not be too hard to switch to the new definition :-)

(it may be I'll anticipate a PR, not to diverge too much to the new definition for infimum)

I guess infm was used in labels, instead of inf, to avoid "collision" with the word "infinite"

Glauco

**Comment by avekens** [comment]
Status after PR #1837:
The following definitions (and related theorems) are revised already:

* df-limsup
* df-pi
* df-lcm
* df-lcmf
* df-ram
* df-odz
* df-gex
* df-nmo
* df-ovol
* df-ig1p
* df-pellfund
* df-dgraa (in Mathbox of @sorear )
* df-tau (in Mathbox of @jkingdon )

With PR #1837, many other theorems are revised, including theorems in Mathboxes of @glacode , @tirix and BL.

The following definitions (and related theorems) still need to be revised (there are many dependencies, so this will take some time):
* df-od
* df-imas

Additionally, there are about 20 theorems using OLD theorems in their proofs to be revised.

**Comment by tirix** [comment]
Infimum is quite ubiquitous: in addition to those you list, I believe the following theorems in my mathbox still could/should be converted:
* xrge0infssd
* infxrge0lb
* infxrge0glb
* infxrge0gelb

As well as these:
* df-oms
* omsval
* omsfval

And maybe this one too:
* ballotlemi

**Comment by avekens** [comment]
With PR #1839, most of the revisions is done (including the changes in TA's mathbox, as proposed by @tirix). Still open are:
*  df-od and related theorems
* df-imas and related theorems 
* ballotlemi (TA's Mathbox) - It's not only this one, also the following theorems depend on ballotth.i $e \|- I = ( c e. ( O \ E )   \|-> sup ( { k e. ( 1 ... ( M + N ) ) \| ( ( F ` c ) ` k ) = 0 } , RR , `'   < ) ) $.

**Comment by avekens** [comment]
With PR #1839, most of the revisions is done (including the changes in TA's mathbox, as proposed by @tirix). Still open are:
*  df-od and related theorems
* df-imas and related theorems 
* ballotlemi (TA's Mathbox) - It's not only this one, also the following theorems depend on ballotth.i $e \|- I = ( c e. ( O \ E )   \|-> sup ( { k e. ( 1 ... ( M + N ) ) \| ( ( F ` c ) ` k ) = 0 } , RR , `'   < ) ) $.

**Comment by avekens** [comment]
With PR #1842, I have finished the revisions according to infimum (including the changes in TA's mathbox, as proposed by TA). 
I kept most of the affected definitions/theorems as OLD version (there are quite a lot of them), which I will remove, according to our conventions, in about a year (in October/November 2021). After this, I will check if I missed some Patterns sup ( * , * , `' * ) which might be still existing.

Concerning OLD versions in mathboxes: I think these could/should be removed as soon as possible by the mathbox owner (@tirix  especially the  37 ballot*OLD theorems). This should be finished in September 2021 latest, to reduce the effort for cleaning up the main body of set.mm afterwards.

**Comment by avekens** [comment]
With PR #2239, this issue is done. There are no theorems using the idiom sup ( * , * , ` ' R ) for the infimum anymore. There are, however, still some OLD theorems in mathboxes, but these can be deleted by the mathbox owners or during a regular cleanup in about a year.
