### ISSUE TITLE
Prove convergence of Cauchy sequences of positive reals in iset.mm

### ISSUE THREAD

**Issue by jkingdon** [metamath/set.mm#1810]
Right now iset.mm has http://us.metamath.org/ileuni/cauappcvgpr.html which says that a Cauchy approximation with values in `Q.` has a limit in `P.`.

The extension to a Cauchy sequence (which is indexed by a natural number, rather than by a rational number indicating the desired closeness of terms) should be straightforward. Here is my current statement of what we are trying to prove:

```
  ${
    $d A j $.
    caucvgpr.f $e |- ( ph -> F : _om --> Q. ) $.
    caucvgpr.cau $e |- ( ph ->
      A. x e. Q. E. j e. _om A. k e. _om ( j <Q k ->
      ( ( F ` j ) <Q ( ( F ` k ) +Q x ) /\
        ( F ` k ) <Q ( ( F ` j ) +Q x ) ) ) ) $.
    caucvgpr.bnd $e |- ( ph -> A. j e. _om A <Q ( F ` j ) ) $.
    $( A Cauchy sequence of postiive fractions converges to a positive real.
       This is basically Corollary 11.2.13 of [HoTT], p.  (varies) (one key
       difference being that this is for positive reals rather than signed
       reals).  We also specify that every term needs to be larger than a
       fraction ` A ` , to avoid the case where we have positive fractions
       which converge to zero (which is not a positive real).  (Contributed by
       Jim Kingdon, 18-Jun-2020.) $)
    caucvgpr $p |- ( ph ->
        E. y e. P. A. x e. Q. E. j e. _om A. k e. _om ( j <Q k ->
        ( <. { l | l <Q ( F ` k ) } , { u | ( F ` k ) <Q u } >.
            <P ( y +P. <. { l | l <Q x } , { u | x <Q u } >. ) /\
          y <P <. { l | l <Q ( ( F ` k ) +Q x ) } ,
            { u | ( ( F ` k ) +Q x ) <Q u } >. ) ) ) $=
      (  ) ? $.
  $}
```

Using the proof of Corollary 11.2.13 of [HoTT] as our guide, there are several steps to proving this:

* define the modulus of convergence based on the hypothesis stating that the sequence is Cauchy. There seem to be a few ways to define a modulus of convergence. All of them take a rational number for the desired tolerance and return a natural number which is an index into the sequence. Some definitions then say that any two indexes greater than that natural number yield values which are close together. For example, "function M : Q + → N, called the modulus of convergence, such that m, k ≥ M ( e ) implies | x<sub>m</sub> − x<sub>k</sub> | < e" (HoTT section 11.2.2). Other definitions compare the value of the sequence at any index beyond the value of the modulus of convergence with the value of the sequence at the value of the modulus of convergence (using the notation of this HoTT sentence, it would look something like "m > M ( e) implies | x<sub>m</sub> - x<sub>M ( e )</sub> | < e". As far as I can tell these two definitions work out the same way, but differ by a factor of two (because with the latter definition we could have one index which is larger then x<sub>m</sub> by almost `e` and another index which is smaller than x<sub>m</sub> by almost `e`.

* One detail in defining the modulus of convergence is how to express "x and y are with e of each other" but my assumption is we'll do this the same way that http://us.metamath.org/ileuni/cauappcvgpr.html does (which does not require subtraction, absolute value, negative numbers, etc).

* Going from the Cauchy hypothesis to a function for the modulus of convergence involves using `A. x e. B E. j e. C` to define a function from B to C. I'm not sure whether this is just a straightforward operation which we already have a theorem and/or most convenient notation for (which I just need to find) or whether it is a morass of existence versus existential uniqueness, ax-coll, axiom of choice, excluded middle, etc.

* Once we have the modulus of convergence we should be able to use it to show (again quoting from HoTT and using their notation, "From this we get | x<sub>M ( δ/2 )</sub> − x<sub>M ( e/2 )</sub> | < δ + e for all δ, e : Q +"). This should be the hypothesis of http://us.metamath.org/ileuni/cauappcvgpr.html

* Then we need to show the limit from cauappcvgpr is the limit we want for caucvgpr . I think this part is straightforward although I haven't tried to sketch it out in any detail.

If anyone does any work on this, please keep this issue updated so we can benefit from each other's progress. Likewise, if I have any partial results I expect to push them to the https://github.com/jkingdon/set.mm/tree/iset-causeq branch (right now this branch just has the unproved caucvgpr as quoted above).

**Comment by jkingdon** [comment]
I'm beginning to wonder whether we need a different definition of Cauchy sequence than the one above. The definition of Cauchy sequence (and modulus of convergence) given both in http://paultaylor.eu/ASD/lamcra/lamcra.pdf (Definition 6.12) and in https://en.wikipedia.org/wiki/Cauchy_sequence ("regular Cauchy sequence" in the latter) includes a restriction about how quickly the terms approach each other. Although the definition from HoTT doesn't, on the face of it, I think that may just be because I'm not correctly translating the type theory (in fact, HoTT does have an explicit assertion that the lack of propositional truncation in their definition of Cauchy sequence means that the rate of convergence matters, and the definition of Cauchy sequence in the description of this github issue does not translate that concept). Another quote from the wikipedia page which (combined with reading some of the set.mm proofs) would seem to imply that we can't prove existence of a limit for any Cauchy sequence defined using a definition similar to http://us.metamath.org/mpeuni/caucvg.html : "The existence of a modulus for a Cauchy sequence follows from the well-ordering property of the natural numbers" (iset.mm doesn't have this property - see http://us.metamath.org/ileuni/nnregexmid.html ).

Now using a stricter definition presumably is possible. In the words of the Taylor paper cited above "Commonly occurring sequences such as the sums of power series do not march obediently towards their limits at the exponential pace that we have ordered.  But analysts who regularly deal with series are skilled  in  re-bracketing  and  re-arranging  them". Not that this quote is entirely reassuring, it makes it sound like many of the sequence convergence results from set.mm will need re-working, not just in terms of the formalism but even in terms of which sequence we prove convergence for (to be concrete about it, I'm thinking about things like http://us.metamath.org/mpeuni/df-ef.html or a sequence which might be used to define the square root of a nonnegative real if we end up going with a sequence).

If there is something I'm misunderstand or overcomplicating, please do speak up. Although there are some references on this topic on the internet, many of them address a slightly different question than what we need to state and prove (some sort of) completeness of the (Dedekind) reals as defined in iset.mm.

**Comment by digama0** [comment]
There is indeed an intuitionistic difference between cauchy sequences with vs without a modulus of convergence (it is the difference between `A. e E. N A. i |x_i - x_N| < e` and `E. M A. e A. i |x_i - x_{M(e)}| < e`), but all explicit moduli are equivalent (e.g. you can require that the sequence converge as 1/n or 2^-n and they are equivalent). Theorems like df-ef will have to be strengthened to provide the explicit modulus, but it is possible to do so for all functions that come up in general analysis.

**Comment by digama0** [comment]
The version in the HoTT book actually includes an explicit modulus of convergence. This is what is meant by the text:

> Note that we did not truncate the inner existential because we actually want to compute rates of convergence—an approximation without an error estimate carries little useful information.  By Theorem 2.15.7, (11.2.9) yields a function M:Q+→N, called the modulus of convergence, such that m,k≥M(e) implies |xm−xk|<e.

The way this is achieved in type theory is using an unsquashed sigma to represent the E. n part, which makes the entire witness a function from e:Q+ to a pair of n:N and a proof that everything above n is e-close to the initial point.

**Comment by digama0** [comment]
While the HoTT book formulation associates extra data to a cauchy sequence (each sequence is paired with a particular modulus), which is not necessary if you fix a rate up front like 2^-n, it is probably easier to intuitionize arbitrary classical proofs of convergence into the HoTT book form because it doesn't require that you reindex the sequence to match the global convergence rate. My suggestion would be to use a fixed rate of convergence like 1/n, and then define functions allowing you to construct a real from a sequence with any modulus of convergence, so that you get the same flexibility as the HoTT form.

**Comment by jkingdon** [comment]
Thanks, @digama0 . That pretty much (a) confirms what I was thinking in my comment above, and (b) reminds me why I've been putting off dealing with completeness :grin: . And yes, the HoTT text starting "Note that we did not truncate the inner existential...." is what I was focused on too. It makes sense now that you say that it is the witness itself which expresses the rate of convergence, and that to apply the theorem you need such a witness.

Sounds like we'll need to regroup with something similar to `caucvgpr` as stated above with a modulus of convergence hypothesis added. I like the idea of using 1/n (or whatever fixed rate we pick) and then being able to prove others in terms of that one.

**Comment by jkingdon** [comment]
Here's my statement of a revised `caucvgpr.cau` hypothesis which is intended to express the "fixed rate of convergence of 1/n" plan described above (as before you can see this in context at the https://github.com/jkingdon/set.mm/tree/iset-causeq branch):

```
    caucvgpr.cau $e |- ( ph ->
      A. n e. N. A. k e. N. ( n <Q k ->
      ( ( F ` n ) <Q ( ( F ` k ) +Q ( *Q ` [ <. n , 1o >. ] ~Q ) ) /\
        ( F ` k ) <Q ( ( F ` n ) +Q ( *Q ` [ <. n , 1o >. ] ~Q ) ) ) ) ) $.
```

**Comment by Nikolaj-K** [comment]
Should you not know about those resources, there's [in this paper](https://arxiv.org/pdf/1510.00639.pdf) and some discussion [on the nLab](https://ncatlab.org/nlab/show/Cauchy+real+number). There's also a man named [Booij](https://arxiv.org/search/cs?searchtype=author&query=Booij%2C+A+B) who has worked on analysis in HoTT. I linked to his arxiv but he also has a 200 page PhD thesis from this year online (can't find it right now) and also analysis contribution of him [here](https://github.com/abooij/HoTT/tree/locators). I don't know if I can ping people on github but excuse my rudeness and let me just try @abooij.

**Comment by jkingdon** [comment]
> Should you not know about those resources, there's [in this paper](https://arxiv.org/pdf/1510.00639.pdf) some discussion and [on the nLab](https://ncatlab.org/nlab/show/Cauchy+real+number). There's also a man named [Booij](https://arxiv.org/search/cs?searchtype=author&query=Booij%2C+A+B) who has worked on analysis in HoTT. I linked to his arxiv but he also has a 200 page PhD thesis from this year online (can't find it right now) and also analysis contribution of him [here](https://github.com/abooij/HoTT/tree/locators). I don't know if I can ping people on github but excuse me rudeness and let me just try @abooij.

Thanks for the suggestions!

In case it isn't clear, this issue isn't about actual type theory (homotypical or otherwise).  iset.mm is based on the constructive set theory IZF (with CZF in one of the mathboxes, but we can say IZF for current purposes). The only reason we are citing the HoTT Book at all (the cited parts of chapter 11 anyway) is as an up to date "textbook" for those parts of constructive mathematics which apply both to type theory and set theory.

Hopefully the above discussion about using a fixed rate of convergence of `1 / n ` solves some of our deeper mathematical problems. If so the next step is a bunch of details about how we connect sequences to http://us.metamath.org/ileuni/cauappcvgpr.html (and/or modified versions thereof, if that would be more helpful). My work to date, including stating a few lemmas I think might help break down the problem, is at the https://github.com/jkingdon/set.mm/tree/iset-causeq branch. If anyone has any suggestions or metamath proofs to contribute, I'm totally open to that.

**Comment by abooij** [comment]
> I don't know if I can ping people on github but excuse me rudeness and let me just try @abooij.

Yes, you can ping people on github!

My [thesis work](https://abooij.blogspot.com/p/phd-thesis.html) is about analysis in HoTT, but I did my best to write it in a neutral style that does not bind the work too strongly to type theory. Cauchy sequences, and Cauchy completeness, are discussed in Section 4.4. I believe a large amount of the ideas can be translated to constructive set theories such as IZF, but I have not attempted this myself. I'd be delighted to discuss specific questions.

**Comment by jkingdon** [comment]
The update is that I am trying to state caucvgpr as described earlier in this issue, and prove in a way similar to the proof of http://us.metamath.org/ileuni/cauappcvgpr.html (but without using the result of `cauappcvgpr` itself - I don't know whether that is possible but I couldn't see how to make it work).

So far I have defined what I plan to be the limit, and shown it is inhabited. So the remaining pieces are that it is rounded, disjoint, and located, and that it really is the limit. As before my work in progress is at https://github.com/jkingdon/set.mm/tree/iset-causeq .

**Comment by jkingdon** [comment]
Status report. I am well on my way to proving the following:

```
MM> show statement caucvgpr
$d A j $.  $d j F k n l u x y $.  $d ph j k x $.
24413 caucvgpr.f $e |- ( ph -> F : N. --> Q. ) $.
24414 caucvgpr.cau $e |- ( ph -> A. n e. N. A. k e. N. ( n <N k -> ( ( F ` n )
      <Q ( ( F ` k ) +Q ( *Q ` [ <. n , 1o >. ] ~Q ) ) /\ ( F ` k ) <Q ( ( F `
      n ) +Q ( *Q ` [ <. n , 1o >. ] ~Q ) ) ) ) ) $.
24427 caucvgpr.bnd $e |- ( ph -> A. j e. N. A <Q ( F ` j ) ) $.
24522 caucvgpr $p |- ( ph -> E. y e. P. A. x e. Q. E. j e. N. A. k e. N. ( j <N
      k -> ( <. { l | l <Q ( F ` k ) } , { u | ( F ` k ) <Q u } >. <P ( y +P.
      <. { l | l <Q x } , { u | x <Q u } >. ) /\ y <P <. { l | l <Q ( ( F ` k )
      +Q x ) } , { u | ( ( F ` k ) +Q x ) <Q u } >. ) ) ) $= ... $.
```

Somewhat more than half of the lemmas needed are proven, and it would appear this is going to work. Work so far is at https://github.com/jkingdon/set.mm/tree/iset-causeq
