### ISSUE TITLE
Github Issue/Pull Request Bot that automatically checks proofs

### ISSUE THREAD

**Issue by void4** [metamath/set.mm#1851]
set.mm contributions seem to require a fork of this repository, it seems that the current process of integrating new proofs is by creating pull requests with diffs to the main file. I've been thinking about creating a bot that checks whether

- (1) the submitted proof(s) are correct and
- (2) all the additional requirements/conventions set.mm requires are followed.

I'm not sure whether you have already done this, or if you would even like something like it.

With pull requests, it might look like this

![image](https://user-images.githubusercontent.com/11392207/96577965-bee55780-12d4-11eb-9f20-f0ff5cde4517.png)

or

![image](https://user-images.githubusercontent.com/11392207/96577909-aaa15a80-12d4-11eb-8247-18d6a7a9e9ae.png)

If new proofs were submitted via issues instead, because these don't support (merge-blocking) status checks, the bot could reply there with a message.

This kind of angles on (but is independent of) my thoughts on a proof bounty system. There is a crypto project called Gitcoin who have a system/bot that awards the successful solution of issues (though human-mediated).

Issues that have rewards attached look like this:

![image](https://user-images.githubusercontent.com/11392207/96579056-7dee4280-12d6-11eb-80cc-92a8bce87024.png)

Their issue explorer looks like this: https://gitcoin.co/explorer

I'll be experimenting on a bot here: https://github.com/void4/mmbot

**Comment by david-a-wheeler** [comment]
We currently do many checks by running Travis as configured via `.travis.yml`.

If this is an improvement that'd be great - what's the improvement?

The idea of running checks on multiple platforms simultaneously (so if one breaks things keep working) does have some appeal, though we have limited time to maintain things.

**Comment by void4** [comment]
I wasn't aware of that, thanks! I think it already covers much, so I'll close this issue for now :)
