### ISSUE TITLE
Proximity of "Bundled" and "Bounded"

### ISSUE THREAD

**Issue by jkingdon** [metamath/set.mm#1863]
From Gérard Lang:

> There is a rather great proximity between the english words « bundled » and « bounded », so that the current name for the axiom of Bundling in iset.mm is « ax-bnd », when Benoît Jubin’s Mathbox uses many times axioms regarding bounded notiions, whose notation is « ax-bd0,…,ax-bdsb » (in the section 5.3.4), « ax-bdsep » (in the section 5.3.6) or even « ax-bdsetind » (in the section 5.3.8.1).
> In my personal opinion, this could be a source of confusion, so that I suggest that the  notation concerning the axiom of Bundling could be changed from « ax-bnd » to ‘« ax-bndl ».

**Comment by benjub** [comment]
Gérard's proposal (ax-bndl) sounds good to me. It will also distinguish it from the axiom of boundedness (a variant of Collection), since the latter has no "L".

**Comment by jkingdon** [comment]
> Gérard's proposal (ax-bndl) sounds good to me. It will also distinguish it from the axiom of boundedness (a variant of Collection), since the latter has no "L".

I have no objection.

**Comment by david-a-wheeler** [comment]
I like it, making names less confusing is a good thing.

**Comment by benjub** [comment]
Done (see #1864), so the issue can be closed (I do not know how to close it).

**Comment by david-a-wheeler** [comment]
Resolved with #1864.
