### ISSUE TITLE
analog - analogue - analogon

### ISSUE THREAD

**Issue by avekens** [metamath/set.mm#1908]
Currently, there are two spellings of the noun "analog" in set.mm:
* analog (AE): 62 times
* analogue (BE): 42 times
* analogon (AE/BE): 0 times

Since we have the convention that American English (AE) should be used (see section 17.1.1  Conventions in set.mm), the 42 occurences of "analogue" should be replaced by "analog".

Alternatively, all occurences could be replaced by "analogon" (from ancient Greek ἀνάλογον), which I would prefer, but which may be a little bit old-fashioned...

**Comment by benjub** [comment]
I'm all for spelling consistency throughout set.mm and I'm ok with the American English convention.  The problem with "analog", though, is that it can be either a noun or an adjective, whereas "analogue" is a noun and "analogous" is an adjective, so maybe the latter two could be preferred ?

See https://www.merriam-webster.com/dictionary/analogue , especially the paragraph "Did you know?".

**Comment by digama0** [comment]
I often use "analogue" instead of "analog" (even though I generally speak AmE) because the latter has also the confounding meaning "not digital". [Random internet person](https://oilpatchwriting.wordpress.com/2013/01/16/analog-vs-analogue/) agrees:

> “With the word traditionally spelled analogue, American writers tend to drop the silent –ue in some contexts, making analog. The spellings are largely interchangeable, though analog is usually used in relation to electronics, while analogue is often used in the sense something that bears analogy to something else. Outside the U.S., analogue prevails for all senses of the word.

**Comment by benjub** [comment]
So we agree to "analogue" for the noun and "analogous" for the adjective ?

Remark: I had a similar dilemma some time ago with alternate/alternative, since their meanings, in some cases, overlap.  I chose to prefer the shorter "alternate" each time that it is possible (https://www.merriam-webster.com/dictionary/alternate). In particular, most comments of ~xxxALT should begin with "Alternate proof of ~ xxx ."

**Comment by avekens** [comment]
For me, "analogue" for the noun and "analogous" for the adjective would be fine. 
@nmegill what's your opinion?

**Comment by nmegill** [comment]
> For me, "analogue" for the noun and "analogous" for the adjective would be fine.
> @nmegill what's your opinion?

I agree.

**Comment by avekens** [comment]
Done with PR #1914 : "analog" replaced by "analogue" resp. "analogous"
