### ISSUE TITLE
What is the best on-ramp for the semi-mathematical reader?

### ISSUE THREAD

**Issue by jkingdon** [metamath/set.mm#1941]
I got a reaction from someone on a software slack when I briefly explained metamath: "I've got to admit that this sounds fascinating.  I always loved mathematical proofs in school.  But my math skills are really rusty and actually trying to understand it sounds intimidating."

I realize that not everyone who expresses such a sentiment is likely to learn metamath, but where would we point them if they did? My response was:

> Well, there is something of a learning curve. At least for me, metamath was a nice way to dabble (for many years before I really learned it as such), partly because it has good web views. One way is to start with http://us2.metamath.org/mpeuni/ax-mp.html and keep clicking "next" to see what can be proved with only a few logical axioms. Another way in is to start with something familiar, like 2+2=4 http://us2.metamath.org/mpeuni/mmset.html#trivia . The nice thing about metamath is that every step is shown - you don't hit the "why does this follow from the previous steps?" problem which happens reading most mathematical proofs. The horrible thing about metamath is that every step is shown - so it is possible to get lost in details.

I think we have some intro material but I wasn't sure where.

I am a bit afraid to bring this up because I know it is a hard problem and if we solve it poorly we just give people *more* of an information dump to get lost in, but I guess I'm also not completely willing to give up on asking myself and the group: "what is the teaching order?" "do things like the web site help people dip their toes in the water?"

**Comment by benjub** [comment]
As you wrote, there is no such thing as **the** teaching order, and it depends much on the learner's background (and tastes). I would say that for the "semi-mathematical reader", the Metamath book (http://us.metamath.org/downloads/metamath.pdf) is the best way to start.

**Comment by jkingdon** [comment]
I'm going to close this as being answered by the Mini FAQ at http://us.metamath.org/ (especially the question "Where do I start?" which points to the metamath book. I mean, there's perhaps a bit of a quibble about exactly what should be most prominent on that page and whether this text is exactly optimally arranged, but on the whole I think the Mini FAQ does a good job of providing both starting points, and a bit of the motivations or ways of approaching it.
