### ISSUE TITLE
Update notnot naming in iset.mm to match recent changes to set.mm

### ISSUE THREAD

**Issue by jkingdon** [metamath/set.mm#2060]
1. Rename notnot1 to notnot
2. Add notnotr and notnotb to missing theorems list in mmil.html, replacing notnot2 and notnot. (note that notnotri and notnotrd are already there and don't need to change).
3. Copy notnotd from set.mm to iset.mm
3. Rename notnot2dc to notnotrdc and notnotdc to notnotbdc

Open question:
1. Should we rename `notnotnot` to `notnotnotb`? I think probably not, I guess mostly because it isn't found in set.mm and therefore there is no need to choose the same name for that reason.

Background: #1980

**Comment by benjub** [comment]
Thanks.  These modifications will add consistency.  I would add ( -. -. -. ph -> -. ph ) to iset.mm as ~notnotnotr, and then prove ~notnotnotb from it and ~notnot.
