### ISSUE TITLE
Restate Cauchy convergence in iset.mm to use normal notations

### ISSUE THREAD

**Issue by jkingdon** [metamath/set.mm#2103]
http://us2.metamath.org/ileuni/axcaucvg.html needs a theorem which builds on it but uses more convenient notations. Most of these are fairly obvious (` NN ` , ` 1 / n ` , ` < ` and ` RR+ `).

There's also a question of how to handle the construction (both in the Cauchy condition and the result) which boils down to "for all k in NN such that n < k". I see that http://us.metamath.org/mpeuni/caucvg.html expresses it as ``k e. ( ZZ>= ` j )`` which also includes the case k = j (which is trivially satisfied, but perhaps would be inconvenient to show when using the theorem?). I suppose another way would be ``k e. ( ZZ>= ` ( j + 1 ) )`` but I'm almost wondering if we're better off sticking with the `A. k e. NN ( n < k -> ....` formulation ( basically the way it is in http://us2.metamath.org/ileuni/axcaucvg.html ).

What I have at the moment is:

```
  ${
    caucvgre.f $e |- ( ph -> F : N --> RR ) $.
    caucvgre.cau $e |- ( ph ->
      A. n e. NN A. k e. ( ZZ>= ` n )
        ( ( F ` n ) < ( ( F ` k ) + ( 1 / n ) ) /\
        ( F ` k ) < ( ( F ` n ) + ( 1 / n ) ) ) ) $.
    $( Convergence of real sequences.

       A Cauchy sequence (as defined here, which has a rate convergence built
       in) of real numbers converges to a real number.  Specifically on rate of
       convergence, all terms after the nth term must be within ` 1 / n ` of
       the nth term.

       (Contributed by Jim Kingdon, 19-Jul-2021.) $)
    caucvgre $p |- ( ph ->
        E. y e. RR A. x e. RR+ E. j e. NN A. i e. ( ZZ>= ` j )
        ( ( F ` i ) < ( y + x ) /\ y < ( ( F ` i ) + x ) ) ) $=
      (  ) ? $.
  $}
```

Of course eventually we'll state a version in terms of absolute value, but we haven't yet developed absolute value and it presumably will need #2101 so the current plan is to tackle that later.

**Comment by digama0** [comment]
I recommend sticking with the ``( ZZ>= ` j )`` formulation. There are a number of theorems that work specifically on formulas of the form ``E. j e. Z A. i e. ( ZZ>= ` j ) ...`` which make many of the theorems simpler than you might think. The fact that it includes i = j isn't a problem because the smaller number is chosen to come from an upper integer set of your choosing, so you can always make it big enough for what is at hand.

**Comment by jkingdon** [comment]
> I recommend sticking with the `` ( ZZ>= ` j ) `` formulation. There are a number of theorems that work specifically on formulas of the form `` E. j e. Z A. i e. ( ZZ>= ` j ) ... `` which make many of the theorems simpler than you might think. The fact that it includes i = j isn't a problem because the smaller number is chosen to come from an upper integer set of your choosing, so you can always make it big enough for what is at hand.

Sounds good. I'm not 100% sure that all situations (e.g. hypothesis versus conclusion, `A.` versus `E.`) involve the same tradeoffs but I'll start with the ``( ZZ>= ` j )`` one as shown above and we can always change it, or add additional variations, if that ends up being inconvenient.
