### ISSUE TITLE
Sum formula for the Euler phi function

### ISSUE THREAD

**Issue by avekens** [metamath/set.mm#2138]
~phisum (A sum formula for the Euler ` phi ` function) is provided in section "Euler's theorem", but commented out. 
It is, however, already proven in SO's mathbox, see ~ phisum. I would like to move this theorem (and all theorems required to prove it) to main set.mm.  @sorear @nmegill @digama0 Would this be OK?

**Comment by digama0** [comment]
Sounds good to me.

**Comment by nmegill** [comment]
ok with me.

**Comment by avekens** [comment]
Done.
