### ISSUE TITLE
Add summation to iset.mm

### ISSUE THREAD

**Issue by jkingdon** [metamath/set.mm#2167]
The summation syntax - http://us.metamath.org/mpeuni/df-sum.html - in set.mm is kind of an amazing thing. It handles finite sets and infinite sequences which can be indexed not just in the obvious ways (NN, NN0, etc) but also "all even indexes" or other subsets of an upper integer set. Furthermore, it has two halves which can overlap (for example in integer ranges like `3...5`) but which agree where they overlap, making iota still work.

How does all this work in iset.mm?

* The `if(𝑛 ∈ 𝐴, ⦋𝑛 / 𝑘⦌𝐵, 0)` portion of the definition will only work well if `𝑛 ∈ 𝐴` is decidable. I expect various theorems will need a hypothesis like `( ( ph /\ x e. ZZ ) -> DECID x e. A`. Fortunately, this should be satisfied by a lot of the usual suspects like `NN` and other upper integer sets, integer ranges, and maybe others. But it would not be satisfied by pathological subsets of `(ℤ≥‘𝑚)` analogous to the ones in, for example, http://us.metamath.org/ileuni/onsucelsucexmidlem.html .
* A theorem like http://us.metamath.org/mpeuni/fsum.html should presumably not need a new hypothesis since it already has narrowed things down to a case that works (Update 10 Sep 2022: It does, however, need some changes for seq including defining `G` beyond `M`)
* The first disjunct in http://us.metamath.org/mpeuni/sumz.html is an example of the "need a DECID hypothesis" sort. In a nutshell, "summable set" would be expressed a different way whereever it occurs.
* ~~As far as I could tell, there is no need to change `df-sum` itself (beyond the obvious change of adding `CC` as an additional argument to `seq`)~~ (Update: https://us.metamath.org/ileuni/df-isum.html does have some modifications from when this issue was created but perhaps has everything it needs as of 10 Sep 2022).

Because this is a fairly large section and even the parts which don't require a rethink are likely to involve some fiddling (syntax changes and the like), it may be a while if I find there are problems with the approach outlined above, but that is my thinking so far. ~~My work to date is at https://github.com/jkingdon/set.mm/tree/iset-sum~~ _That branch was merged at #2184 but further changes will be needed before summation can be considered "done"_

**Comment by digama0** [comment]
> The `if(𝑛 ∈ 𝐴, ⦋𝑛 / 𝑘⦌𝐵, 0)` portion of the definition will only work well if `𝑛 ∈ 𝐴` is decidable. I expect various theorems will need a hypothesis like `( ( ph /\ x e. ZZ ) -> DECID n e. A`. Fortunately, this should be satisfied by a lot of the usual suspects like `NN` and other upper integer sets, integer ranges, and maybe others. But it would not be satisfied by pathological subsets of `(ℤ≥‘𝑚)` analogous to the ones in, for example, http://us.metamath.org/ileuni/onsucelsucexmidlem.html .

For sums of positive real numbers, you can define `sum_ n e. A F(n)` as the supremum of all finite sums of elements which all satisfy `A`, and this works even if `A` is not a decidable set. However I'm not sure if cauchy reals have the supremum property in this sense, and you can use `sum_ n e. { x | x = 1 /\ p } 1 = if (p, 0, 1)` as an argument that if the sum exists and satisfies the usual properties, then excluded middle holds, so probably there isn't much point in investigating the nondecidable sets here. Observe also that you can always just set `A` to `NN` and play with `B` instead, so there is no real loss of generality in restricting to decidable sets.

As far as I can tell, you are right about `sumz`. It would be nice to be able to generalize that to all sets, but without the ability to take the supremum of an arbitrary set of real numbers (which I think is possible with dedekind reals but not cauchy reals) you will have to restrict at least to predicates that are Sigma_1 or some such thing, at which point you are better off not bothering and just stick to decidable sets.

**Comment by jkingdon** [comment]
> Observe also that you can always just set `A` to `NN` and play with `B` instead, so there is no real loss of generality in restricting to decidable sets

Hmm, I think "play with B" in the general case might involve putting into `B` an `if` expression on the very condition that would have made the set you were thinking of using as `A` undecidable.

But at this point I'll be happy if I can just make this whole thing work with decidable sets. It seems to cover the vast majority (all?) of the ways this would be used in practice. Your thoughts about supremums and related topics are interesting ones but I don't think starting with the decidable case will make it harder to take those up when/if we want to in the future.

**Comment by jkingdon** [comment]
At this point summation is well developed, sufficient for example https://us.metamath.org/ileuni/eff.html , https://us.metamath.org/ileuni/mertensabs.html , and a bunch of others. As far as I noticed everything mentioned in this issue is done and if we notice something else we can open a new issue for it.
