### ISSUE TITLE
Check all .mm databases in CI workflow

### ISSUE THREAD

**Issue by david-a-wheeler** [metamath/set.mm#2342]
Our current CI workflow, set in `.github/workflows/verifiers.yml`, only checks `set.mm` and `iset.mm`. We should check all databases with at least one verifier. I don't think we need to use every verifier, as the other databases aren't as widely used/depended on.

See #2334.

I plan to do this, consider this my reminder to myself (and a way for others to nag me if I forget).

**Comment by david-a-wheeler** [comment]
PR #2343 changes the CI check to check all .mm databases at least once (using C metamath.exe). It fails, because many .mm databases don't pass the verification check. We could weaken the verification check, or fix the databases.

**Comment by benjub** [comment]
@david-a-wheeler : So I guess your latest comment means that this issue can be closed ?

**Comment by david-a-wheeler** [comment]
Yes, I'll close this, per the changes made in #2343 that implemented this.

The current CI workflow includes this line:

>      - run: ls -1 *.mm | sed -e '/^set\.mm$/d' -e '/^iset\.mm$/d' | while read db; do scripts/verify --top_date_skip --no-verify-markup "$db"; done

That does basic verification of all the .mm databases except set.mm and iset.mm. We handle set.mm and iset.mm separately, with more checking for various comment conventions, etc.
