### ISSUE TITLE
github actions sometimes but not always catch bibliographic reference problem

### ISSUE THREAD

**Issue by jkingdon** [metamath/set.mm#2377]
Recently, there was introduced a problem in bibliographic formatting in the comment of `breprexp` which generates the following error:

```
?Warning: Bibliography keyword missing in comment for "breprexp".
(See HELP WRITE BIBLIOGRAPHY for list of keywords.)
```

Or perhaps more precisely, it is supposed to generate that error, but whether it does on the tests that run when we push up branches seems to be mysteriously non-deterministic (or controlled by yet to be identified factors, more likely).

Examples where the tests passed (and should not have);
* https://github.com/metamath/set.mm/runs/4573373217?check_suite_focus=true
* _the pull request which merged the bad markup_

Examples where the tests (correctly) failed:
* https://github.com/jkingdon/set.mm/actions/runs/1597980267
* https://github.com/jkingdon/set.mm/runs/4579038688?check_suite_focus=true

See https://github.com/metamath/set.mm/pull/2363 for the discussion which led to creating this issue.

**Comment by jkingdon** [comment]
This apparently has something to do with pull request runs versus branch runs. At least, here are two runs for the same revision f1a206b09df11e9cc7e16ef5ddb16ef39ca117eb 
* https://github.com/metamath/set.mm/runs/4587633776?check_suite_focus=true (pull request, passes)
* https://github.com/jkingdon/set.mm/actions/runs/1603974060 (branch, fails)

**Comment by benjub** [comment]
@jkingdon : Is this still failing, or is it fixed ? If fixed, can we close ?

**Comment by jkingdon** [comment]
> @jkingdon : Is this still failing, or is it fixed ? If fixed, can we close ?

I don't remember seeing it in a while. I think we fixed the bad markup.

I created this issue at @david-a-wheeler 's request at https://github.com/metamath/set.mm/pull/2363#issuecomment-997640725 so I suppose he's the main stakeholder for whether to keep it open, but I'm fine with closing it even if we never did really take the time to understand/diagnose the underlying issue. I mean, unless someone still wants to work on it, that is.

**Comment by david-a-wheeler** [comment]
Some problems only show on pull requests vs. branch runs - that's inevitable & why tests are run on both.

I think we can close this, so I'll do so. If someone thinks we should reopen, please post!

**Comment by jkingdon** [comment]
> Some problems only show on pull requests vs. branch runs - that's inevitable & why tests are run on both.
> 
> I think we can close this, so I'll do so. If someone thinks we should reopen, please post!

Uh, OK, I guess maybe some day I'll need to understand what the difference is between branch runs and pull request runs. But I'm OK with not worrying about it unless/until a similar issue comes up again.

**Comment by benjub** [comment]
> the difference is between branch runs and pull request runs

I would say that the run that happens when I "git push origin" to my local repo on github is a branch run, while the run that happens when I do a PR is a PR run ?
