### ISSUE TITLE
List of Metamath databases outside of the set.mm repository

### ISSUE THREAD

**Issue by tirix** [metamath/set.mm#2384]
In a remark in PR #2373 , I suggested we'd list Metamath databases which are not in the set.mm repository (this repository).
Here are a few, in no particular order:

* @digama0 's [Dependent-Type Theory](https://github.com/digama0/dtt.mm/blob/master/dtt.mm) 
* ~@sctfn 's [New Foundations](https://github.com/sctfn/metamath-nf/blob/master/nf.mm)~ - (Actually moved here)
* @tirix 's [Q0 Logic](https://github.com/tirix/q0.mm)
* @pbrosnan [Number Theory Game](https://github.com/pbrosnan/ntg) Based on peano.mm, with additions.
* @geohot 's [TwitchCoq](https://github.com/geohot/twitchcoq/blob/master/metamath/realtwoplustwo.mm) has a few interesting 2+2 proofs
* @ishanpm 's [Linear Logic](https://github.com/ishanpm/metamathlinear/blob/master/linear.mm)
* @jamesjer 's [Unlimited Register Machine and Hilbert Geometry](https://github.com/jamesjer/set.mm/blob/geometry/set.mm) is a fork of set.mm with very interesting work which has not been merged back, IIRC
* @sorear 's [A variation on Peano](https://github.com/sorear/metamath-stuff/blob/master/yapeano.mm) where expressions variables cannot fail to refer
* @rod-lin 's [Matching Logic](https://github.com/rod-lin/kore2mm/blob/master/prelude.mm) - the result of a Kore-to-MM conversion.

There are also several [test databases](https://github.com/david-a-wheeler/metamath-test) collected by @david-a-wheeler .

**Comment by david-a-wheeler** [comment]
How about putting this in an "OTHER-DATABASES.md" file, and link to that from the README?

That'll help make it clearer what is *not* in this repo, while still providing links to them. I fear that if we mention them in the README file, someone will think they're included no matter what the introductory text says :-).

**Comment by savask** [comment]
There's also a "Laws of forms" database: https://naipmoro.github.io/lofmm/

Also maybe one should consider putting the list of other databases on the webpages, for example, here: http://us2.metamath.org:88/other.html

**Comment by tirix** [comment]
Yes, my original thought was also that the ideal place for this kind of information is on the website.

Github files can include basic information about the project, about how to contribute, rules, CI, etc.
But beyond that, I would expect other information to be on the website.

**Comment by tirix** [comment]
I also recently made an experiment with FOL "without overloading", i.e. the equality and membership predicates (`=` and `e.`) have two different flavors, one for set variables and one for classes, instead of being "overloaded" with both. It can be found here:
[https://github.com/tirix/set-noov.mm](https://github.com/tirix/set-noov.mm)
