### ISSUE TITLE
How should we use # in iset.mm?

### ISSUE THREAD

**Issue by jkingdon** [metamath/set.mm#2528]
Here's a summary of the status quo (after #2525 ) with respect to usage of the ` # ` symbol or variations thereof:

| file    | abbreviation | ASCII | typeset | meaning | example
|--------|------------------|---------|------------|-------------|-----
| set.mm  | hash         | #     | #       | set size function | [hashen](http://us.metamath.org/mpeuni/hashen.html)
| iset.mm | ap           | #     | #       | apartness relation | [apcotr](http://us.metamath.org/ileuni/apcotr.html)
| iset.mm | size         | size  | ♯   | set size function | [sizeen](http://us.metamath.org/ileuni/sizeen.html)

I'm thinking of maybe changing this to:

| file    | abbreviation | ASCII | typeset | meaning
|--------|------------------|---------|------------|-------------
| set.mm  | hash         | #     | #       | set size function
| iset.mm | ap           | =//=  | #       | apartness relation
| iset.mm | hash         | #     | ♯   | set size function

Perhaps my strongest motive is to reduce the need to change "#" to "size" when copy-pasting expressions from set.mm to iset.mm. Also changing the abbreviation used in names would reduce needless theorem renames when they are driven just by "hash" versus "size".

The suggestion of `=//=` is one that @digama0 made at https://github.com/metamath/set.mm/pull/1437#issuecomment-578433332 . Although apartness is common enough (it appears in pretty much any theorem involving division or multiplicative cancellation of real or complex numbers) that I'm now beginning to wonder whether the above is misguided and we should stick with the "status quo" table above. Hence me putting this forth in an issue for community discussion.

**Comment by jkingdon** [comment]
Oh and at the risk of stating the perhaps-obvious, the two tables above aren't the only choices. Another possibility would be to change set.mm to make it more similar to iset.mm:

| file    | abbreviation | ASCII | typeset | meaning 
|--------|------------------|---------|------------|-------------
| set.mm  | size         | size    | ♯       | set size function 
| iset.mm | ap           | #     | #       | apartness relation
| iset.mm | size         | size  | ♯   | set size function

and there could well be other plausible choices.

**Comment by tirix** [comment]
`=//=` looks good to me for apartness as it is similar to both `#` and `≠`.
Though I've not been contributing to iset.mm, so I don't think I really have a say: you are the bigger stakeholder there.

**Comment by benjub** [comment]
My preference would be to use the same abbreviations, ascii and unicode for both set.mm and iset.mm:
| file    | abbreviation | ASCII | unicode | meaning 
|--------|------------------|---------|------------|-------------
| set.mm  | size         | size    | size       | set size function 
| iset.mm | ap / apart          | =//=     | #       | apartness relation
| iset.mm | size         | size  | size   | set size function

I think that "size" is explicit and hard to misunderstand.

**Comment by jkingdon** [comment]
Since I opened this issue I've had a few more days of working with these theorems and, well, a few observations: (1) there are theorems, like http://us.metamath.org/ileuni/sizefz1.html and http://us.metamath.org/mpeuni/hashfz1.html which are the same in set.mm and iset.mm and so part of me finds the differences in naming a bit jarring, (2) there are also a large number of theorems, perhaps more in number, which are different between set.mm and iset.mm for reasons having nothing to do with notation. One example is http://us.metamath.org/mpeuni/hashf1rn.html / http://us.metamath.org/ileuni/sizef1rn.html but other examples are http://us.metamath.org/mpeuni/hasheq0.html (needs to change A e. V to A e. Fin), http://us.metamath.org/mpeuni/hashrabrsn.html (apparently would need both `A e. V` and `DECID ph`), and others.

I suppose I'm a bit indecisive (and/or reluctant to change the status quo) by nature, but aside from that I'm not sure an obvious answer is emerging, at least not in my mind.

**Comment by benjub** [comment]
Your comment reinforces my opinion that having the same notation in set.mm/iset.mm helps focus on the real differences. Also, when in doubt, tending to a notation which is explicit and "hard to misunderstand" seems wise.

Since this may imply changes in set.mm, what do others (especially @digama0, who worked on the "hash" section of set.mm) think of the different proposals above ?

**Comment by digama0** [comment]
I'm not in a hurry to implement the proposed changes, but I'm not against the use of `size` for this function, although this might collide with other senses of "size" that we might want later.

**Comment by avekens** [comment]
I would prefer to keep the # symbol (ASCII) instead of `size` in set.mm, because it is shorter to write `( # `` M ) ` instead of ` ( size `` M ) `, and a real symbol is more emphazising than a textual one. To change the typeset to ♯ would be fine for me. Also to change the abbreviation to "size" would be OK, but this should be announced before such a change is performed (it would have an impact on a lot of theorems). Currently, it would interfere with my work in progress...

**Comment by jkingdon** [comment]
My reactions so far:

1. I'm not in a hurry either. We can think about this a while and see if anyone else has ideas or our own reactions evolve.
2. I guess my current thinking, based partly on the above comments, is:

| file    | abbreviation | ASCII | typeset | meaning
|--------|------------------|---------|------------|-------------
| set.mm  | hash         | #     | ♯       | set size function
| iset.mm | ap           | =//=  | #       | apartness relation
| iset.mm | hash        | #     | ♯   | set size function

where iset.mm theorem names would add `fi` where `A e. V` (set.mm) changes to `A e. Fin` (iset.mm) and make some other naming adjustment (e.g. add `dc` if we add `DECID` somewhere) for other kinds of changes. The only change to set.mm would be to the `htmldef`, `althtmldef`, and `latexdef` so it would be a pretty self contained impact. The impact to iset.mm would be larger (which is part of why I don't want to rush into this - to reduce the chance we change hundreds of theorems and then want to change them again soon).

**Comment by jkingdon** [comment]
I'm planning on starting in on

| file    | abbreviation | ASCII | typeset | meaning
|--------|------------------|---------|------------|-------------
| set.mm  | hash         | #     | ♯       | set size function
| iset.mm | ap           | =//=  | #       | apartness relation
| iset.mm | hash        | #     | ♯   | set size function

as follows:

1. Change the ASCII syntax of apartness in iset.mm from `#` to `=//=`.
2. Change the ASCII syntax of set size in iset.mm from `size` to `#`.
3. Change the typeset syntax of set size in set.mm from `#` to `♯`.
4. Start renaming the iset theorems with "size" in their name back to the set.mm names or other names built on those using "hash" rather than "size".

In particular, I think 1 to 3 above may be pretty quick once I get started. Number 4 will probably be more incremental over a larger period of time.
