### ISSUE TITLE
Intuitionize seqf1o

### ISSUE THREAD

**Issue by jkingdon** [metamath/set.mm#2575]
That is, set.mm has http://us.metamath.org/mpeuni/seqf1o.html and iset.mm does not have anything particularly close.

There's some discussion of potentially related theorems at https://github.com/metamath/set.mm/pull/2574 and https://github.com/metamath/set.mm/pull/2551 (disclaimer: although the topics mentioned there are interesting ones, some of them might be red herrings with respect to `seqf1o` - so don't take that discussion as necessarily a blocker).

It is likely that some of the occurences in seq1fo of `( M ... N )` can be changed to ``( ZZ>= ` M )`` without making life more difficult for http://us.metamath.org/mpeuni/summolem3.html (this is the usage of `seqf1o` which we're concerned about currently)

**Comment by jkingdon** [comment]
I'm not sure I see all the pieces, but my current thinking is that we'll want a version of theorems such as http://us.metamath.org/ileuni/iseqfveq.html which change `𝑥 ∈ (ℤ≥‘𝑀)` in the closure hypothesis to `x e. M ... N` (likewise for `x e. M ... ( N + 1 )` in theorems such as http://us.metamath.org/ileuni/iseqp1.html ).

Most of the reason that existing theorems need to look at the values of `F` "too far out" (that is, beyond values which should matter) is that they they use closure hypotheses when they are proving that something like `seq` ends up with a function. So if we can show we end up with a function anyway, we should be good. I'm thinking of something along the lines of http://us.metamath.org/ileuni/frecuzrdgtcl.html but with a weaker conclusion (`Fun T` or something similar) and which would omit the `((𝜑 ∧ (𝑥 ∈ (ℤ≥‘𝐶) ∧ 𝑦 ∈ 𝑆)) → (𝑥𝐹𝑦) ∈ 𝑆)` hypothesis (or replace it with something weaker).

We talked about this at https://github.com/metamath/set.mm/pull/2551#issuecomment-1073184307 and my current thinking of how to handle the "breaking down the function value operation" part of it is to intersect the would-be function with `( _V X. _V )`. A first piece of that is at #2584 . This is still a few steps away from anything which directly touches `frec` or `seq` but I find it encouraging that I found a proof for `Fun ( { <. A , B >. } i^i ( _V X. _V ) )` which didn't need case elimination on whether `B` is a set or a proper class (the idea here is that the ordered pair would be the `⟨(𝑥 + 1), (𝑦 + (𝐹‘(𝑥 + 1)))⟩` from http://us.metamath.org/ileuni/df-iseq.html ).

**Comment by jkingdon** [comment]
I don't know how much to talk about a partially completed proof, but I've been working on this and apparently making good progress on the https://github.com/jkingdon/set.mm/tree/iset-summo branch towards a proof of seqf1o adapted for iset.mm. It doesn't do much in terms of being able to stop recursion or `seq` after a finite number of terms. Instead, it uses `if` a fair bit and adds hypotheses along the lines of

```
iseqf1o.h $e |- ( ( ph /\ x e. ( ZZ>= ` M ) ) -> ( H ` x ) e. S ) $.
```

(much the same way as many of the `seq` theorems now in iset.mm). It is pretty thoroughly rearranged from the set.mm proof (partly due to these issues about where functions are defined and evaluated, maybe in other cases unnecessarily).

Not sure I can confidently say there will be no roadblocks, but the lemmas on that branch I think probably outline what can be turned into a successful proof.

**Comment by benjub** [comment]
I've only skimmed through the statements and haven't looked at the proofs, so the following may or may not apply.  Regarding ~nnsplit and ~isummolemnm/~isummolem3: I would try to favour as much as possible NN0 (the monoid of natural numbers) over NN (the semigroup of nonzero natural numbers).

> It is pretty thoroughly rearranged from the set.mm proof

I hope you can "retrofit" these enhancements back into [set.mm](http://set.mm/).

**Comment by jkingdon** [comment]
> Regarding ~nnsplit and ~isummolemnm/~isummolem3: I would try to favour as much as possible NN0 (the monoid of natural numbers) over NN (the semigroup of nonzero natural numbers).

This part of the proof is taken very directly from set.mm and goes all the way back to https://us.metamath.org/mpeuni/df-sum.html where the definition refers to ` 1 ... m ` rather than ` 0 ... m ` and `seq 1` rather than `seq 0` . I suppose if you wanted you could experiment with what it would take to make it zero-based but I'm not sure it is appealing to give up the property that the `m` in the second half of the definition  is the number of elements in the set ` A `.

> > It is pretty thoroughly rearranged from the set.mm proof
> 
> I hope you can "retrofit" these enhancements back into `set.mm`.

I'm afraid enhancement would be a bit of an optimistic take. The proof is turning out to be much, much longer than the set.mm one and even what I thought would be easy seems to take a lot of steps. On the plus side, it does seem to be working and I'm not sure a more modest set of changes to the set.mm proof would work given the issues around functions being evaluated outside their domains or the various differences in `seq`.
