### ISSUE TITLE
Consider alternate forms of relative set complements in iset.mm

### ISSUE THREAD

**Issue by jkingdon** [metamath/set.mm#2619]
Currently iset.mm copies the definition of relative set complement from set.mm: `(𝐴 ∖ 𝐵) = {𝑥 ∣ (𝑥 ∈ 𝐴 ∧ ¬ 𝑥 ∈ 𝐵)}` ( http://us.metamath.org/ileuni/df-dif.html ). Although this is widely used enough in iset.mm that presumably we will keep it, it does fail to have many of the properties that it has in set.mm and perhaps the situation is at least a little bit analogous to http://us.metamath.org/mpeuni/df-pss.html and http://us.metamath.org/mpeuni/df-sdom.html

There is another definition given by page 10 of [1] which is `X \ Y = { α ∈ X | ∀β ∈ Y α =/= β }` . At a minimum, I suppose we should mention this in the df-dif comment but perhaps there is a source we can cite which goes into more detail (I didn't quickly find one), or theorems/definitions we can add.

[1] "Infinite Omniscient Sets in
Constructive Mathematics" by Ceel Pierik, https://www.cs.ru.nl/bachelors-theses/2020/Ceel_Pierik___4806182___Infinite_Omniscient_Sets_in_Constructive_Mathematics.pdf

**Comment by benjub** [comment]
Aren't these equivalent ?

**Comment by jkingdon** [comment]
> Aren't these equivalent ?

I'm not sure - anyone know? Or wants to try proving it one way or the other in metamath?

**Comment by benjub** [comment]
this looks like the intuitionistic contrapositive (with subsitutibility of equals) to me:
```
\forall y \in B x =/= y <=>
\forall y ( y \in B -> x =/= y) <=>
\forall y ( y = x -> y \notin B) <=>
\forall y ( y = x -> x \notin B) <=>
\exists y ( y = x and x \notin B) <=>
(\exists y y = x) and x \notin B <=>
x \notin B
```

**Comment by jkingdon** [comment]
> this looks like the intuitionistic contrapositive (with subsitutibility of equals) to me:

My devious scheme to talk you into writing the formal version of the proofs appears to have failed again! Oh well, formalizing this informal proof - see #2624 - was doable and I'm not sure I would have easily come up with it on my own.

> ```
> \forall y \in B x =/= y <=>
> \forall y ( y \in B -> x =/= y) <=>
> \forall y ( y = x -> y \notin B) <=>
> \forall y ( y = x -> x \notin B) <=>
> \exists y ( y = x and x \notin B) <=>

I didn't see a way to biconditionalize this step. Instead I used http://us.metamath.org/ileuni/exintr.html which means the proof as outlined in this comment only proves subset rather than equality. Fortunately, the reverse subset proposition is not hard to prove another way, so this doesn't affect the end result.

> (\exists y y = x) and x \notin B <=>
> x \notin B
> ```

**Comment by benjub** [comment]
I was thinking of equs4v

**Comment by jkingdon** [comment]
> I was thinking of equs4v

Oh of course. equs4v isn't a biconditional but http://us.metamath.org/ileuni/sb56.html is. Probably could shorten the proof a bit if someone wants to take this up some day.

**Comment by benjub** [comment]
> > I was thinking of equs4v
> 
> Oh of course. equs4v isn't a biconditional but http://us.metamath.org/ileuni/sb56.html is.

Sorry, that was sb56 indeed (I had modified the comment of http://us.metamath.org/mpeuni/equs4.html to signal it).

> if someone wants to take this up some day.

so sneaky !

**Comment by jkingdon** [comment]
> so sneaky !

:imp:
