### ISSUE TITLE
define notation for omniscience in iset.mm

### ISSUE THREAD

**Issue by jkingdon** [metamath/set.mm#2620]
As suggested at https://github.com/metamath/set.mm/issues/2595#issuecomment-1157367557 we should define

```
A e. Omni <-> A. f : A --> 2o ( E. x e. A ( f ` x ) = (/) \/ A. x e. A ( f ` x ) = 1o )
```

This matches the definition of '''omniscient set''' at Definition 3.1 of [Pierik], p. 14.

We can also prove:
* `A e. Fin -> A e. Omni`
* `A. x x e. Omni` implies excluded middle (see "If you take it to be the subsingleton corresponding to a given truth value and apply this principle to the constantly true proposition, then EM follows" at https://ncatlab.org/nlab/show/principle+of+omniscience )
* Perhaps prove in set.mm that ``A. z A. f : z --> 2o ( E. x e. z ( f ` x ) = (/) \/ A. x e. z ( f ` x ) = 1o )`` (no need for a specific notation for `Omni` here, I suppose)

Mention in a comment that `_om e. Omni` is the Limited Principle of Omniscience (LPO).

[Pierik] "Infinite Omniscient Sets in
Constructive Mathematics" by Ceel Pierik, https://www.cs.ru.nl/bachelors-theses/2020/Ceel_Pierik___4806182___Infinite_Omniscient_Sets_in_Constructive_Mathematics.pdf

More background reading: https://ncatlab.org/nlab/show/principle+of+omniscience

**Comment by digama0** [comment]
By the way, I think it would also be useful to have a definition for EM. We can't define it in pure propositional logic because we need to quantify over propositions, but we can once we get to set theory, by quantifying over subsets of `1o` . set.mm has a definition for `CHOICE` and I think it will make it easier to do similar things like proving implications between weak EM principles just like set.mm does for choice principles.

The purpose of the definitions is not really to make the derivations shorter, although I can imagine something like that for `Omni` since there are a lot of properties that converge on this notion; rather it is intended to give a vocabulary for things that look unmotivated otherwise.

**Comment by benjub** [comment]
Something like
```
df-em $a |- ( EM <-> A . x ( x C_ 1o -> ( x = (/) \/ x = 1o ) ) ) $. 
```
?

**Comment by digama0** [comment]
Yep. That could also be written as `A. x ( x C_ 1o -> DECID (/) e. x )`, or even just `A. x DECID (/) e. x` or `A. x A. y DECID x e. y`.

**Comment by benjub** [comment]
Then maybe your first version, which seems weakest, as the definition, and my version and your latest two versions as theorems (or, waiting for a benevolent formalizer, as "TODO" comments in the definition).

**Comment by jkingdon** [comment]
> Something like
> 
> ```
> df-em $a |- ( EM <-> A . x ( x C_ 1o -> ( x = (/) \/ x = 1o ) ) ) $. 
> ```
> 
> ?

I would call it `EXMID` to follow long-standing convention in both set.mm and iset.mm but this seems like a good idea. In particular, #739 wants to say "given excluded middle, ordinal trichotomy follows" and this seems like the best way to express that.  I'm not sure I have an opinion among the various suggested definitions.

**Comment by benjub** [comment]
Agreed for the more explicit `EXMID`. I think Mario's first version, the weakest looking, should be the definition, but probably my proposal should be proved as a theorem since it is more explicit so may be more usable by other theorems. It would be nice if "someone" can also prove the equivalence with Mario's last two versions! (if not, put it as a TODO comment in df-exmid).

**Comment by digama0** [comment]
My intention with the latter versions was to try to find a "shorter" definition, either in terms of actual symbols or in terms of fewest symbols-from-axioms. Both versions use `DECID` but for the symbols-from-axioms version you could just expand that into `A. x A. y ( x e. y \/ -. x e. y )` which is still pretty short and uses only primitive connectives.

**Comment by benjub** [comment]
I would say that (important) definitions are made to be used, so the versions using DECID are better in my opinion.
IIRC, Bourbaki states the axiom of extensionality as
> (x \subseteq y \wedge y \subseteq x) \to x = y

**Comment by digama0** [comment]
Well, `EXMID`, like `CHOICE`, is bound to get tens or even hundreds of equivalent definitions, so in the long run I don't think that it's necessary to optimize the definition for use. The actual "optimized for use" theorem will be `EXMID -> DECID ph` or a few variations on this for proof by cases; for proving `EXMID` I would guess we want either `EXMID <-> A. x ( x C_ 1o -> ( (/) e. x \/ -. (/) e. x ) )` or `EXMID <-> A. x ( (/) e. x \/ -. (/) e. x )` for direct proofs, or one of the many equivalent definitions if going via an intermediate.

**Comment by jkingdon** [comment]
> waiting for a benevolent formalizer

My ears are burning! On the other hand you were the benevolent formalizer for http://us.metamath.org/ileuni/ax-bdsep.html which does get a mention in this work.

What I have so far on `EXMID` is at #2629 but I expect to add most/all of the suggestions which are currently in this thread before moving it from draft pull request to regular pull request.

**Comment by david-a-wheeler** [comment]
@digama0 :
> ... The purpose of the definitions is not really to make the derivations shorter, although I can imagine something like that for Omni since there are a lot of properties that converge on this notion; rather it is intended to give a vocabulary for things that look unmotivated otherwise.

I think that's a great use for definitions. While it's obviously possible to add information in comments, formally defining a term creates a common vocabulary. It also provides a single location to officially define & explain that definition. It *can* also provide flexibility in formalization, that is, some ideas can be expressed in various different formal ways & we can "hide" the expression behind its definition. Like anything this can be taken too far (since sometimes you may need to unwind a lot of definitions), but I think we should probably create more definitions than we have so far.

**Comment by benjub** [comment]
> I think that's a great use for definitions. While it's obviously possible to add information in comments, formally defining a term creates a common vocabulary. It also provides a single location to officially define & explain that definition. It _can_ also provide flexibility in formalization, that is, some ideas can be expressed in various different formal ways & we can "hide" the expression behind its definition. Like anything this can be taken too far (since sometimes you may need to unwind a lot of definitions), but I think we should probably create more definitions than we have so far.

I generally share this view, but one has to be careful that a vocabulary is useful when it is shared widely (I mean: it has to be common beyond Metamath), and that having to learn a large new vocabulary constitutes a hurdle when moving to a new field (so too much of it could discourage Metamath adoption).

**Comment by avekens** [comment]
> > I think that's a great use for definitions. While it's obviously possible to add information in comments, formally defining a term creates a common vocabulary. It also provides a single location to officially define & explain that definition. It _can_ also provide flexibility in formalization, that is, some ideas can be expressed in various different formal ways & we can "hide" the expression behind its definition. Like anything this can be taken too far (since sometimes you may need to unwind a lot of definitions), but I think we should probably create more definitions than we have so far.
> 
> I generally share this view, but one has to be careful that a vocabulary is useful when it is shared widely (I mean: it has to be common beyond Metamath), and that having to learn a large new vocabulary constitutes a hurdle when moving to a new field (so too much of it could discourage Metamath adoption).

I wonder why it should be encoraged to introduce more definitions now! We have the convention "New definitions infrequent.", and many proposals I made in the past were rejected (for example definitions of ` Even ` and ` Odd `, see issue #1682). What is the difference, and what intention changed now? We should, however, continue this discussion in the Google group, if necessary.

**Comment by jkingdon** [comment]
> wonder why it should be encoraged to introduce more definitions now! We have the convention "New definitions infrequent."

I can't speak for everyone, but for me each definition has to stand or fall on its own merits (e.g. does it enable us to remove a dummy variable, is it shorter than the alternative, that sort of thing).

For iset.mm examples, we said yes to `DECID ph` (for several reasons, including that `ph \/ -. ph` requires repeating the formula `ph`, and that we do enough with decidable propositions that a proof like http://us.metamath.org/ileuni/dfgcd2.html is significantly helped by being able to invoke `ianordc` and `gcdmndc`. On the other hand, http://us.metamath.org/ileuni/dftest.html used to be written with a notation `TEST ph` and when we looked at how it is used there didn't seem to be any advantage to that over `DECID -. ph` so we got rid of `TEST`.

Going back to `EXMID`, did you have an alternate proposal for how to express

```
EXMID -> A. x A. y ( x C_ y <-> ( x u. ( y \ x ) ) = y )
```

? For me that is the key advantage here, and I wouldn't especially object to `DECID ph` or `ph \/ -. ph` if it could do the job (but because we can't quantify over propositions, those don't fully work the same way as `EXMID`).

At least for me #1682 is a less easy decision than many but that's probably getting a bit far afield from `EXMID` and `Omni` (remember `Omni`? This was/is an issue about `Omni`) which is the topic here.

**Comment by avekens** [comment]
@jkingdon I have nothing against the definition EXMID, quite the contrary: I fully support this. My comment is related to the general remarks on definitions within this issue. As I said before, this discussion could/should be continued elsewhere.

**Comment by jkingdon** [comment]
> @jkingdon I have nothing against the definition EXMID, quite the contrary: I fully support this. My comment is related to the general remarks on definitions within this issue. As I said before, this discussion could/should be continued elsewhere.

Oh, sorry if I jumped to conclusions and/or belabored the issue. I probably agree with your larger point, but I also find it a bit hard to have a position independent of specific examples.
