### ISSUE TITLE
Define N_infinity in iset.mm

### ISSUE THREAD

**Issue by jkingdon** [metamath/set.mm#2621]
At the moment iset.mm has http://us.metamath.org/ileuni/df-xnn0.html but this is not the most useful definition in the absence of excluded middle.

We would like to define it with a definition like the one in Section 3.1 of [Pierik], p. 15.

Chances are #2622 is a prerequisite.

There's also the question of notation: because this set includes zero, perhaps we want to keep the ℕ<sub>0</sub><super>*</super> notation  rather than trying to subscript ℕ with both zero and `∞`? It doesn't seem especially appealing to use ℕ<sub>∞</sub> for a something which includes zero. More than notation but perhaps related is the question of whether ℕ<sub>0</sub> is a subset of N_infinity or whether its elements can just be mapped to elements of N_infinity.

We can prove:
* N_infinity = ( NN0 u. { ∞ } ) <-> _om e. Omni (Proposition 3.6.1 of [Pierik], p. 15)
* N_infinity e. Omni (Theorem 3.4 of [Pierik], p. 15, where Omni is defined at https://github.com/metamath/set.mm/issues/2620 )

[Pierik] "Infinite Omniscient Sets in
Constructive Mathematics" by Ceel Pierik, https://www.cs.ru.nl/bachelors-theses/2020/Ceel_Pierik___4806182___Infinite_Omniscient_Sets_in_Constructive_Mathematics.pdf

More background reading: https://ncatlab.org/nlab/show/extended+natural+number

**Comment by benjub** [comment]
To keep compatibility with set.mm, I think we should keep df-xnno with its current definition, and *in addition* add Escardo's one-point compactification. Maybe use $\mathbb{N}_\infty$ for the latter (two subscripts would be a bit heavy). State in its comment that it's the more useful notion in the constructive context. Then we have a theorem `$e |- I = ... $.  $p |- I : xNN0 -1-1-> NNinfty` and you can prove that I being bijective is equivalent to the limited principle of omniscience in the form `omega e. Omni`.

I think it would be too cumbersome to adapt either set to have a genuine inclusion. We have `NN0 C_ xNN0` and the above natural  injection `I`, and we should probably be content with that.

**Comment by jkingdon** [comment]
I've been looking at the Pierik in more detail, and a few observations:

1. A closer reading of the paper shows that they follow BJ's suggestion of not identifying natural numbers with elements of N_infinity but talking about a mapping between the the two - if n is a natural number, they use an underlined n to mean the mapping of n into an element of N_infinity. They also use ∞ to denote an element of N_infinity (a sequence of all ones). Using BJ's suggestion in which `I` is the mapping from an element of `NN0*` to an element of N_infinity, then ``( I ` +oo )`` would be an element of N_infinity.
2. There is a lot which we could formalize, including a bunch of observations about the Weaker Lesser Principle of Omniscience and Markov’s Principle. Unless I missed something they aren't needed for the key theorem that `N_infinity e. Omni`, so perhaps these are best saved for another day.
3. Oh, and while I'm at it I suppose we'll need to figure out the source code we want in iset.mm for N_infinity. Maybe `NN+oo` would be good? And typeset it as ℕ<sub>∞</sub> as suggested by BJ.
4. As far as I noticed we don't need the results from that paper concerning metrics and apartness.
5. It apparently is easier to show that `_om e. Omni <-> ( I " NN0* ) = NN+oo` (Proposition 3.6.1 of Pierik) than that `NN+oo e. Omni` so perhaps we should start with the former (or even more elementary theorems about `NN+oo` if they would be useful building blocks).
6. For `NN+oo e. Omni`, we apparently need notations (or expressions which we repeat as needed) for searchable set and full subset. I don't think we would need to explicitly define congruent sets.

**Comment by benjub** [comment]
I haven't looked at that paper in detail, but all your proposals sound reasonable.

**Comment by jkingdon** [comment]
There are still things we could prove about ℕ<sub>∞</sub> but it is now defined at https://us.metamath.org/ileuni/df-nninf.html and we even have https://us.metamath.org/ileuni/nninfomni.html so I'm going to call this done. Feel free to open issues or pull requests for remaining topics as desired.
