### ISSUE TITLE
How long does it take `mmverify.py` linked to on the metamath homepage to run on `set.mm`?

### ISSUE THREAD

**Issue by enjoysmath** [metamath/set.mm#2676]
Hi,

I'm running it now and it's not printing anything but it's also not crashing, so I think it's doing it's thing.  How long until it completes on a typical laptop?

Thanks.

**Comment by benjub** [comment]
Around 30sec on my 4yo desktop. Run it with verbosity 1:
```
$ python3 mmverify.py -v 1 set.mm
```
To see other options, look at the help: `$ python3 mmverify.py -h`. To time it: `$ time python3 mmverify.py -v 1 set.mm`

**Comment by enjoysmath** [comment]
That's not working for me either.  I think it's running except it's waiting
for input or something like that.

**Comment by benjub** [comment]
Try with iset.mm: 4seconds for me.

**Comment by enjoysmath** [comment]
It's "python -m mmverify -v 1 < set.mm" on my machine.  Thank you!  Yes,
takes forever to run though :D

**Comment by enjoysmath** [comment]
My verifier is going to make you pass in just "set.mm" and will do no
piping because my IDE wingware doesn't seem to like what it's doing.  The
same emulated in the IDE, and it waits for input, so...  I can't run my
debugger on it as I usually do.

**Comment by benjub** [comment]
Make sure you have the version at https://github.com/david-a-wheeler/mmverify.py/blob/master/mmverify.py
