### ISSUE TITLE
Proposal: Switch to logical quotation system by convention

### ISSUE THREAD

**Issue by david-a-wheeler** [metamath/set.mm#2786]
I propose that we document in our conventions that we use the *logical* quoting system, not the *typesetters'* quoting system, within future text and that we slowly switch to it. In the *logical* system, quotations only include punctuation if they are in the original quote; in the *typesetters'* system, commas and periods (but typically not other punctuation) are moved from the outside to the inside of a quote if they appear after the quote, even if the quote did not include the punctuation. Sometimes these are called "British" and "American" quoting, but those names are misleading, since both systems are used in formal publications on both sides of the pond.

This proposal was briefly discussed in [PR #2772](https://github.com/metamath/set.mm/pull/2772).

Currently we inconsistently use both, depending on the committer, and that inconsistency can be confusing. So I think it's worth picking one and moving towards it.

Wikipedia (among other organizations) uses the logical quoting system, and there's a good article on [Why Wikipedia uses logical quotation](https://en.wikipedia.org/wiki/Wikipedia:Logical_quotation_on_Wikipedia). One of their arguments is especially relevant here: "Logical quotation is precise; typesetters' often falsifies quoted material". Given that we are trying to be precise, I think that *alone* justifies using it.

It will take time to make things consistent, and there's no reason to drop everything. I suggest starting by documenting in our conventions that all *new* text use this convention, and that we encourage people to adjust the text as they adjust other things. We could eventually do a mass fix of the remainder after a while; at that point it would be easier to do.

**Comment by wlammen** [comment]
I am in favour of this change.

**Comment by avekens** [comment]
I fully support David's proposal.

**Comment by benjub** [comment]
In the section `17.1.1  Conventions`, we currently have:
* ~conventions
* ~conventions-label
* ~conventions-contrib

I propose to add ~conventions-nonmath to group the non-mathematical conventions, typically typographical conventions used in comments (e.g., language and spelling, quotation style, spacing, capitalization...) and add a mini-TOC of these labels in the section head comment (like I began to do last time when I added ~conventions-label and ~conventions-contrib.

What do you think ? Recommendations on the order of these four labels and the labels themselves ? (my first idea was "conventions-typography", but there are also mathematical typography conventions, and the relevant grouping in my opinion is "non-mathematical things in their own group")

**Comment by david-a-wheeler** [comment]
@benjub - splitting it up makes sense, but "-nonmath" seems, well, not right.

I suggest that we create a separate issue to discuss splitting up "conventions", including names of the sections, & let's keep this issue focused on logical quoting. My brain is only so big :-).

**Comment by benjub** [comment]
Now documented, via #2840.
