### ISSUE TITLE
Broken links in mmdeduction.html

### ISSUE THREAD

**Issue by giomasce** [metamath/set.mm#2801]
Links to theorems `hbneg`, `hbnegd` and `abidhb` in the final paragraph of https://us.metamath.org/mpeuni/mmdeduction.html are broken. Apparently they were renamed with an `ENF` suffix in bc8e4ad5798dfbcf87a2fe3fb631511294d55910 and later removed.

I don't know what that suffix was meant to indicate, but I would suggest to either restore the theorems if they are useful examples, or remove the "Another Special Case of the Deduction Theorem" paragraph if they are not.

**Comment by david-a-wheeler** [comment]
I think we should restore them.

**Comment by benjub** [comment]
@david-a-wheeler : I assumed that in "we should restore them", you were not using the royal we, so I fixed the broken links in #2842, with some other minor fixes.
@giomasce : the relabelings were due to the fact that we mainly switched from the hb* idiom to the nf* idiom in most proofs.
