### ISSUE TITLE
pm11.07 in set.mm is not what it appears to be

### ISSUE THREAD

**Issue by jkingdon** [metamath/set.mm#281]
The distinct variable constraints in http://us2.metamath.org:88/mpeuni/pm11.07.html make the theorem a trivial one, which has little application.

The distinct variable constraints between `𝜑` and `𝑥`, and between `𝜑` and `𝑧`, mean that both sides of the theorem (`[𝑤 / 𝑥][𝑦 / 𝑧]𝜑` and `[𝑦 / 𝑥][𝑤 / 𝑧]𝜑` immediately simplify to `𝜑` (via `nfv` and `sbf` and the usual machinery around `sbbii` and biconditional transitivity).

In case the above is unclear, here's the trivial proof above as a metamath compressed proof of `pm11.07`  (this is for the 20-Jan-2018 version of set.mm but applies with slight changes to iset.mm too):
```
$=    ( wsb nfv sbf sbbii bitri bitr4i ) ADCFZBEFZAADEFZBCFZMABEFALABEADCADGZHI
      ABEABGZHJOABCFANABCADEPHIABCQHJK $.
 ```

As for what `*11.07` in Principia really is, here is the text from page 152 of https://ia600602.us.archive.org/35/items/PrincipiaMathematicaVolumeI/WhiteheadRussell-PrincipiaMathematicaVolumeI_text.pdf : 

> *11·07. "Whatever possible argument x may be, 𝜑(x,y) is true whatever possible argument y may be" implies the corresponding statement with x and y interchanged except in "𝜑(x, y)". Pp.

I don't think I can confidently turn that into metamath notation. The translation given in `pm11.07` might be roughly correct with different distinct variable constraints, or it might just map to the fact that metamath theorems are all (implicitly) theorem schemas, or perhaps something else.

As for what to do about it, perhaps just delete `pm11.07`? The history seems to say this came from a mathbox originally, don't know if that user is still active or if anyone else wants to pick up the baton.

**Comment by nmegill** [comment]
I felt this was interesting enough to post on the Google Group.
Norm

**Comment by jkingdon** [comment]
Thanks for posting that, Norm, and doing your own research. To summarize the discussion there, if no one comes up with something better soon, we should just delete `pm11.07`.

**Comment by david-a-wheeler** [comment]
If we delete it, we should retain a comment somewhere about it.  Otherwise someone might try again, without learning from the last time. I'm not sure where we put comments about something *not* done.

**Comment by nmegill** [comment]
The pm11.07 in set.mm now appears to be correct (even though extremely trivial), and there isn't any reason to delete it, so that others won't have the same confusion.  This was figured out by Benoit later in the Google Group thread:
https://groups.google.com/d/msg/metamath/iS0fOvSemC8/M1zTH8wxCAAJ

**Comment by tirix** [comment]
I suppose we can now close this issue.
