### ISSUE TITLE
Add joint denial (NOR) to set.mm

### ISSUE THREAD

**Issue by benjub** [metamath/set.mm#2818]
Among the "less common" logical binary connectives, set.mm already has a section for alternative denial (NAND) and a section for exclusive disjunction (XOR). It would be nice to add a section for joint denial (NOR). Like these other two sections, it is not meant to have many applications (stating more advanced theorems with these connectives would generally make them less readable), but simply to state the basic properties of that connective (the sections introducing NAND and XOR have 15 theorems each, organized in neatly parallel fashions). (**edit:** Additionally, the section "Truth tables" should receive a new subsection "Joint denial".)

This would make a nice first work for someone who wants to get acquainted to Metamath and set.mm.

**Comment by david-a-wheeler** [comment]
Makes sense to me. I have an electronics engineering degree, focusing on digital electronics, so for me NOR is key basic stuff :-).

**Comment by benjub** [comment]
> Makes sense to me. I have an electronics engineering degree, focusing on digital electronics, so for me NOR is key basic stuff :-).

I just learnt on wikipedia (https://en.wikipedia.org/wiki/NOR_gate) that apparently, the first Apollo lunar modules were based on NOR gates ! (But since this issue would be a nice way to get *acquainted* to Metamath and set.mm, you are banned from doing it !)

**Comment by walkingsophie** [comment]
I think I'll work on this as my first direct contribution to Metamath.

**Comment by walkingsophie** [comment]
Sorry, had some issues with setting stuff up, then real life stuff happen, then University happened, so I couldn't work on it. I'm happy for someone else to work on it.

**Comment by lesyna** [comment]
Jeff Machado and I had already discussed doing NOR before I noticed this issue. Any objections if we take it up?

**Comment by benjub** [comment]
Please, go on !

**Comment by benjub** [comment]
Closed by #3594.
