### ISSUE TITLE
"conventions-nonmath"

### ISSUE THREAD

**Issue by benjub** [metamath/set.mm#2838]
Following https://github.com/metamath/set.mm/issues/2786#issuecomment-1222432650, @david-a-wheeler suggested that I open this Issue.

With the inflation of the conventions for set.mm, I suggested, for readability, to group the nonmathematical conventions in a separate "statement" labeled `~conventions-nonmath`. Thus, the conventions Section would have:
* ~conventions
* ~conventions-label
* ~conventions-contrib
* ~conventions-nonmath

@david-a-wheeler was not enthousiastic about the name "conventions-nonmath", hence the creation of this Issue. Any opinions ?

From experience, these topics about conventions tend to stale, and if this one does, I may begin to write the convention that prompted this issue (namely, quotation style), and we can later rename things and do some resectioning (for instance: maybe `~conventions-contrib` is not that great since this is not thematic, maybe create `~conventions-proofs`, etc... but one thing at a time).

Conventions are not an interesting topic, but they are necessary in a large multi-contributor project like this one. Style and language conventions are also necessary since many contributors (and users), like me, are nonnative English speakers and are more comfortable with a more "rigid", even if less elegant, language.

Of course, an important goal should be concision, both for the sake of contributors and users. Just the amount of conventions necessary to maintain consistency and adequate standards, and no gratuitous rules.

**Comment by david-a-wheeler** [comment]
I don't object to the reorganization, just the name. Instead of `conventions-nonmath` how about `conventions-style` ?

**Comment by benjub** [comment]
I think "style" is less specific, since there is also style in the mathematical part (choice of math symbols, proof styles like "deduction style", etc.)

**Comment by david-a-wheeler** [comment]
Maybe `conventions-text` ? Naming is hard :-).

**Comment by benjub** [comment]
I guess we'll need other opinions. Maybe @digama0 and @jkingdon ?

**Comment by digama0** [comment]
What is the content of the document? If it's about the style of theorem comments, I would suggest `conventions-comments`.

**Comment by benjub** [comment]
I like @digama0's proposal `conventions-comments`.

**Comment by david-a-wheeler** [comment]
I also like `conventions-comments` !

**Comment by benjub** [comment]
Here you go: #2840
