### ISSUE TITLE
How to name the "at most one" quantifier ?

### ISSUE THREAD

**Issue by benjub** [metamath/set.mm#2839]
We need a consistent naming for quantifiers, especially the "at most one" quantifier `E*`, which is not common outside `set.mm`.  I propose **"uniqueness quantifier"**, which is self-explanatory. Currently, "uniqueness quantifier" is used in set.mm sometimes (seldom) for `E*` and sometimes (more often) for `E!`. The latter use is deceptive since `E!` is about existence as much as uniqueness. To sum up, we would have:
* `A.` universal quantifier
* `E.` existential quantifier
* `E*` uniqueness quantifier
* `E!` unique existential quantifier

(This issue was raised in a comment to PR #2836.)

**Comment by digama0** [comment]
I think "uniqueness quantifier" is not at all self explanatory, or at least the incorrect reading is at least as common as the reading you want. I don't think we need a new name for this quantifier; you already said the name, which is the "at most one" quantifier. The name df-mo also reflects this.

**Comment by benjub** [comment]
If you think understandability is at risk, then ok for "the at-most-one quantifier". (I have to admit it sounds a bit childish to me, a bit like calling a cat "the meow animal", but maybe I'm being a snob!)

**Comment by wlammen** [comment]
Here it is discussed already: https://math.stackexchange.com/questions/1205464/quantifier-for-there-is-at-most-one

**Comment by jkingdon** [comment]
at-most-one quantifier seems like the best of what I've seen so far. It is what we already call it at places like https://us.metamath.org/mpeuni/mobid.html (and using slightly different wording) https://us.metamath.org/mpeuni/eumo.html . At least to my eyes that seems a lot clearer than "uniqueness quantifier".

**Comment by benjub** [comment]
Ok, so since a majority votes for "at-most-one quantifier", I implemented it in #2843. After all, maybe it sounds strange only when translated to French and it is ok in English.
Up to now, set.mm was using "uniqueness quantifier" not consistently and at times for both E! and E*. The new situation is:
* ` A. ` universal quantifier
* ` E. ` existential quantifier
* ` E* ` at-most-one quantifier
* ` E! ` unique existential quantifier
* the phrase "uniqueness quantifier" is avoided since it is ambiguous: it can be understood as claiming either uniqueness (`E*`) or unique existence (`E!`).
