### ISSUE TITLE
What "summaries" to keep when merging ?

### ISSUE THREAD

**Issue by benjub** [metamath/set.mm#2925]
When we "squash and merge" a PR, there are two pre-filled text fields, apparently one for the title of the PR, e.g., `Redundancy (#2924)` for #2924, and one for a summary, which apparently has the concatenation of the commit messages.

I never change the title, and sometimes I remove the most trivial messages from the summary (e.g., when there are multiple `rewrap` or `typos` or `regen disc` in a row). Is there a preferred policy ? Is there a notion of "cluttering" the history with too long summaries ? Or should we enforce a strict equality between commit messages and leave the text fields strictly unchanged ?

**Comment by jkingdon** [comment]
Removing the most trivial doesn't bother me but in general I'd lean towards using the messages which were in the commit messages without changing them.

If people creating pull requests want more control over removing trivial messages and the like, they can do it using a local git program and then push them up to github - see https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History (especially the section "Squashing Commits"). But I don't think we should make this level of git familiarity a requirement.

**Comment by avekens** [comment]
I also have no clear opinion about this: I think we should not force some actions to be done, but if a contributor wants to edit the summary, he/she can do that. The only restriction should be that the summary should contain a meaningful description of the main aspects of the PR.

**Comment by benjub** [comment]
Thanks. I'll keep my current practice, and when in doubt keep the original summaries.
