### ISSUE TITLE
Prove 2irrexpq in iset.mm

### ISSUE THREAD

**Issue by jkingdon** [metamath/set.mm#2958]
This is a famous theorem which can be proved using excluded middle, for example the proof at https://us.metamath.org/mpeuni/2irrexpq.html

It is Theorem 1.2 of [[Bauer],](https://us.metamath.org/ileuni/mmil.html#Bauer) p. 483. The "Classical proof" given there is the one in set.mm

The "Constructive proof" in Bauer is "(√ 2 )<sup>log<sub>2</sub>9</sup> = √(2<sup>log<sub>2</sub>9</sup>) = √9 = 3"  plus "Of course, irrationality of log<sub>2</sub>9 needs to be established, but the proof is no harder than the one of irrationality of √2." (_update 30 Dec 2022: added missing radical symbol_)

Note that if we take `2irrexpq` as stated in set.mm and copy that to iset.mm, the resulting statement would require `a` and `b` to not be rational. We'd presumably also want to strengthen that condition and require that `a` and `b` are irrational, in the sense of apart from any rational number, as in https://us.metamath.org/ileuni/sqrt2irrap.html .

Of course we'd need https://us.metamath.org/mpeuni/df-logb.html and the related theorems (or at least a version for real arguments). Likewise to even state the desired result we need https://us.metamath.org/mpeuni/df-cxp.html (where again, we only need this to work for real arguments).

**Comment by benjub** [comment]
You can probably skip the definition of `logb`.  The proof that log(3)/log(2) is irrational looks accessible since you have already proved Euclid's lemma. Good luck !

**Comment by avekens** [comment]
> You can probably skip the definition of `logb`. The proof that log(3)/log(2) is irrational looks accessible since you have already proved Euclid's lemma. Good luck !

I think there is a "root" symbol missing in the constructive proof of Bauer. It should read: `(√2)^log_2(9) = √(2^log_2(9)) = √9 = 3` (unfortunatley, I do not know how to obtain sub-/superscripts in this editor).

How should the proof work with `log_2(3)`? We would have `(√2)^log_2(3) = √(2^log_2(3)) = √3` which is not rational.

**Comment by benjub** [comment]
If (log 3)/(log 2) is irrational, then so is (log 9)/(log 2). What I mean is that as a standalone result, irrationality of (log 3)/(log 2) seems neater.

**Comment by jkingdon** [comment]
> I think there is a \"root\" symbol missing in the constructive proof of Bauer.

It is present in the original paper; the error was me transcribing it to github (now fixed).

As for log<sub>2</sub> 9 versus ln 9/ln 2 that's a detail that whoever picks this up (not necessarily me) can worry about. At the moment we don't have any logarithms, whether natural or to an arbitrary base.

**Comment by jkingdon** [comment]
> I do not know how to obtain sub-/superscripts in this editor

I'm OK with sub-/superscripts or with other ways of getting the idea across, but in case you want to know, the sub-/superscripts are documented at https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#styling-text

**Comment by benjub** [comment]
Apparently, github now supports LaTeX , so you can write `$2^a_b$` and it will appear as $2^a_b$. Since I don't know what part of LaTeX is supported, I think you can simply write the LaTeX code and let the readers "compile" it in their head.

**Comment by avekens** [comment]
With PR #2963, the required theorems are available in set.mm now. They have to be taken over to iset.mm, after the definitions and theorems they are based on are available there. Maybe (or probably) some adaptations will be necessary, too.

These theorems are:
* [sqrt2irr0](https://us.metamath.org/mpeuni/sqrt2irr0.html): (√‘2) ∈ (ℝ ∖ ℚ)
* [2logb9irr](https://us.metamath.org/mpeuni/2logb9irr.html): (2 logb 9) ∈ (ℝ ∖ ℚ)
* [sqrt2cxp2logb9e3](https://us.metamath.org/mpeuni/sqrt2cxp2logb9e3.html):  ((√‘2)↑𝑐(2 logb 9)) = 3
* [2irrexpqALT](https://us.metamath.org/mpeuni/2irrexpqALT.html): ∃𝑎 ∈ (ℝ ∖ ℚ)∃𝑏 ∈ (ℝ ∖ ℚ)(𝑎↑𝑐𝑏) ∈ ℚ

**Comment by jkingdon** [comment]
Status report: This is now, it would appear, at the level of merely the usual kind of intuitionizing, and is getting close. We have https://us.metamath.org/ileuni/df-relog.html and https://us.metamath.org/ileuni/df-rpcxp.html . The next section (going through set.mm in order) is the one containing https://us.metamath.org/mpeuni/2irrexpqALT.html .

We'd presumably also want a variation of 2irrexpq which strengthens the irrationality condition to require that a and b are irrational in the sense of apart from any rational number, as in https://us.metamath.org/ileuni/sqrt2irrap.html . But if past experience is a guide, that isn't usually very hard.
