### ISSUE TITLE
Merge develop into master

### ISSUE THREAD

**Issue by david-a-wheeler** [metamath/set.mm#30]
The latest development branch has lots of goodness, however, it's not obvious because the default branch is 'master'.  Simple solution: at some point, merge develop into master.

**Comment by digama0** [comment]
I leave this to @nmegill . The idea is that master commits match updates to the web site, but I think the master commit has been lagging behind of late.

**Comment by digama0** [comment]
Fixed in https://github.com/metamath/set.mm/commit/44f25a2e2deed9337e7afb9929298a53b4f4a51c
