### ISSUE TITLE
Changing the definition of proper substitution

### ISSUE THREAD

**Issue by benjub** [metamath/set.mm#3003]
I would like to change the definition of proper substitution https://us.metamath.org/mpeuni/df-sb.html to the definition https://us.metamath.org/mpeuni/df-ssb.html.  Not right now, since there is still some work to do in my mathbox, but I'm posting now to give a heads up and hear opinions.  The main motivation is to allow a finer study of dependencies on the object-redundant axioms ax-10, ..., ax-13.

Of course, these two definitions are equivalent over {ax-mp, ax-gen, ax-1, ..., ax-13}, but they are not equivalent over {ax-mp, ax-gen, ax-1, ..., ax-7} (of course, axioms ax-8, ax-9 do not play any role here).  If one is in {ax-mp, ax-gen, ax-1, ..., ax-7}, then df-ssb is closer to our conception of proper substitution than df-sb, as show the more elementary theorems following df-ssb in my mathbox, e.g. https://us.metamath.org/mpeuni/bj-ssbim.html, https://us.metamath.org/mpeuni/bj-alsb.html, https://us.metamath.org/mpeuni/bj-ssbequ.html among many others (whereas their counterparts using df-sb require extra axioms among ax-10, ..., ax-13).  There are further comments on the df-ssb page.

This definition change is in the same spirit as the definition change for the nonfreeness predicate https://us.metamath.org/mpeuni/df-nf.html. It accompanies the ongoing effort to reduce axiom dependencies, with many contributors: lately, mainly Wolf and I, but this was already the case with Norm and others since long before I even knew Metamath.  I found that post on the discussion group about df-nf: https://groups.google.com/g/metamath/c/Ovxv2aXJOIM and among the latest PRs related to this are @wlammen's #2997 and #2989 (see also the discussions at #2977 and #2719).  There are also many theorems avoiding ax-13 in my mathbox.

**Comment by digama0** [comment]
This is already the definition I use in MM0: https://github.com/digama0/mm0/blob/45e06c7f95293e974bebd66350c9c45ca304a9a3/examples/peano.mm0#L107-L113 . (This is necessary since you can't play the same tricks with bundling which presumably correspond to using additional axioms in set.mm.) So you won't hear any complaints from me.

**Comment by david-a-wheeler** [comment]
@benjub - that plan makes sense. I would ask that you prove that the new definition is equivalent to the old one for {ax-mp, ax-gen, ax-1, ..., ax-13}. I suspect you were already going to do that :-).

**Comment by wlammen** [comment]
The only downside I see is that [https://us.metamath.org/mpeuni/sb56.html](https://us.metamath.org/mpeuni/sb56.html) is now based on ax-11 (instead of ax-10 and ax-12).  While this is possibly acceptable for this particular theorem, others proved from it will have ax-11 additionally in their axiom footprint.   Its a pity that I explicitly removed ax-13 from sbnv, only to have it replaced with ax-11 now. As far as I am concerned, I can live with it.

**Comment by benjub** [comment]
> The only downside I see is that https://us.metamath.org/mpeuni/sb56.html is now based on ax-11 (instead of ax-10 and ax-12). While this is possibly acceptable for this particular theorem, others proved from it will have ax-11 additionally in their axiom footprint. Its a pity that I explicitly removed ax-13 from sbnv, only to have it replaced with ax-11 now. As far as I am concerned, I can live with it.

I don't understand. Currently, https://us.metamath.org/mpeuni/sb56.html depends on ax-10, ax-12 and it does not depend on df-sb, so the definition change will not affect that. Am I missing something ?

**Comment by wlammen** [comment]
It was sb6 vs. bj-ssb1 that triggered my comment, not sb56.  In fact I was very busy at work, and used a 5-min break to skim through the theorems in your mathbox.  If sbnv was proven with the pair bj-ssb1/sb56 you would run into my problem.  This is an example, there might be ways around it, if you look closer.  I can't tell without investigation, but that will have to wait until weekend.  Sorry for my quick reply, but I didn't want to appear uninterested.

**Comment by wlammen** [comment]
df-sb and df-ssb have both advantages over the other in certain respects, so there is no clear winner.  In my profession we let the user decide in such situations.  (S)He sets up her/his profile to her/his liking, and the program follows suit.  Translated to Metamath this means, substitution would be based on some independent, dedicated axioms, and these axioms are in turn proven from both df-sb and df-ssb.  A similar approach was implemented with numbers, based on own axioms, that are in turn somehow embedded in set theory.

I'd like to adapt a configuration file to my personal preferences, and create a web page suite based on my decisions.  I am not sure whether Metamath supports such an operation natively,  but a simple solution could be a shell script reacting on a kind of #ifdef #else #endif tags strewn in as comments, and disabling parts of it as the 'macro' values tell to do.  The master set.mm file has to support all variants, of course, and maintain the above mentioned dedicated axiom scheme.

If this solution is too complex, or in other ways not really supported, I can live with any choice here.

**Comment by benjub** [comment]
Closing as implemented by #3283.
