### ISSUE TITLE
Automatic formatting + discouraged

### ISSUE THREAD

**Issue by icecream17** [metamath/set.mm#3041]
It would be nice to do formatting + discouraged automatically.

It is possible to make a workflow to edit files as shown in various bots and  https://github.com/icecream17/chesstree/blob/a7dea3e8c1cb1ef8b83e79380cd3124518418b4d/.github/workflows/python-app.yml

(Since there are many compilation files etc, the `git add --all` in my link should probably be replaced with only committing `discouraged`, `iset-discouraged`, `iset.mm`, and `set.mm`. Since this would be for pull_requests, [`github.head_ref` would be used instead](https://github.com/ad-m/github-push-action))

**Comment by benjub** [comment]
Related to #2381

**Comment by tirix** [comment]
#2381 is about formatting. It would be nice if this was automatic. Could that be added to the workflow as in the example provided, @david-a-wheeler ?

About regenerating the `discouraged` file automatically, I think this might ruin the purpose of the file. It was created to find out whether discouraged theorems have been newly used. There are two cases:
- either it is a legit special case, and the user has to acknowledge that by regenerating the "discouraged" file,
- or it is a mistake, and the proofs have to be changed before being submitted.

Always regenerating the file would amount to just remove the check.

**Comment by benjub** [comment]
At least, the regeneration of the discouraged file could be faster. This is described in https://github.com/metamath/metamath-exe/issues/12

**Comment by tirix** [comment]
I've written PR david-a-wheeler/metamath-knife#96 for adding to metamath-knife a function to regenerate the discouraged file.
It appears to run in ~2s.

**Comment by icecream17** [comment]
I think this is then supersumed by #2381 since the discouraged part is resolved
