### ISSUE TITLE
Malfunctioning Latexdefs left to fix

### ISSUE THREAD

**Issue by GinoGiotto** [metamath/set.mm#3091]
Checks 2,3,4,5,6,7,8,10,11,12,14 are fixed in #3099
Checks 1, 9, 13 are fixed in https://github.com/metamath/metamath-exe/pull/133

This is a list of all faulty latex substitutions that I found + some minor questions I have. Hopefully no more errors will be produced by any latexdef after these are fixed:

**In set.mm:**
- [x] Token: <code>[. </code> Tex: <code>\underaccent{\dot}{[}</code>
Token: <code>]. </code> Tex: <code>\underaccent{\dot}{]}</code>
These need <code>\usepackage{accents}</code> to work

- [x] Token: <code>RPrime</code> Tex: <code>\mathsc{RPrime}</code>
Token: <code>UFD</code> Tex: <code>\mathsc{UFD}</code>
It seems that <code>\mathsc</code> doesn't exist, maybe it was meant to be <code>\textsc</code> or <code>\mathscr</code>?

- [x] Token: <code>_Ind</code> Tex: <code>\mathsfbf{1}</code>
Gives the error <code>undefined control sequence. \end{align}</code>, I don't know how to fix this one

- [x] Token: <code>log_</code> Tex: <code>log_</code> Already addressed [here](https://github.com/metamath/set.mm/issues/3079#issuecomment-1454942780)

- [x] Token : <code>(|</code> Tex: <code>\lParen</code>
 Token : <code>|)</code> Tex: <code>\rParen</code>
They where probably meant to be  <code>\lparen</code> and <code>\rparen</code> which are commands of the <code>mathtools</code> package

- [x] Token: <code>iota</code> Tex: <code>\mathrm{\rotatebox[origin=C]{180}{$\iota$}}</code>
Token: <code>iota_</code> Tex: <code>\underline{\mathrm{\rotatebox[origin=C]{180}{$\iota$}}}</code>
Token: <code>iota'</code> Tex: <code>\mathrm{\rotatebox[origin=C]{180}{$\iota$}}\textquoteright</code>
These latexdefs contain <code>\rotatebox</code> and <code>\iota</code> which should be replaced https://github.com/metamath/metamath-exe/pull/131

- [x] Token: <code>Xs_</code> Tex: <code>\text{\large\boldmath$\times$}\_s</code>
Token: <code>X_</code> Tex: <code>\text{\large\boldmath$\times$}</code>
I believe these ones should be replaced with <code>\large{\pmb{\times}}</code> ? https://github.com/metamath/set.mm/pull/3074#discussion_r1122252644 @benjub 

- [x] Token: <code>Singleton</code> Tex:  <code>Singleton</code>
Token: <code>PtDf</code> Tex: <code>PtDf</code>
Token: <code>RR3</code> Tex: <code>RR3</code>
Token: <code>plane3</code> Tex: <code>plane3</code>
Token: <code>line3</code> Tex: <code>line3</code>
Token: <code>Reflexive</code> Tex: <code>Reflexive</code>
Token: <code>Irreflexive</code> Tex: <code>Irreflexive</code>
Token: <code>class-o</code> Tex: <code>class-o</code>
Token: <code>class-n</code> Tex: <code>class-n</code>
Were these ones meant to be something like <code>\mathrm{Singleton}</code> or <code>\text{Singleton}</code> or they are good as they are?

**In iset.mm:**
- [x] Token: <code>[. </code> Tex: <code>\underaccent{\dot}{[}</code>
 Token: <code>]. </code> Tex: <code>\underaccent{\dot}{]}</code>
Same as above

- [x] Token: <code>iota</code> Tex: <code>\mathrm{\rotatebox[origin=C]{180}{$\iota$}}</code>
Token: <code>iota_</code> Tex: <code>\underline{\mathrm{\rotatebox[origin=C]{180}{$\iota$}}}</code>
Same as above

- [x] Token: <code>Xs_</code> Tex: <code>\text{\large\boldmath$\times$}\_s</code>
Token: <code>X_</code> Tex: <code>\text{\large\boldmath$\times$}</code>
Same as above

- [x] <code>latexdef ";" as "\mathrm{;}";</code> why not just <code>;</code> here?

**In nf.mm:**
- [x] Token: <code>[. </code> Tex: <code>\underaccent{\dot}{[}</code>
Token: <code>]. </code> Tex: <code>\underaccent{\dot}{]}</code>
Same as above

- [x] Token: <code>iota</code> Tex: <code>\mathrm{\rotatebox[origin=C]{180}{$\iota$}}</code>
Same as above

**In hol.mm:**

Not sure if this is wrong, but this one just produces a whitespace. It's actually called "separator", so it was probably meant to be like that, but I wanted to ask for confermation:
<pre>htmldef "." as " ";
althtmldef "." as ' ';
latexdef "." as "\,";</pre> 

Sometimes there are some alphabetical letters that are defined in <code>$c</code> and <code>$f</code>, but never used, and sometimes there are some alphabetical letters that are missing completely, so what is the policy? It's preferred to define all letters anyway, or the unused ones shoud be removed?

If someone can provide solutions for the mentioned latexdefs I will make a pull request with the fixes.

**Comment by benjub** [comment]
* yes, add `\usepackage{accents}` as in my PR https://github.com/metamath/metamath-exe/pull/131
* `\textsc` was meant (it works in both text and math modes)
* `\pmb{1}`
* `\pmb{\bigtimes}_\text{s}` `\pmb{\bigtimes}`
* `\text{\riota}` `\underline{\text\riota}` `\text\riota'` now that `phonetic` is loaded
* yes, `\mathrm{;}` is the same as `;`
* `\mathopen{(\!|}` and `\mathclose{|\!)}` (rather than loading stmaryrd which redefines many commands)
* yes, use `\mathrm` for the series beginning with `Singleton`

**Comment by digama0** [comment]
I think package definitions (beyond the basics) should be in a $t command, they are obviously database-sensitive.

**Comment by benjub** [comment]
> I think package definitions (beyond the basics) should be in a $t command, they are obviously database-sensitive.

Yes, this is why I refrained from using stmaryrd and I recently updated https://us.metamath.org/mpeuni/conventions.html to advise using only "standard" packages.

Do you think that `accents` should not be in it ?

**Comment by digama0** [comment]
I don't have much of an opinion on which packages should be in the baseline, but I would tend toward things that are required for the framework itself plus things that almost every database would need (like anything needed to support e.g. variable names).

**Comment by tirix** [comment]
Having the prelude in the database would allow it to be shared between all tools, and not hardcoded in each one (like `metamath-exe` and `latex_collector.py`).

**Comment by GinoGiotto** [comment]
Are these two TeX definitions in <code>hol.mm</code>:
<code>latexdef "1-1" as "text{ 1-1 }"</code>
<code>latexdef "onto" as "text{ onto }"</code> 

the same as:
<code>latexdef "-1-1->" as "\overset{\mathrm{1-1}}{\longrightarrow}"</code>
<code>latexdef "-onto->" as "\underset{\mathrm{onto}}{\longrightarrow}"</code>

Which are in the other databases? (if yes I can replace them)

**Comment by tirix** [comment]
See below, it looks like it is used in a prefix notation (as in `1-1 f`), so it would be better to just update it as `\mathrm{1-1}`
```
  ax-inf $a |- T. |= ( ? \ f : ( ind -> ind ) .
    [ ( 1-1 f : ( ind -> ind ) ) /\ ( ~ ( onto f : ( ind -> ind ) ) ) ] ) $.
```

**Comment by david-a-wheeler** [comment]
Once all latexdefs are fixed, I'd like to modify the CI pipeline to test things (so they *stay* fixed). An early draft is in #3100.

**Comment by david-a-wheeler** [comment]
We're *really* close to being able to generate a LaTeX list of symbols in set.mm without serious issues. We are getting a warning though:

> LaTeX Warning: Command \L invalid in math mode on input line 982.

Can our TeX-ers figure out the cause and fix that? LaTeX runs to completion without fixing that, but I don't like the idea of having an invalid command in a generated TeX file.

**Comment by benjub** [comment]
> Can our TeX-ers figure out the cause and fix that?

See my anwer at #3100

**Comment by GinoGiotto** [comment]
All tasks are now done, if I receive confirmation that the last two questions don't need any fix, I will close this issue.

>In hol.mm:
>
>Not sure if this is wrong, but this one just produces a whitespace. It's actually called "separator", so it was probably meant to be like that, but I wanted to ask for confirmation:
>
><pre>htmldef "." as " ";
>althtmldef "." as ' ';
>latexdef "." as "\,";</pre>

>Sometimes there are some alphabetical letters that are defined in $c and $f, but never used, and sometimes there are some alphabetical letters that are missing completely, so what is the policy? It's preferred to define all letters anyway, or the unused ones shoud be removed?

**Comment by benjub** [comment]
The author of hol.mm is @digama0 so he may have a word on this.
As for me, I'm fine with anything, but I'd remove all unused $f $c and $v statements.
(by the way: it's "confirmation")

**Comment by GinoGiotto** [comment]
> (by the way: it's "confirmation")

Oops, thanks for noticing :-)

**Comment by digama0** [comment]
I'm not sure what the question is. That token is supposed to produce a whitespace, because without it you get letters running together in `\ x : A . x` appearing something like $\lambda\ x:Ax$. (Note that set.mm has a [special case hack](https://github.com/metamath/metamath-exe/blob/d68c417/src/mmwtex.c#L4844-L4872) in metamath-exe to insert a space between $A$ and $\varphi$ in $\forall x\in A\ \varphi$; hol.mm would need a similar hack but I don't like these kinds of hacks generally and want to move it all to $j comments or the like.)

I don't think we should prune unused $f declarations, as this makes it annoying to end-extend the database when there aren't enough variables declared.

**Comment by GinoGiotto** [comment]
> I'm not sure what the question is. That token is supposed to produce a whitespace, because without it you get letters running together in `\ x : A . x` appearing something like λ x:Ax. (Note that set.mm has a [special case hack](https://github.com/metamath/metamath-exe/blob/d68c417/src/mmwtex.c#L4844-L4872) in metamath-exe to insert a space between A and φ in ∀x∈A φ; hol.mm would need a similar hack but I don't like these kinds of hacks generally and want to move it all to $j comments or the like.)
> 
> I don't think we should prune unused $f declarations, as this makes it annoying to end-extend the database when there aren't enough variables declared.

Good for me, I'll consider this the final word
