### ISSUE TITLE
clean-up/unification of ~reuxfr3d/~reuxfr2d

### ISSUE THREAD

**Issue by avekens** [metamath/set.mm#3148]
After PR #3142 is merged, ~reuxfr3d/~reuxfr2d should be cleaned up/unified as mentioned in the review remarks, because the proof of ~reuxfr2d consists essentially only of ~reuxfr3d. So ~reuxfr2d and ~reuxfr3d seem to be a kind of duplicates.

**Comment by benjub** [comment]
Closing as fixed by #3149.
