### ISSUE TITLE
Add more T. (true) and F. (false) theorems to iset.mm

### ISSUE THREAD

**Issue by jkingdon** [metamath/set.mm#316]
I ran `search * 'T.'` and `search * 'F.'` in `set.mm` and found a lot of theorems which are not in `iset.mm` yet. The vast majority hold intuitionistically, and the proofs probably aren't especially hard. In some cases the proofs from `set.mm` will work unmodified.

This would be a good beginner project for someone who is learning logic or metamath.

**Comment by david-a-wheeler** [comment]
Well, I'm not *exactly* a beginner, but I'm definitely a beginner at intuitionistic logic.  Besides, it looked like fun, so I did a few.  It turns out that many of the same theorems work just fine unchanged, so I just copied them from set.mm with credit retained.  See #337.

**Comment by jkingdon** [comment]
@david-a-wheeler Now that #337 is merged, are we ready to close this issue? I didn't see any other theorems which caught my eye, but if you are aware of some, we can list them here.

**Comment by david-a-wheeler** [comment]
I want to include exclusive or and nand. In particular, exclusive or is the basis of some ancient propositional logic that I would really like to prove is also valid in intuitionistic logic. However, I'm not sure I understand how exactly to represent exclusive or in intuitionistic logic. It appears to me that several different expressions for exclusive or that are exactly the same in classical logic are not the same in intuitionistic logic, and I do not understand which one is "correct" in intuitionistic logic. I started looking for sources about this, but I am probably looking in the wrong places. Any suggestions?

**Comment by jkingdon** [comment]
There is a section about exclusive or at http://us2.metamath.org:88/ileuni/mmtheorems19.html#mm1847s but there is more that could be done here.

See https://github.com/metamath/set.mm/pull/236 which includes a web page link which maybe should be in our bibliography. That web page also mentions existential uniqueness in the same breath as exclusive or, and no one has even started on existential uniqueness in iset.mm.

**Comment by nmegill** [comment]
A Google search for "exclusive or in intuitionistic logic" returns ileuni/xor.html as the first hit, which isn't helpful, but some way down the page it shows https://ncatlab.org/nlab/show/exclusive+disjunction that comments on it, saying that some classical equivalents aren't equivalent intuitionistically but not committing to which one is the right one.  Based on the usage in English, I might go for "p or q but not both" expressed as "(p or q) and not (p and q)", which isn't mentioned there, and I don't know if it is equivalent to any of theirs.

**Comment by david-a-wheeler** [comment]
Thanks for the reference!

That page may not "commit" to one, but it does give a big hint.  It notes 3 possible forms:

1. ¬(p⇔q)
2. (p∨q)∧(¬p∨¬q)
3. (p∧¬q)∨(¬p∧q)

It then says that "These are all equivalent in classical logic. In intuitionistic logic, (2,3) are equivalent but (1) is weaker; (2,3) give the usual meaning in constructive mathematics."

If that's our only source for information, I would recommend definition #3.  I think we should use the "usual meaning" (and intuitionistic logic is a kind of constructive mathematics).  I think ¬(p⇔q) is pretty short, and doesn't really cry out for an abbreviation.  In addition, definition #3 appeals to me as the "intuitively obvious meaning" of exclusive-or; that's an argument that doesn't really count for much, but it makes me happy :-).

It's not a very authoritative source.  If there's no better source, then we should use it, but is there any better/more authoritative source for the definition of "exclusive or" in intuitionistic logic?

**Comment by jkingdon** [comment]
@nmegill Pretty sure that `(p∨q)∧(¬p∨¬q)` implies `(p or q) and not (p and q)` but not the converse. See http://us2.metamath.org:88/ileuni/ianor.html

**Comment by david-a-wheeler** [comment]
I think we can close this issue.  iset.mm now has exclusive-or and the relevant truth table entries for it.  The section heading doesn't mention exclusive or; I'll create a little branch to fix that.

There's no Sheffer stroke (nand) truth table entries, but that would require Sheffer stroke to be defined first in iset.mm...!
