### ISSUE TITLE
Minimize proofs using ~el2v

### ISSUE THREAD

**Issue by avekens** [metamath/set.mm#3171]
There are (currently) 34 proofs which can be minimized using ~el2v (recently moved from mathboxes to main).

This minimization should be performed after the current minimization activity (see PR #3127) is finished.

**Comment by GinoGiotto** [comment]
It depends where these 34 proofs are placed in the set.mm database. If they all appear earlier than `dedekind` then they are not going to generate conflicts with my PRs (assuming your branch is updated).

**Comment by GinoGiotto** [comment]
The current minimization activity #3127 is finished. You can start committing your minimizations @avekens.

**Comment by GinoGiotto** [comment]
I think we can close this issue now, since https://github.com/metamath/set.mm/pull/3258 is merged (I don't have the permissions to do it).

**Comment by avekens** [comment]
Done with #3258.
