### ISSUE TITLE
Remove depedencies from ax-13

### ISSUE THREAD

**Issue by GinoGiotto** [metamath/set.mm#3183]
With the `/MAY_GROW` option is possible to use the minimizer as a sort of axiom usage minimizer. For most axioms this tool provides little success, but I found a significant difference for `ax-13`. With a scan of 5000 theorems in main I found 267 that can be proven without it, also without adding any disjoint variable conditions. The only tradeoff is that some proof are a bit longer, but it's usually a few bytes.

The question is: Are you interested in those proofs?

**Comment by jkingdon** [comment]
I think "We prefer proofs that depend on fewer and/or weaker axioms, even if the proofs are longer." from https://us.metamath.org/mpeuni/conventions.html is pretty clear on this point. I suppose if it is more than a few bytes there might sometimes be a reason for an ALT proof to show both ways but we mostly haven't done that (for example https://us.metamath.org/mpeuni/sbth.html mentions the Axiom of Infinity or the Axiom of Choice as not being used but does not show alternative proofs which use one or both of those axioms).

**Comment by david-a-wheeler** [comment]
Short answer: Yes.

Longer answer: As @jkingdon noted, if the new proofs are significantly longer, we should keep the older proofs as ALT forms. But only if they're a lot longer.

I'm surprised no one has mentioned this before. We in general try to reduce axiom usage. Good idea!

**Comment by GinoGiotto** [comment]
I looked into this more clearly and I think I understand what happened:

* The minimizer edited around 450 proofs out of the 5000 scanned.
* Among these 450 proofs there are 3 that accidentally dropped `ax-13`.
* It happens that one of those 3, which is called `dfss2f`, is used by many following theorems, so all other 264 ones dropped `ax-13` without having their proof edited!

In the end it's much simpler than I thought, it's sufficient to make a PR for 3 theorems only to automatically reduce axiom usage of the others. I guess that's the reason why nobody mentioned it: diminishing axiom usage with this method looks like a rare occurrence, I was just lucky enough to spot a very "influential" theorem. Anyway it was an interesting test to make.

**Comment by david-a-wheeler** [comment]
One of the reasons we prefer the "main" proof to have fewer axioms is to cause later proofs to possibly use fewer axioms. I'm surprised by the *extent* in this case - but also delighted :-).

**Comment by benjub** [comment]
For more info on this phenomenon, see also the discussion on the mailing list from 2019: https://groups.google.com/g/metamath/c/1wi1s6qBYqY/m/FPkPsd5oAwAJ especially the part "This is because these hundred-or-so technical lemmas are mainly used later with dummy variables".

**Comment by GinoGiotto** [comment]
My question has been answered and the anticipated PR https://github.com/metamath/set.mm/pull/3189 has been merged, so I think I can close this issue now.

Thanks for your info and partecipation.
