### ISSUE TITLE
Add triangle equality minimum theorems to iset.mm

### ISSUE THREAD

**Issue by jkingdon** [metamath/set.mm#3184]
We would like to prove:

```
    stdbdmet.1 $e |- D = ( x e. X , y e. X |->
      inf ( { ( x C y ) , R } , RR* , < ) ) $.

    $( The standard bounded metric is an extended metric given an extended
       metric and a positive extended real cutoff.  (Contributed by Mario
       Carneiro, 26-Aug-2015.)  (Revised by Jim Kingdon, 9-May-2023.) $)
    bdxmet $p |- ( ( C e. ( *Met ` X ) /\ R e. RR* /\ 0 < R ) ->
        D e. ( *Met ` X ) ) $=
      ? $.
```

There are a variety of steps in intuitionizing the set.mm proof but
this issue is about one in particular:

```
|- (  (  ( R e. RR* /\ 0 < R )
    /\ ( a e. ( 0 [,] +oo ) /\ b e. ( 0 [,] +oo ) ) )
  -> inf ( { ( a +e b ) , R } , RR* , < ) <_
    ( inf ( { a , R } , RR* , < ) +e inf ( { b , R } , RR* , < ) ) )
```

How can we prove this? I'm assuming that the real number case is the hard part and it would readily be expanded to extended reals if we had:

```
  bdtri $p |- ( ( ( A e. RR /\ 0 <_ A ) /\ ( B e. RR /\ 0 <_ B ) /\ C e. RR+ )
      -> inf ( { ( A + B ) , C } , RR , < ) <_ ( inf ( { A , C } , RR , < )
      + inf ( { B , C } , RR , < ) ) ) $=
    ? $.
```

One possible tactic is to apply `minabs` from #3182 and then (based on some rearrangements not shown here which I haven't proved all of but which I think should be correct) the problem reduces to :

```
|- (  (  ( A e. RR /\ 0 <_ A ) /\ ( B e. RR /\ 0 <_ B ) /\ C e. RR+ )
  -> ( ( abs ` ( A - C ) ) + ( abs ` ( B - C ) ) ) <_  ( C + ( abs ` ( ( A + B ) - C ) ) )
  )
```

However, whether that is any easier than the original problem is not clear to me.

**Comment by icecream17** [comment]
I think I proved it
```
abstri with |AB| = AB
  |AB - AC - BC + CC| <_ AB + |- AC - BC + CC|
  |AB - AC - BC + CC| <_ AB + |AC + BC - CC|
  |AB - AC - BC + CC| <_ |AC + BC - CC| + AB
plenty of transformation steps
  |(A - C)(B - C)|              <_ C|A + B - C| + AB
absmul
  |A - C||B - C|                <_ C|A + B - C| + AB
  2|A - C||B - C|               <_ 2C| A + B - C | + 2AB
lots of transformation steps [1]
  (A - C)^2 + 2|A - C||B - C| + (B - C)^2 <_ C^2 + 2C| A + B - C | + (A + B - C)^2
more transformation steps (breq12)
  (| A - C | + | B - C |)^2               <_ (C + | A + B - C |)^2
le2sq
  | A - C | + | B - C |                   <_ C + | A + B - C |
```

lots of transformation steps [1] (bottom to top for the actual proof) [wolfram alpha verification](https://wolframalpha.com/input?i2d=true&i=Power%5B%5C%2840%29A+-+C%5C%2841%29%2C2%5D+%2B+Power%5B%5C%2840%29B+-+C%5C%2841%29%2C2%5D+%2B+2AB+%3D+Power%5BC%2C2%5D+%2B+Power%5B%5C%2840%29A+%2B+B+-+C%5C%2841%29%2C2%5D)
```
(A - C)^2 + (B - C)^2         ??? C^2 + (A + B - C)^2
AA - 2AC + CC + BB - 2BC + CC ??? CC + AA + 2AB - 2AC + BB - 2BC + CC
<everything was canceled>     ??? 2AB
```

**Comment by jkingdon** [comment]
Ooh nice. As far as I could tell from a semi careful reading that looks correct. Will try formalizing when I get a chance (probably the next day or few).

**Comment by jkingdon** [comment]
> I think I proved it

I totally have the best collaborators.

This proof formalizes without much trouble and the https://github.com/jkingdon/set.mm/tree/bdxmet branch now has a proof for:

```
  $( Lemma for ~ bdtri .  (Contributed by Steven Nguyen and Jim Kingdon,
     17-May-2023.) $)
  bdtrilem $p |- ( ( ( A e. RR /\ 0 <_ A ) /\ ( B e. RR /\ 0 <_ B )
    /\ C e. RR+ ) -> ( ( abs ` ( A - C ) ) + ( abs ` ( B - C ) ) ) <_
      ( C + ( abs ` ( ( A + B ) - C ) ) ) ) $=
```

I'll turn that into a pull request once I have finished using this to prove the `bdxmet` theorem shown at the top of this issue (which is going smoothly, no signs of any problems so far and should be relatively close).
