### ISSUE TITLE
Proposal: be able to declare forbidden axioms for a proof

### ISSUE THREAD

**Issue by jkingdon** [metamath/set.mm#3250]
Many theorems have comments saying that they are proved without certain axioms, for example https://us.metamath.org/mpeuni/sbth.html says that it avoids https://us.metamath.org/mpeuni/ax-inf.html and https://us.metamath.org/mpeuni/ax-ac.html , and https://us.metamath.org/mpeuni/equsb1v.html says that it avoids https://us.metamath.org/mpeuni/ax-13.html

However, we have no way to check that such claims remain true, despite this being easy to automate in principle. In the past we have had multiple problems where axiom usage gets accidentally re-introduced and although our mechanisms to prevent this have gotten better, they aren't perfect and in some cases are more manual than needed.

Proposal:

* Add a `$j usage` directive, for example for these examples it would be:
```
$j usage 'sbth' avoids 'ax-inf' 'ax-ac';
$j usage 'equsb1v' avoids 'ax-13';
```

* Although this would probably generally be used for axioms, I had in mind saying that any usage of the specified statement, when traced back recursively, would be an error. This would be well defined for theorems as well as axioms. Although I don't have a concrete example of using it for theorems I am thinking of something like "this is an elementary proof which does not require Bézout's identity" (or something sorta like that).

* We would need a tool to check this. I assume it would look a bit like https://github.com/david-a-wheeler/metamath-knife/pull/107 (with various changes to parse the $j comments and so on, as well as presumably being a crate on top of the metamath-knife library crate since we are talking about breaking apart metamath-knife like that).

* We'd want the set.mm automated tests to download this tool and run it, which should be fairly similar to the existing checks.

Open questions:

* I'm not attached to this syntax, perhaps people have ideas about syntax
* Of course someone has to write the checker. I might be volunteering especially if the crate separation in metamath-knife is done first, but if someone else gets to it before me that's great too.

**Comment by digama0** [comment]
SGTM :+1:

**Comment by tirix** [comment]
This could also be useful to confirm that certain proofs do not require the axiom of choice, which we also have later on.
I don't expect the implementation to be very complicated, since we already have several bits and pieces for that.

The syntax seems sensible, so I think we can already add the `$j usage` tag in the database, and implement the check later.

**Comment by jkingdon** [comment]
> I don't expect the implementation to be very complicated, since we already have several bits and pieces for that.

Perhaps someone who knows metamath-knife (if so, that wouldn't be me) will take it on.

> The syntax seems sensible, so I think we can already add the `$j usage` tag in the database, and implement the check later.

Although we have a long history of adding `$j` comments thinking we'll write software to use them, and then not getting around to writing that software, I guess in this case I'll risk it - see #3251

**Comment by wlammen** [comment]
It would be nice, if you could span such a constraint across a block of theorems (don't use ax-11 from here to there).  In the predicate section, related theorems often share such constraints.

**Comment by jkingdon** [comment]
> It would be nice, if you could span such a constraint across a block of theorems (don't use ax-11 from here to there). In the predicate section, related theorems often share such constraints.

I thought about being able to name a constraint and reuse it, for example `aux-logic` could be `ax-10 ax-11 ax-12 ax-13`, `choice` would be `ax-ac ax-ac2`, `infinity` would be `ax-inf ax-inf2` etc. I guess to my eyes it seemed like overkill.

Getting a similar effect by some sort of 'begin constraint" and "end constraint" scoping has similar overkill issues in my mind and also seems pretty error-prone as theorems are modified or moved.

**Comment by wlammen** [comment]
In the end you have to provide a "negative" list of axioms, i. e. all those NOT appearing in the axioms list.  In predicate logic this covers all from ax-gen to ax-13.  You can simply run through some of predicate logic to learn, this is a LOT of information.   It's maybe easier to group theorems according to their axiom usage, so the from-to commands cover already most of it.

**Comment by wlammen** [comment]
If you want to automatically check that axiom usage has not widened in a shortening/revision process, it is perhaps a good idea to compare the OLD with the new version in this regard.  This helps at least when something was manually added, as part of the everyday business.  In case of a huge minimization process like this #3127 you need a bit more.

**Comment by jkingdon** [comment]
I think the only remaining piece is to merge https://github.com/david-a-wheeler/metamath-knife/pull/118 and write the script so we run it as part of the pull request checks in the set.mm repository.

But we seem to be getting close.

**Comment by tirix** [comment]
> I think the only remaining piece is to merge [david-a-wheeler/metamath-knife#118](https://github.com/david-a-wheeler/metamath-knife/pull/118) and write the script so we run it as part of the pull request checks in the set.mm repository.

Merge is done!
