### ISSUE TITLE
Two problems related to equality of certain functions in iset.mm

### ISSUE THREAD

**Issue by jkingdon** [metamath/set.mm#3286]
These are two problems in which showing two functions to be equal might seem to rely on unavailable operations (real trichotomy or an analogue for ` NN+oo `), but which are nonetheless possible.  I learned about both from Martin Escardo at the links shown below.

The first problem is stated at https://mathstodon.xyz/@MartinEscardo/110685126712603913 . It feels like maybe an easy extension of https://us.metamath.org/ileuni/nninfall.html 

```
    nninffg.f $e |- ( ph -> F : NN+oo --> NN ) $.
    nninffg.g $e |- ( ph -> G : NN+oo --> NN ) $.
    nninffg.oo $e |- ( ph
      -> ( F ` ( x e. _om |-> 1o ) ) = ( G ` ( x e. _om |-> 1o ) ) ) $.
    nninffg.n $e |- ( ph -> A. n e. _om
      ( F ` ( i e. _om |-> if ( i e. n , 1o , (/) ) ) )
      = ( G ` ( i e. _om |-> if ( i e. n , 1o , (/) ) ) ) ) $.
    $( Equality of two functions on ` NN+oo ` which agree at every
       integer and at the point at infinity.  (Contributed by
       Jim Kingdon, 9-Jul-2023.) $)
    nninffg $p |- ( ph -> A. x e. NN+oo ( F ` x ) = ( G ` x ) ) $=
      ? $.
```

The second problem is perhaps even more striking because it is in terms of real numbers. It is stated at https://mathstodon.xyz/@MartinEscardo/110685074921103237

```
    refg.f $e |- ( ph -> F : RR --> RR ) $.
    refg.g $e |- ( ph -> G : RR --> RR ) $.
    refg.lt0 $e |- ( ph
      -> A. x e. RR ( x < 0 -> ( F ` x ) = ( G ` x ) ) ) $.
    refg.gt0 $e |- ( ph
      -> A. x e. RR ( 0 < x -> ( F ` x ) = ( G ` x ) ) ) $.
    refg.0 $e |- ( ph -> ( F ` 0 ) = ( G ` 0 ) ) $.
    $( Equality of two real functions which agree at negative
       numbers, positive numbers, and zero.  This holds even
       without real trichotomy.  (Contributed by
       Jim Kingdon, 9-Jul-2023.) $)
    refg $p |- ( ph -> A. x e. RR ( F ` x ) = ( G ` x ) ) $=
      ? $.
```

**Comment by tirix** [comment]
Interesting! It would really be nice to have those proofs in `iset.mm`!

**Comment by jkingdon** [comment]
> Interesting! It would really be nice to have those proofs in `iset.mm`!

Feel free to give it a try. I don't expect to get to it until at least after a few other things. Even then I'm not sure I know how to prove them (although there should be inspirations from https://us.metamath.org/ileuni/nninfall.html and probably the TypeTypology repo if one can find the right part and understand the notation).
