### ISSUE TITLE
Can we confirm or refute "The [Schroeder-Bernstein] theorem can be proved more easily if we allow AC"?

### ISSUE THREAD

**Issue by jkingdon** [metamath/set.mm#3325]
The genesis of this issue is https://mathstodon.xyz/@andrejbauer/110792965005628884 which says "I don't know, the [proof of Schroeder-Bernstein] with excluded middle isn't particularly involved. I am not even aware of one that uses choice directly."

The context, for metamath, is the statement "The theorem can be proved more easily if we allow AC" at https://us.metamath.org/mpeuni/sbth.html 

I attempted to do a literature search of sorts and I don't think any of the proofs I found use choice, but I'm not sure I know enough to be sure (either where to look or how to detect choice):

* [Cantor-Bernstein-Schröder Theorem](https://proofwiki.org/wiki/Cantor-Bernstein-Schr%C3%B6der_Theorem) in proofwiki (6 proofs)
* [Knaster–Tarski theorem](https://en.wikipedia.org/wiki/Knaster%E2%80%93Tarski_theorem) in Wikipedia ("The Knaster–Tarski theorem can be used to give a simple proof of the Cantor–Bernstein–Schroeder theorem.")
* [Schröder–Bernstein theorem](https://en.wikipedia.org/wiki/Schr%C3%B6der%E2%80%93Bernstein_theorem) in Wikipedia

Norm must have had something in mind when he wrote that (assuming it was Norm and not someone who emailed him the text), but I'm not sure it will be easy to figure out what. Does anyone have a copy of Suppes (which Norm cited), and if so does it discuss choice? Of course "more easily" and "quite difficult" are hard to nail down, and this might just mean relative to other theorems which existed in set.mm in 1998 but even so are there even any proofs which use choice?

Interestingly, the comment about the axiom of choice was not there in 1998 when `sbth` was first added (see https://github.com/metamath/set.mm/blob/db5c4a1d938a13be1685998fb5e6cc088fb87810/set.mm ) but instead was added in e89b9b5780698853be9241a6de13b6ed60087cfe (that is to say, some time between 2001 and 2004).

**Comment by jkingdon** [comment]
Of course we could just revise the comment to say "there is a truly delightful proof of this via the axiom of choice, but this margin is too small to contain it".

**Comment by digama0** [comment]
I'm fairly sure the imagined proof goes along these lines: under AC, every set is equinumerous to an ordinal (its cardinality), and ordinals are totally ordered more or less by definition. There are still a few things to show after you reduce to cardinals, in particular that `A ~<_ B` implies `A C_ B` for cardinals, but they are a lot easier than the usual S-B proof.

If `A ~<_ B` and WLOG assuming `B C_ A` by ordinal trichotomy, then `A` is equinumerous to a subset `C C_ B`. By ordinal collapse there is an order isomorphism from `C` to an ordinal `D`, which implies `D C_ A`. But `A` is a cardinal and `D ~~ A`, so `D = C = B = A`, hence `A C_ B`.

**Comment by jkingdon** [comment]
The proof sketched by @digama0 would seem to also be the one described at https://mathoverflow.net/a/439000/489586 . Ah, and a closer read of the Wikipedia page https://en.wikipedia.org/wiki/Schr%C3%B6der%E2%80%93Bernstein_theorem shows "[Cantor] obtains it as an easy consequence of the linear order of cardinal numbers".

Given this, I think we should take this issue as being resolved if someone adds a `sbthALT` which formalizes this argument. Especially given the historical notes in the Wikipedia page, it would be helpful to have this formalized. And I haven't looked in great depth, but it would appear that set.mm already has most of the needed theorems regarding cardinals and ordinal trichotomy and the like.

**Comment by jkingdon** [comment]
So putting "it would appear that set.mm already has most of the needed theorems" into practice looks easy, but the hard part arrives if we are hoping to do this without circular reasoning, as `sbth` occurs in set.mm well before most of the theorems about cardinality, and a `show usage sbth/recursive` shows many of those theorems.

So there is a mathematical problem: is this usage essential?

And there is a purely organizational problem: how do we put this in the file and separate things which use sbth from those who do not? This is the kind of situation I had in mind when I suggested that `$j usage` could apply to a theorem as well as an axiom.

I suppose the simplest thing to do is just add the following and handwave over the circular reasoning issue.

```
  ${
    $d x y z w f g A $.  $d x y z w f g B $.
    $( Schroeder-Bernstein Theorem.  Although ~ sbth is the usual proof which
       does not use the axiom of choice, this is a proof using choice which is
       simpler (at least if one takes as given the needed theorems about
       cardinality).  (Contributed by Jim Kingdon, 1-Aug-2023.)
       (Proof modification is discouraged.)  (New usage is discouraged.) $)
    sbthac $p |- ( ( x ~<_ y /\ y ~<_ x ) -> x ~~ y ) $=
      ( cv cdom wbr cen ccrd cfv wceq wss eqss cdm wcel cvv numth3 elv carddom2
      wa wb mp2an anbi12i bitri carden el2v bitr3i biimpi ) ACZBCZDEZUHUGDEZRZU
      GUHFEZUKUGGHZUHGHZIZULUOUMUNJZUNUMJZRUKUMUNKUPUIUQUJUGGLZMZUHURMZUPUISUSA
      UGNOPZUTBUHNOPZUGUHQTUTUSUQUJSVBVAUHUGQTUAUBUOULSABUGUHNNUCUDUEUF $.
  $}
```

**Comment by digama0** [comment]
> So there is a mathematical problem: is this usage essential?

It's probably not essential, but I can believe that it would take a significant amount of reconstruction to eliminate it, much like the work you are doing now on iset.mm to eliminate ax-3 from many theorems that don't need it but transitively depend on theorems that do.

**Comment by jkingdon** [comment]
> It's probably not essential, but I can believe that it would take a significant amount of reconstruction to eliminate it, much like the work you are doing now on iset.mm to eliminate ax-3 from many theorems that don't need it but transitively depend on theorems that do.

Yeah, that's my guess too. You'd have to revamp much of the development of cardinals and there wouldn't really be much point to doing so other than this one demonstration.

Therefore, my thinking is that we should add sbthac as shown above, note that it does derive from sbth as currently arranged but still illustrates the idea of proving Schroeder-Bernstein from cardinal ordering, and revise the sbth comment accordingly. I can put that in pull request form unless there are other ideas of how to proceed.
