### ISSUE TITLE
Add metamath to lets-prove-leftpad

### ISSUE THREAD

**Issue by jkingdon** [metamath/set.mm#3344]
At https://github.com/hwayne/lets-prove-leftpad there is a collection of proofs for different proof systems which includes:

1. A definition of a `leftpad` function
2. Proof of three theorems about that function

I didn't take a super close look at how to do this in metamath but it seems like words over a set (df-word) would have most of what we need.

I guess the leftpad definition could be a hypothesis ("local definition") if we don't want to make it global.

**Comment by tirix** [comment]
Yes, words over a set is what we should use.

It seems that repository has a directory for each system, so maybe we could write a mini database importing `set.mm`, defining the `leftpad` function, and then proving the 3 theorems, which we could put there.

**Comment by jkingdon** [comment]
> It seems that repository has a directory for each system, so maybe we could write a mini database importing `set.mm`, defining the `leftpad` function, and then proving the 3 theorems, which we could put there.

I was thinking of adding the 3 theorems to set.mm and copy-paste them to the lets-prove-leftpad repo. But maybe a .mm file which imports set.mm is better.

**Comment by tirix** [comment]
My work-in-progress is here:
[https://github.com/tirix/lets-prove-leftpad/tree/metamath/metamath](https://github.com/tirix/lets-prove-leftpad/tree/metamath/metamath)

It seems that the last pull request has been on hold since January 2023, I'm unsure if any new one will get merged.

**Comment by jkingdon** [comment]
> My work-in-progress is here: https://github.com/tirix/lets-prove-leftpad/tree/metamath/metamath
> 
> It seems that the last pull request has been on hold since January 2023, I'm unsure if any new one will get merged.

I suppose the next step (especially since you have done so much of the work already) is to get it in pull request form even if we aren't really sure what would happen after that? The explanation of the proofs could perhaps be a little less detailed if that made it any easier (although I don't have a strong opinion on that).

There were several pull requests merged in 2022 for whatever that is worth.

**Comment by tirix** [comment]
I've added more to the readme file:
[https://github.com/tirix/lets-prove-leftpad/tree/metamath/metamath](https://github.com/tirix/lets-prove-leftpad/tree/metamath/metamath)

> explanation of the proofs could perhaps be a little less detailed

I've pushed the detailed explanations to the very end of the file, and kept only the general principles at the top.

> the next step is to get it in pull request form

Yes. I'd love to get a review of that submission by @david-a-wheeler too!

**Comment by jkingdon** [comment]
> I've pushed the detailed explanations to the very end of the file, and kept only the general principles at the top.

Ah yes, and more importantly you finished writing it! I don't have any particular opinion about how detailed it should be, I just was thinking about the effort level.

**Comment by david-a-wheeler** [comment]
Overall https://github.com/tirix/lets-prove-leftpad/tree/metamath/metamath looks great! I'm glad to see it. Here are a few thoughts:

In "More details and explanations", I would add one sentence for each of the major items that succinctly explains "what this says". The theorem "lpadleft" does this, but not "leftpad" or "lpadright". E.g.:

* Definition of leftpad, add as first sentence: "We define the leftpad function as accepting character c, a word (sequence) w, and length l; it returns a new word with c repeated l times on its left followed by the original word w".
* I'd shorten lpadleft's first sentence to: "This theorem shows that any character with an index in the range (current text) is C."
* "lpadright", add: "This theorem shows that any character with an index after the range (current text) is its corresponding value in the original w."

The text of "leftpad" sometimes uses uppercase and sometimes uses lowercase in a way that appears inconsistent.

Also, this didn't turn into a link for some reason:

~~~~
 (~ovmpt2d)[https://us.metamath.org/mpeuni/ovmpt2d.html]
~~~~

**Comment by tirix** [comment]
Thank you David!
I've incorporated your changes, and merged @icecream17's suggestions too.
If there are no more remarks, I'll issue the PR, and hope the repository's maintainer will notice.

**Comment by david-a-wheeler** [comment]
Wonderful! They may only occasionally look at pull requests to merge them. In that case, it's important to have this PR in the queue so that it's available when they *do* look at it.

**Comment by tirix** [comment]
Mission successful, our PR was merged!

**Comment by david-a-wheeler** [comment]
Awesome! Thank you so much!

**Comment by jkingdon** [comment]
Nice to see this and browse https://github.com/hwayne/lets-prove-leftpad/tree/master/metamath
