### ISSUE TITLE
Add `metamath` to .gitignore

### ISSUE THREAD

**Issue by CatsAreFluffy** [metamath/set.mm#3377]
The example commands in CONTRIBUTING.md and the "Getting started with contributing" wiki page invoke metamath.exe as `./metamath`. This suggests that metamath.exe should be included in the working directory, but currently if someone does that and tries to commit changes they'll inadvertently add metamath.exe to this repository. Adding `metamath` to the gitignore file would avoid this issue.

**Comment by tirix** [comment]
I'd say open a pull request with the change!

Personally I'd like to add `*.mmp`, `*.mmt` and `*.mms` to `.gitignore`, those are working files generated by Yamma in the `set.mm` directory, which I'd like to avoid committing by mistake.

**Comment by CatsAreFluffy** [comment]
Completed in #3384.
