### ISSUE TITLE
is the union of countably many countable sets countable?

### ISSUE THREAD

**Issue by jkingdon** [metamath/set.mm#3394]
Andrej Bauer calls this the "litmus test" for a definition of countability ( https://mathstodon.xyz/@andrejbauer/110906869535920346 ). Is this provable given the ∃𝑓 𝑓:ω–onto→(𝐴 ⊔ 1o) definition that we use in most of our countability theorems in iset.mm? Does it require countable choice?

I'm not sure where I'd go to research this further, though.

**Comment by jkingdon** [comment]
I have the sketch of what appears to be a proof of this, but I've hit a snag and I'm not sure whether it is just that I haven't fully gotten the hang of nested quantifiers ("for every x in A there exists a f such that....") or whether I'm attempting to use what amounts to the axiom of choice, or what.

My statement of what we want to prove is:

```
  ${
    ctiunct.a $e |- ( ph -> E. f f : _om -onto-> ( A |_| 1o ) ) $.
    ctiunct.b $e |- ( ( ph /\ x e. A )
      -> E. g g : _om -onto-> ( B |_| 1o ) ) $.
    $( The union of countably many countable sets is countable.

       The proof proceeds by mapping a natural number to a pair of natural
       numbers (by ~ xpomen ) and using the first number to map to an element
       ` x ` of ` A ` and the second number to map to an element of B(x) .  In
       this way we are able to map to every element of ` U_ x e. A B ` .
       Although it would be possible to work directly with countability
       expressed as ` E. f f : _om -onto-> ( A |_| 1o ) ` , it is easier to
       perform this proof by transforming to functions from subsets of the
       natural numbers via ~ ctssdc .

       (Contributed by Jim Kingdon, 24-Oct-2023.) $)
    ctiunct $p |- ( ph -> E. h h : _om -onto-> ( U_ x e. A B |_| 1o ) ) $=
      ? $.
  $}
```

The nested quantifier there is "for every x in A there exists a g".

The key lemma (most of which I"ve proved) is:

```
$d A n x $.  $d B n $.  $d n F x $.  $d z F x $.  $d n G $.  $d n J x $.  $d z
  J $.  $d z S $.  $d z T $.  $d U n $.  $d ph n x $.
ctiunct.som $e |- ( ph -> S C_ _om ) $.
ctiunct.sdc $e |- ( ph -> A. n e. _om DECID n e. S ) $.
ctiunct.f $e |- ( ph -> F : S -onto-> A ) $.
ctiunct.tom $e |- ( ( ph /\ x e. A ) -> T C_ _om ) $.
ctiunct.tdc $e |- ( ( ph /\ x e. A ) -> A. n e. _om DECID n e. T ) $.
ctiunct.g $e |- ( ( ph /\ x e. A ) -> G : T -onto-> B ) $.
ctiunct.j $e |- ( ph -> J : _om -1-1-onto-> ( _om X. _om ) ) $.
ctiunct.u $e |- U = { z e. _om | ( ( 1st ` ( J ` z ) ) e. S /\ ( 2nd ` (
      J ` z ) ) e. [_ ( F ` ( 1st ` ( J ` z ) ) ) / x ]_ T ) } $.
ctiunct.h $e |- H = ( n e. U |-> ( [_ ( F ` ( 1st ` ( J ` n ) ) ) / x ]_
      G ` ( 2nd ` ( J ` n ) ) ) ) $.
ctiunct.nfh $e |- F/_ x H $.
tiunct.nfu $e |- F/_ x U $.
ctiunctlemfo $p |- ( ph -> H : U -onto-> U_ x e. A B ) $= ... $.
```

Now `S` and `F` come from `E. f f : _om -onto-> ( A |_| 1o )`. First apply https://us.metamath.org/ileuni/ctssdc.html to get:

```
E. s
  (  s C_ _om
  /\ E. f f : s -onto-> A
  /\ A. n e. _om DECID n e. s )
```

then use theorems like `rexlimddv` to use this to satisfy the hypotheses of the lemma.

But how does this work for `g`, `T`, and `G`? We are dealing with a family of sets/functions, where we have one for each `x` in `A`. I would think this dependence on `x` is just expressed by the order of the quantifiers, but I didn't see how to apply the `rexlimddv` pattern or something similar while putting the `x e. A` in the correct place. Like I say, I can't tell whether this is a technical matter of getting a bit better at arranging these quantifiers, or a more fundamental issue of whether any of this is going to work.

**Comment by digama0** [comment]
I don't think this is provable, or more specifically it requires the axiom of countable choice. The version that is provable is that if you have `F : _om -onto-> ( A |_| 1o )` and `G : X_ x e. A ( _om -onto-> ( B |_| 1o ) )` then `U_ x e. A B` is countable, but you need CC in order to construct the function `G` out of your `A. x e. A E. g` quantifier.

Remember that it is consistent with ZF that the real numbers (while still uncountable) are a countable union of countable sets, so if IZF is a subsystem of ZF then it can't prove this property.

**Comment by jkingdon** [comment]
> I don't think this is provable, or more specifically it requires the axiom of countable choice.

Ah, then my intuition that this involved choice wasn't too far off.

> The version that is provable is that if you have `F : _om -onto-> ( A |_| 1o )` and `G : X_ x e. A ( _om -onto-> ( B |_| 1o ) )` then `U_ x e. A B` is countable, but you need CC in order to construct the function `G` out of your `A. x e. A E. g` quantifier.

Hmm, I guess this is too far from "countably many countable sets" to get too excited about it. (Not that I yet know enough to really have a good feel for what to get excited about).

> Remember that it is consistent with ZF that the real numbers (while still uncountable) are a countable union of countable sets, so if IZF is a subsystem of ZF then it can't prove this property.

One caveat: IZF is not sufficient to prove that the reals are uncountable. But I don't think that affects the impossibility argument you are making here. (for those reading along, possibly including future me, there are references concerning  the "it is consistent with ZF that . . . " theorem at https://mathoverflow.net/questions/100717/zf-the-reals-are-the-countable-union-of-countable-sets-consistent ).

**Comment by digama0** [comment]
> One caveat: IZF is not sufficient to prove that the reals are uncountable. But I don't think that affects the impossibility argument you are making here.

Right, my point is that IZF doesn't prove anything that ZF doesn't prove because it is a strictly weaker system, so if there is a model of ZF in which the reals are uncountable and also a countable union of countable sets, then this shows the unprovability of "a countable union of countable sets is countable" in ZF and any subsystem thereof, including IZF.

> Hmm, I guess this is too far from "countably many countable sets" to get too excited about it. (Not that I yet know enough to really have a good feel for what to get excited about).

I would argue that it is a fairly natural recasting of the theorem to put all the choices up-front. You can also phrase it in metamath using free class variables rather than an existential quantifiers:
```
  ${
    ctiunct.a $e |- ( ph -> F : _om -onto-> ( A |_| 1o ) ) $.
    ctiunct.b $e |- ( ( ph /\ x e. A )
      -> G : _om -onto-> ( B |_| 1o ) ) $.
    ctiunct.h $e |- H = ... $.
    $( The union of countably many (constructively) countable sets is countable. $)
    ctiunct $p |- ( ph -> H : _om -onto-> ( U_ x e. A B |_| 1o ) ) $=
      ? $.
  $}
```
In this form it is likely to be usable in practice, if you ever have the need to prove the constructive existence of an enumerating function for a union of (constructively) countable sets. In fact, this is the same as your statement modulo an application of the existence property.

**Comment by jkingdon** [comment]
> You can also phrase it in metamath using free class variables rather than an existential quantifiers

Wow, now I feel like I'm writing proof-relevant type theory.

Anyway, I'll give formalizing this a try.

**Comment by jkingdon** [comment]
As for the version described in the comment of https://us.metamath.org/ileuni/ctiunct.html which needs countable choice, proving it from `CCHOICE`, or some other formalization of countable choice, would appear to depend on figuring out #3687
