### ISSUE TITLE
Minimize proofs depending on df-cleq (resp. df-clel) but until #3389 not on ax-9 (resp. ax-8)

### ISSUE THREAD

**Issue by benjub** [metamath/set.mm#3402]
After the revision of df-cleq and df-clel in #3389, every theorem depending on df-cleq (resp. df-clel) now also depends on ax-9 (resp. ax-8).

Consider a theorem which depended, before #3389, on df-cleq but not on ax-9, and suppose it has a shorter proof using ax-9. That proof could not be found by `MM-PA> MINIMIZE_WITH *`, since that command does not consider statements adding axiom dependencies.

Therefore, one should do a global `MM-PA> MINIMIZE_WITH *` on every theorem which before #3389 depended on df-cleq but not on ax-9, and on every theorem which before #3389 depended on df-clel but not on ax-8.

Anyone up for it, just assign yourself to this issue (or comment here if you don't have the rights to assign).

**Comment by GinoGiotto** [comment]
I'll do it (probably in the next few days).

Just a quick question to be sure I understand: If I introduce df-clel in a theorem dependency I would automatically introduce ax-8 as well? If yes, I think there shouldn't be any issue with using the usual minimization form `MINIMIZE * /ALLOW * /NO_NEW ax-*`

**Comment by icecream17** [comment]
To be clear the reason the usual minimization would work is that such theorems already depend on dfclel/dfcleq, which is what this issue is about. If a shorter proof exists by _introducing_ these definitions, that might indeed add unnecessary axioms, and so the regular minimize would not introduce these definitions
