### ISSUE TITLE
iset.mm problems with the power set of a singleton

### ISSUE THREAD

**Issue by jkingdon** [metamath/set.mm#3456]
The challenge is the two problems in https://mathstodon.xyz/@MartinEscardo/111002413035009813

**Comment by benjub** [comment]
The second excercise is already in iset.mm as ~exmidpw, no ?

As for the first, it suffices to prove that there is no injection from `3o` to `~P { (/) }`... I'll think about it.

**Comment by jkingdon** [comment]
I'm going to take a crack at proving them in a form a bit closer to how they are stated in the prompt but you are right that the second one is pretty close to https://us.metamath.org/ileuni/exmidpw.html

**Comment by jkingdon** [comment]
Here's how I've stated the problems. I'm assuming that, based on "a map e : Fin n → Ω is an embedding iff e x = e y implies x=y (which is not enough to characterize embeddings for more general types, but in this case it is).", we can express the idea of being an embedding, here, with `-1-1->`.

```
  ${
    pwle2.t $e |- T = U_ x e. N ( { x } X. 1o ) $.
    pwle2 $p |- ( ( N e. _om /\ G : T -1-1-> ~P 1o ) -> N C_ 2o ) $=
      (  ) ? $.

    pwf1oexmid $p |- ( ( N e. _om /\ G : T -1-1-> ~P 1o )
        -> ( ran G = ~P 1o  <-> ( N = 2o /\ EXMID ) ) ) $=
      (  ) ? $.
  $}
```

Neither appears to be as easy as I thought when I first saw them (at least, I don't see how to prove them). For the forward direction of the second one, you need to get `N = 2o` first before you can apply exmidpw

**Comment by jkingdon** [comment]
Another thing which would apparently suffice is `x e. ~P 1o -> -. -. ( x = (/) \/ x = { (/) } )` . But I'm not sure that's even provable, to be honest I don't know whether it is like https://mathoverflow.net/questions/452678/does-negative-trichotomy-hold-for-constructive-ordinals or not.

**Comment by icecream17** [comment]
In the case of https://mathoverflow.net/questions/452678/does-negative-trichotomy-hold-for-constructive-ordinals

<https://us.metamath.org/ileuni/mmil.html>
![image](https://github.com/metamath/set.mm/assets/58114641/f4b0505c-1f07-4e14-868d-55084ded6e16)

Given that `( 𝐴 < 𝐵 ∨ 𝐴 = 𝐵 ∨ 𝐵 < 𝐴)` is provable in classical propositional calculus, the `not not` version is provable in intuitionistic version, right?

**Comment by digama0** [comment]
It's unfortunately not that simple. The "propositional calculus" part there is load-bearing. Glivenko's theorem does extend to predicate calculus, but there is an additional double negation you have to put in front of every existential quantifier. That means that it's not necessarily the case that you can just `not not` an arbitrary ZFC proposition and get something intuitionistically provable.

That said, this theorem's double negation is provable. Suppose that `-. A < B`, `-. A = B` and `-. B < A`. Then `A <= B` and `B <= A` by lenlt, so `A = B` by letri3, hence contradiction.

**Comment by benjub** [comment]
> As for the first, it suffices to prove that there is no injection from `3o` to `~P { (/) }`... I'll think about it.

Remark: when I wrote that, I was wrongly assuming a non-intuitionistic contraposition.

**Comment by jkingdon** [comment]
So this is partly my fault for starting us down some tangents, but we've been talking about:

1. `-. -. ( x < y \/ x = y \/ y < x )` where x and y are real. This is in iset.mm as https://us.metamath.org/ileuni/ltntri.html (see https://us.metamath.org/ileuni/ioran.html if you are unsure whether ltntri is equivalent to what is shown here)
2. `-. -. ( x e. y \/ x = y \/ y e. x )` where x and y are ordinals. This is not provable at least if we trust the Paul Taylor reference given at mathoverflow (which states without proof that it isn't provable).
3. `-. -. ( x = (/) \/ x = { (/) } )` where x is a subset of `{ (/) }`. This should just be an application of the law of noncontradiction ( https://us.metamath.org/ileuni/pm3.24.html ) as described in section 1.1 of the [Bauer] reference at https://us.metamath.org/ileuni/mmil.html but to make this work one has to recast subsets of `{ (/) }` into propositions (as we do in the proof of https://us.metamath.org/ileuni/exmidexmid.html ). Although I doubted this could work above, I'm not at all sure I was right.
4. the actual two problems at the top of this issue, which have to do with embeddings from natural numbers (well or something which is basically a natural number) to `~P 1o `.  I think Item 3 would suffice, but there might be other ways to prove them. We're pretty sure they are provable because Escardo proved them in foundations which we don't have any reason to believe are different from iset.mm in any way which affects whether these can be proved.

**Comment by digama0** [comment]
> > As for the first, it suffices to prove that there is no injection from `3o` to `~P { (/) }`... I'll think about it.
> 
> Remark: when I wrote that, I was wrongly assuming a non-intuitionistic contraposition.

I think your reduction is correct. The reason is that natural numbers have decidable comparison, so `-. 3o <= n` implies `n <= 2o`. For any `n` greater than 3 there is an injection from 3 to n, and so if there is no injection from 3 to `~P 1o` then there is also no injection from n.

**Comment by digama0** [comment]
I believe item 4 is equivalent to item 3, because if you have `a` which is not equal to `(/)` or `{ (/) }` then you have an injection from 3, namely `{0 -> (/), 1 -> { (/) }, 2 -> a}`, and conversely if you have an injection from 3 then you have three values a, b, c which are all pairwise not equal, and after a very long case analysis we can prove that if `a = (/)` and `b = { (/) }` then c violates item 3, and similarly for every permutation of `a,b,c` being assigned to one of `(/)`, `{ (/) }` or neither (violating item 3). You can do this case analysis without LEM because for example if we assume `a = (/)` and prove a contradiction (first half of the case analysis), then we have proven `a =/= (/)` and can use that to prove a contradiction as well (second half of the case analysis).

**Comment by digama0** [comment]
So it suffices to consider item 3. Suppose `x =/= (/)` and `x =/= { (/) }`. Now consider an arbitrary `a e. x`. Since `x C_ { (/) }`, `a = (/)`, therefore `{ (/) } C_ x` and hence `x = { (/) }` , a contradiction. Therefore `x` has no elements and `x = (/)`, also a contradiction. Hence false.

**Comment by jkingdon** [comment]
Item 3 is https://github.com/metamath/set.mm/pull/3478

I'll add item 4 in another pull request, may take another day or two

**Comment by benjub** [comment]
> > > As for the first, it suffices to prove that there is no injection from `3o` to `~P { (/) }`... I'll think about it.
> > 
> > 
> > Remark: when I wrote that, I was wrongly assuming a non-intuitionistic contraposition.
> 
> I think your reduction is correct. The reason is that natural numbers have decidable comparison, so `-. 3o <= n` implies `n <= 2o`. For any `n` greater than 3 there is an injection from 3 to n, and so if there is no injection from 3 to `~P 1o` then there is also no injection from n.

You're right; we use the intuitionistic $((\phi \wedge \psi) \to \bot) \to (\phi \to \neg\psi)$ with $\phi =$"there is an injection from $n$ to $\Omega$" and $\psi = (3 \leq n)$ so $\neg\psi \leftrightarrow (n \leq 2)$ (for integers).
