### ISSUE TITLE
Contribution principles

### ISSUE THREAD

**Issue by jkingdon** [metamath/set.mm#3483]
Managing a collaborative project such as metamath involves, among other things, acknowledging contributions and we have a variety of ways of doing that. This has led to quite a variety of different perspectives and uncertainty about how to proceed in a number of contexts. Some of what I say here was prompted by specific things which happened recently but others have been vexing me (and probably others) for much longer.

My proposal is to write down a few things (e.g. about git logs and the contributor list at the top of set.mm) which I think were clear in some people's minds but maybe not everyone. But also to write a list of principles, on the theory that if we have at least some level of shared understanding about what we are trying to achieve, perhaps that will make it a bit easier for the specific conventions to be applied or refined than if we just have conventions alone.

I suppose if we decide we want this text it would go in CONTRIBUTING.md but whether there is some other place is also up for discussion.

> We acknowledge people who contribute to these proofs in various ways, including
comments on each theorem, statements on the web site, git logs, and others.

> Although there are conventions relating to many of these, they are guided
by some principles:

> 1. We want to make everyone who contributes to metamath to feel appreciated.
This goes double for new contributors! In many cases, their experiences
upon attempting their first submission will determine whether they continue
to participate.

> 2. Although we want every contributor to be acknowledged in some way, where
and how this is done is more flexible.  In some cases contribution
will be mentioned along with the text or proofs that was contributed,
in others it will be in separate historical records.

> 3. A lot of people have built set.mm and iset.mm, going back decades, and
this is worth celebrating! From lists of people to graphical visualizations,
we love showing off our current and past contributors.

> Mechanisms:

> * There is a contributor list at the top of set.mm and iset.mm.
If you find someone with a Contributed, Revised by, or Proof shortened
by line who is not in the contributor list, either it is a mistake
or they are so far undercover that their identity must remain as
an easter egg to be discovered.

> * The git history.  This is the most historical of our records, but is
also hard to revise if something confusing happened during merging.
For that reason if a submission is going to be accepted and then revised,
it is usually better either for the original author to make the
revisions, or merge the original pull request followed a separate pull
request (possibly from a different person) with the revisions.
By "hard to revise" we mean the only practical way to change git history,
once a change has been merged, is to make a commit reverting
that change, followed by another one with new content or different
authorship.

> * The Contributed by, Revised by, and Proof shortened by comments are described
in the Metamath book and https://us.metamath.org/mpeuni/conventions-comments.html

> * The Metamath 100 list gives an author or a small list next to each
theorem. It is our best attempt to summarize who did most of the work
in contributing that theorem to metamath.

> * Other mentions on the web site are more flexible in format and subject
to revision as text is modified and moved around.

> * changes-set.txt, like git history, is a historical record but only
mentions authorship when theorems are moved in or out of mathboxes.

**Comment by benjub** [comment]
Concerning the "specific things ... vexing you (and probably others)", I think it would be good to try and solve them as soon as they appear, and here is an appropriate place to do so, in my opinion. This would be beneficial to the vexed ones (you "and probably others"), and to the (probably involuntary) vexers, so as not to do it again.

In, https://us.metamath.org/mpeuni/conventions-comments.html, I wrote the sentence "Since this is somewhat subjective, judgment and intellectual honesty should be applied, with collegial settlement in case of dispute." in that spirit, and I think it's better to have a short sentence like that, rather than risking an inflation of texts like the above proposal. Not that I particularly disagree with it, but the more texts like that there are, the more opportunities to argue and disagree on the precise phrasing, etc.  I find it rather vague and not to the point. When I open a contributing.md, I want to find instructions on how to, say, us git, push, merge, rebase, what to write where. Something "to the point" and not longer than strictly required.

**Comment by jkingdon** [comment]
In the case of #3440 , by the time we realized there was a problem, we had already lost a potential contributor (probably forever, but even in the best case scenario temporarily).

I do share the concern about whether writing too much text is harmful (the reader has to parse it including how much of what is written is malleable or obsolete, etc). That's what got me thinking in terms of principles more so than additional detailed rules. Of course "Since this is somewhat subjective, judgment and intellectual honesty should be applied, with collegial settlement in case of dispute" is even more concise and I guess for me the big thing which isn't covered by that is how to make metamath more welcoming for new contributors (well and how we make "collegial" a reality although I'm not sure I have a lot of answers on that except to say it is one of our big questions including at places like #3170).

We could dig into details but based on the lack of discussion on this issue so far I guess my default assumption is that people don't really see a big need to add/modify contribution principles of whatever format.

**Comment by icecream17** [comment]
On the question about how we make "collegial" a reality, I think Metamath already has that overall feeling similar to most other math texts published online, and it would be even if several additional playful quips were added. (Note that not all jokes are in the humor section)

<details><summary>spoiler</summary>

I vaguely remember NM's joke about a 5-letter theorem name and how "any relation to" something something something is coincidental or something.

</details>

In general it doesn't seem like collegialness will be a problem, so there isn't a need for more writing on that.

**Comment by jkingdon** [comment]
I'm going to go ahead and close this. There doesn't seem to be any particular enthusiasm for the specific wording in this issue, and I'm not sure there is even much enthusiasm for the ideal of trying to come up with a set of principles (either about acknowledging contributions in particular, or about the project more broadly).

We can always make another proposal later if we feel like there is more clarity or more of a sense of what problems might be solved by this sort of statement.
