### ISSUE TITLE
split set-main.mm into subfiles

### ISSUE THREAD

**Issue by icecream17** [metamath/set.mm#3520]
When running the `write source set.mm /split` command, the largest file `set-main.mm` is 20 megabytes long which is about half of set.mm

To make this easier to work with I'm proposing to split `set-main.mm` further into subfiles

https://us.metamath.org/mpeuni/mmtheorems.html

<details><summary>As an initial suggestion I would say</summary>

+ chapters 2 to 4: `set-settheory.mm`
+ chapters 5 and 6: `set-numbers.mm`
+ chapters 7 to 10: `set-structures.mm`
+ remaining (11 to 17): stay in `set-main.mm`

(note that chapters 15 and 16 are already separate files)
(chapter 11 might also go in structures?)

</details>

Edit: will be per-chapter

**Comment by tirix** [comment]
Maybe rather than "structures", we could group parts 7 to 11 into "Algebra"?
Big chapters would be:
- Logic
- Set Theory
- Number Theory
- Algebra
- Geometry (incl. Topology)
- Analysis

**Comment by digama0** [comment]
why not just split once per part? I don't see any reason to invent yet another categorization.

**Comment by benjub** [comment]
> why not just split once per part? I don't see any reason to invent yet another categorization.

Could we even have the metamath option "/ SPLIT" recognize headers for parts and split there ?

**Comment by icecream17** [comment]
There is some non-triviality with figuring out what files to edit like if they're on related but separate places or if one is not familiar with the terms. (Initially I scrolled through files quite a bit, although I eventually found global find, which kinda makes this point moot).

So yeah probably this is too much pre-optimization and organizing per-chapter would help make chapter organization better in the long run

**Comment by icecream17** [comment]
oh I misremembered chapter 2's status earlier. It seems like part of chapter 2 (up to the axiom of replacement) is in `set-class.mm`

For now here are (also initial) file name proposals:

| ch# | chapter name | file name | already separate | # theorems |
|-------|----------------------|---------------|--------------------------|------------------|
| 1 | CLASSICAL FIRST ORDER LOGIC WITH EQUALITY | `set-pred.mm` | yes | 2750 |
| 2 | ZF (ZERMELO-FRAENKEL) SET THEORY | `set-class.mm`<br>+ `set-zf.mm` | yes + no | 2298 + 4606
| 3 | ZFC (ZERMELO-FRAENKEL WITH CHOICE) SET THEORY | `set-zfc.mm` | no | 247
| 4 | TG (TARSKI-GROTHENDIECK) SET THEORY | `set-tg.mm` | no | 162
| 5 | REAL AND COMPLEX NUMBERS | `set-num.mm` | no | 5397
| 6 | ELEMENTARY NUMBER THEORY | `set-numth.mm` | no | 874
| 7 | BASIC STRUCTURES | `set-struct.mm` | no | 458
| 8 | BASIC CATEGORY THEORY | `set-cat.mm` | no | 601
| 9 | BASIC ORDER THEORY | `set-order.mm` | no | 313
| 10 | BASIC ALGEBRAIC STRUCTURES | `set-algstr.mm` | no | 2870
| 11 | BASIC LINEAR ALGEBRA | `set-linalg.mm` | no | 628
| 12 | BASIC TOPOLOGY | `set-top.mm` | no | 2545
| 13 | BASIC REAL AND COMPLEX ANALYSIS | `set-numanal.mm` | no | 600
| 14 | BASIC REAL AND COMPLEX FUNCTIONS | `set-numfunc.mm` | no | 1568
| 15 | ELEMENTARY GEOMETRY | `set-tarskigeom.mm` | yes | 559
| 16 | GRAPH THEORY | `set-graphth.mm` | yes | 1480
| 17 | GUIDES AND MISCELLANEA | `set-guidesetc.mm` | no | 86
| ... | (deprecated and mathbox) | ... | yes | 16288

I am tempted to exclude the shorter chapters, especially chapters 17, 4, and 3. But chapter 15 does have "just" 559 theorems.

**Comment by savask** [comment]
I think issue https://github.com/metamath/set.mm/issues/29 is relevant to this discussion.

I like the idea of splitting the file per part, but maybe some parts could be reorganized? For instance parts 13 and 14 (real and complex stuff) could be merged into one, in my opinion.

**Comment by jkingdon** [comment]
> For now here are (also initial) file name proposals:

That looks good to me. It doesn't bother me that some files are much shorter than others, that is pretty standard in other contexts (e.g. source code) and it doesn't particularly cause any problems (especially once you get used to tools to do things like search across files, such as https://github.com/BurntSushi/ripgrep or your favorite equivalent).

Some files being especially large might be more of a concern (especially if our goal is to not have text editors get really slow, etc), but none of the files in this split would be as long as what we have now.
