### ISSUE TITLE
some relabelings of axext*

### ISSUE THREAD

**Issue by benjub** [metamath/set.mm#3585]
Following the general trend of striving for more meaningful labels, I propose:
axext2 --> axexte (for "existence")
axext3 --> axextg (for "general")
axext4 --> axextb (for "biconditional")

**Comment by GinoGiotto** [comment]
In [conventions-labels](https://us.metamath.org/mpeuni/conventions-labels.html) it seems the abbreviation `e` is assigned to equality, while `ex` is for existence:

![Immagine 2023-10-23 011513](https://github.com/metamath/set.mm/assets/73717712/6a8374ec-481b-4fd9-bc84-854b189d2442)
![Immagine 2023-10-23 010655](https://github.com/metamath/set.mm/assets/73717712/b97e1729-0c4e-490e-9b2e-1e46471e4d32)

So maybe axext2 --> axextex?

**Comment by icecream17** [comment]
there's spsbe and ax6e so I think the table is simply incomplete

**Comment by wlammen** [comment]
Or the labeling is inconsistent.

**Comment by tirix** [comment]
> Or the labeling is inconsistent.

My thought exactly.

**Comment by benjub** [comment]
Strictly speaking, every labeling is inconsistent, unless we allow labels basically as large as statements. We simply aim to minimize inconsistencies when reasonable. I will add "e" as a possible factor in labels for existence/existential, to reflect current practice.

**Comment by jkingdon** [comment]
Existing practice is certainly to have quite a few labels where `e` is for existence and also where `ex` is for existence.  I'd say changing the conventions to list both is the right call here, because one or the other can make more sense in different contexts.
