### ISSUE TITLE
Define CHOICE in iset.mm

### ISSUE THREAD

**Issue by jkingdon** [metamath/set.mm#3616]
The idea here is to provide a definition (either exactly the same as https://us.metamath.org/mpeuni/df-ac.html or similar, if it needs intuitionizing for some reason).

I'm not sure there's a lot to prove about it other than ` CHOICE -> EXMID ` which would be essentially the same as the https://us.metamath.org/ileuni/acexmid.html proof adapted to the different notation.  Most likely this would be easier if we intuitionize https://us.metamath.org/mpeuni/dfac7.html (or something similar, might depend on how closely we stick to the acexmid proof).

Because choice implies excluded middle, I don't really see the CHOICE notation as hugely interesting in its own right in iset.mm. But part of why I was thinking of adding it was as a stepping stone to countable choice (and, I suppose, dependent choice too) which does come up a lot more in mathematics without excluded middle.

**Comment by digama0** [comment]
Because choice implies excluded middle (which is a proof iset.mm should have and is a good reason to define it), choice does not have any intuitionistically different variations, so you should be able to use the original definition and also prove all the same characterization theorems as in set.mm.

**Comment by jkingdon** [comment]
> Because choice implies excluded middle (which is a proof iset.mm should have and is a good reason to define it), choice does not have any intuitionistically different variations, so you should be able to use the original definition and also prove all the same characterization theorems as in set.mm.

Sorta but there's at least one caveat. To quote [Bauer], p. 483:

> In constructive mathematics we need to take care with the formulation of the
axiom of choice because there is a diﬀerence between a nonempty set, which is a
set A such that ¬(A = ∅), and an inhabited set, which is a set A such that there
exists x ∈ A. The axiom of choice states that any family of inhabited sets has a
choice function.

Might be a bit of a moot point unless we _want_ to try to prove all the characterization theorems, and in fact it isn't immediately obvious to me what the consequences are to working with the "wrong" formulation of choice.

**Comment by benjub** [comment]
Looking at https://us.metamath.org/ileuni/acexmid.html, I notice that the hypothesis `acexmid.choice` misses an initial `A. x`. The proof modifications are straightforward (adding the same quantifier to `acexmidlemv.choice`).

**Comment by jkingdon** [comment]
> Looking at https://us.metamath.org/ileuni/acexmid.html, I notice that the hypothesis `acexmid.choice` misses an initial `A. x`. The proof modifications are straightforward (adding the same quantifier to `acexmidlemv.choice`).

So does https://us.metamath.org/mpeuni/ac2.html . In light of ax-gen this is a stylistic choice and last time Mario and I discussed it (not for this theorem, for another one with this kind of hypothesis) I was advised to leave off the quantifier. I'm not sure either of us feels super strongly about it, though.

**Comment by benjub** [comment]
> So does https://us.metamath.org/mpeuni/ac2.html . In light of ax-gen this is a stylistic choice and last time Mario and I discussed it (not for this theorem, for another one with this kind of hypothesis) I was advised to leave off the quantifier. I'm not sure either of us feels super strongly about it, though.

Thanks, I had missed that discussion. My point was to have a sentence, which is easier to interpret than an open formula.
