### ISSUE TITLE
3 Bad dates

### ISSUE THREAD

**Issue by arpie-steele** [metamath/set.mm#3628]
```
Theorem       Bad Date     Blame Date   BlameRev
dfcoeleqvrels 22-Nov-2028  21-Jul-2023  29b322f0c22c8ab889d6236537b80f5137e822e8
dfcoeleqvrel  22-Nov-2028  21-Jul-2023  29b322f0c22c8ab889d6236537b80f5137e822e8
2mulprm        8-Jun-2030  23-Jul-2023  bc266806bf678083cdebd55364c186284f57feb8
                            1-Jul-2023  0ccfa19b47ec9074801a002db000a8428f2aed81
```

Suggestion: 2mulprm -> 8-Jun-2023 (based on 0ccfa19b47ec9074801a002db000a8428f2aed81 and assuming year only is wrong)
Suggestion: dfcoeleqvrels -> 28-Nov-2022 (same as df-coeleqvrels, which is also in 29b322f0c22c8ab889d6236537b80f5137e822e8 and assuming transposed day/year digits)
Suggestion: dfcoeleqvrel -> 28-Nov-2022

**Comment by arpie-steele** [comment]
Request for comment from @mazsa  and @avekens

**Comment by mazsa** [comment]
>  Suggestion: dfcoeleqvrels -> 28-Nov-2022
>  Suggestion: dfcoeleqvrel -> 28-Nov-2022

@arpie-steele Good catches. If you open a PR for this, I'll accept your suggestions, or I'll fix it in one of my next PRs. Thank you.

**Comment by avekens** [comment]
> Suggestion: 2mulprm -> 8-Jun-2023 

OK for me, please correct it in #3630

**Comment by arpie-steele** [comment]
Upon further review, two more typos were found with obvious likely replacements.

Found: 15-Oct-1013 starting in fda18f6019 so likely it should be 15-Oct-2013
Found: 23-Apr-1017 starting in 0f3533bfd5 so likely it should be 23-Apr-2017

This is all I found in today's `set.mm` and `nf.mm` by looking for out-of-range years. Looking for out-of-range month or day-of-month yielded no results for dates that matched [0-9]{1,2}-[A-Z][a-z][a-z]-[0-9]{4}.

**Comment by jkingdon** [comment]
Looks like everything mentioned here is fixed.

If there are unresolved issues go ahead and re-open this issue (or perhaps better, create a new issue with whatever is left).
