### ISSUE TITLE
Empty mathbox

### ISSUE THREAD

**Issue by GinoGiotto** [metamath/set.mm#3629]
In set.mm there is this mathbox:
<pre>
$(
#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
  Mathbox for Drahflow
#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#

  This is the mathbox of Jens-Wolfhard Schicke-Uffmann, reachable at
  drahflow@gmx.de / drahflow.name

$)

$( (End of Drahflow's mathbox.) $)
</pre>

Which is empty. It is placed between the mathbox of Paul Chapman [20.8](https://us.metamath.org/mpeuni/mmtheorems325.html#mm32460b) and the mathbox of Scott Fenton [20.9
](https://us.metamath.org/mpeuni/mmtheorems325.html#mm32473b)

From the links above, it's possible to note that the empty mathbox for Drahflow is not reported on the official Metamath website, therefore it appears as if it doesn't exist.

However it is reported on @tirix metamath-web https://metamath.tirix.org/mpests/toc?ref=1042, generating an empty webpage.

This causes the subsequent chapter counting to be unmatched between the two websites (Scott Fenton mathbox is [20.9
](https://us.metamath.org/mpeuni/mmtheorems325.html#mm32473b) in the official website, while it's [20.10](https://metamath.tirix.org/mpests/toc?ref=1086) in metamath-web).

What would you suggest to solve these discrepancies?

Opinion part: My opinion would be to delete empty mathboxes as they occupy space without satisfying their intended purpose of containing math content. Drahflow name is mentioned in the contributor list, so he/she still keeps its own credits.

**Comment by digama0** [comment]
Empty sections are deliberately omitted from the TOC in the web site generation. I would suggest that @tirix 's TOC code follow suit.

As for the mathbox itself, I would not suggest doing anything with it. It would just cause unnecessary churn if the reason the mathbox is empty is because of upstreaming theorems to main, since then it may be emptied and filled on a regular basis. As long as the tools ignore it there is really little harm in empty sections. (They also may not be empty, e.g. the theorems in it are commented out, in which case deleting the section is even more clearly the wrong choice.) I would leave the decision of what to do with this section up to @Drahflow .

**Comment by arpie-steele** [comment]
I checked my memory, and I know who and when cleared out Drahflow's mathbox. It was _**me**_ back in PR #1666.

In 5-Jun-2020, I rescued some nice work. The `set.mm` from b17b206c016c447d5fe4579696339580201106a5 shows the post-PR file has an empty mathbox.

https://github.com/metamath/set.mm/tree/b17b206c016c447d5fe4579696339580201106a5

**Comment by GinoGiotto** [comment]
> Empty sections are deliberately omitted from the TOC in the web site generation. I would suggest that @tirix 's TOC code follow suit.

Ok. Then this is a [metamath-web](https://github.com/tirix/metamath-web) issue. I'll leave this one open for a few more days in case @Drahflow will intervene.

**Comment by david-a-wheeler** [comment]
I agree with Mario, we should support empty mathboxes easily. Another reason is that creating an empty mathbox is a useful first step to putting things into a mathbox. New users are often trying to "figure it all out", so it's helpful to be able to create an empty mathbox area *for* them. They can then put stuff in it. I think the ability to do that is helpful.

**Comment by tirix** [comment]
Definitely agree with David here. 
However, this is not about whether empty mathboxes should be supported or not, they are supported in all cases.
The question is whether we should skip empty mathboxes (and other empty chapters) in tables of contents and chapter numbering.
`Metamath-exe` skips them, `Metamath-knife` does not.

**Comment by david-a-wheeler** [comment]
My two cents: I think skipping is the better answer (metamath-exe), and tweak metamath-knife to match. There's no content, so there's nothing worth showing.

**Comment by digama0** [comment]
> The question is whether we should skip empty mathboxes (and other empty chapters) in tables of contents and chapter numbering. `Metamath-exe` skips them, `Metamath-knife` does not.

`mm-web-rs` skips them, and it is based on `metamath-knife`, although it doesn't make use of the `outline_pass` and does [its own version](https://github.com/digama0/mm-web-rs/blob/201bd8e71caddcfbb31628ba100be36f4a1b6892/src/render.rs#L246-L271) of it. I think the current behavior of `metamath-knife` is fine.

**Comment by GinoGiotto** [comment]
From the discussion above it was agreed to keep the empty mathboxes in the database and adapt metamath-web to the behaviour of the official website, therefore I opened a new issue on metamath-web and closed this one.
