### ISSUE TITLE
Can cnplimc be proved in iset.mm?

### ISSUE THREAD

**Issue by jkingdon** [metamath/set.mm#3634]
As discussed in #3223 we defined `limCC` (and from there derivatives) by basically taking the classical epsilon-delta definition and changing not equal to apart. This has gotten us part of the way to making these concepts useful, including for example https://us.metamath.org/ileuni/limccnp2cntop.html and https://us.metamath.org/ileuni/dvid.html .

However, one of the key sticking points relates continuity to the limit of a function, namely that "A function is continuous at 𝐵 iff its limit at 𝐵 equals the value of the function there" that is https://us.metamath.org/mpeuni/cnplimc.html . The forward direction, proved at https://us.metamath.org/ileuni/cnplimcim.html , is easy, because continuity applies at all points in an interval and the limit of a function needs basically the same property at a subset of that interval (points apart from B).

In set.mm the reverse direction is proved using a lot of looking at decidable equality between B and other real numbers. Can this somehow be proved in iset.mm? On the one hand, you might think so because the limit of a function does tell us things about points arbitrarily close to B. On the other hand, it isn't clear how to replace the technique of combining B with non-B points to make an interval. I tried working with two points, B and another point apart from B but sufficiently close, and relatedly wondering if `cnlimc` is any easier than `cnplimc`, but I haven't figured out anything like that which works yet.

This has implications for theorems like https://us.metamath.org/mpeuni/dvcn.html where the set.mm proof uses the reverse direction of `cnplimc` in an apparently essential way.

**Comment by digama0** [comment]
It didn't seem like it would be possible at first, but I think I have a proof.

* We have: $\forall\epsilon>0,\exists \delta>0,\forall z,z\mathrel{\\#}b\land\left|z-b \right|<\delta\to\left|f(z)-f(b)\right|<\epsilon$
* We want: $\forall\epsilon>0,\exists \delta>0,\forall z,\left|z-b \right|<\delta\to\left|f(z)-f(b)\right|<\epsilon$

Fix $\epsilon>0$, instantiate the other quantifier with $\epsilon/2$, and take the other quantifiers to be the same.
* We have: $z\mathrel{\\#}b\land\left|z-b \right|<\delta\to\left|f(z)-f(b)\right|<\epsilon/2$
* We have: $\left|z-b \right|<\delta$
* We want: $\left|f(z)-f(b)\right|<\epsilon$

We can use weak trichotomy to consider the cases $\left|f(z)-f(b)\right|<\epsilon$ or $\left|f(z)-f(b)\right|>\epsilon/2$. In the first case we are done, and in the second case we will seek a contradiction. Suppose $z\mathrel{\\#}b$. Then $\left|z-b \right|<\delta$ means we can apply the first hypothesis, so $\left|f(z)-f(b)\right|<\epsilon/2$, contradicting $\left|f(z)-f(b)\right|>\epsilon/2$. Therefore $\neg(z\mathrel{\\#}b)$, so $z=b$. Thus $\left|f(z)-f(b)\right|=0<\epsilon/2$, again a contradiction.

**Comment by jkingdon** [comment]
Very nice. Once again I fail to see a proof where non-decidability does not preclude assuming the positive (in this case z # b), deriving a contradiction, and then proceeding with the negative.

I'll work on formalizing this.
