### ISSUE TITLE
Should distinctness be decidable in iset.mm?

### ISSUE THREAD

**Issue by jkingdon** [metamath/set.mm#364]
That is, do we want an axiom of the sort `A. x x = y \/ -. A. x x = y`?

Another option is `A. x x = y \/ F/_ x y` because `A. x x = y \/ -. A. x x = y` has some possibly undesirable decidability statements equivalent to DECID(the universe has one element) in the absence of `dtru`. Note that iset.mm doesn't have `F/_` yet, but presumably it could (and see https://github.com/metamath/set.mm/pull/192#issuecomment-351952043 for a bit more elaboration).

Note that `ax-i12` states that `( A. z z = x \/ ( A. z z = y \/ A. z ( x = y -> A. z x = y ) ) )` which is along these lines, and it would be even stronger if the last disjunct also had `A. x`, that is `( A. z z = x \/ ( A. z z = y \/ A. x A. z ( x = y -> A. z x = y ) ) )`. In fact that strengthened version of `ax-i12` would make fairly easy work of the remaining work on #339 which is the main remaining piece of predicate logic which is unproven in iset.mm.

For past discussion see #362 and #192 .

I (@jkingdon) don't have a particularly good feel for the consequences of these decisions. It is very tempting to say "well of course a variable is just a string of unicode characters (or equivalently, a natural number) and so of course distinctness should be decidable". But saying it that way is almost inviting the parallels to non-Euclidian geometry or intuitionistic logic or other cases where it turned out to be fruitful to make fewer "obvious" assumptions. That is, does adding additional axioms about what a "variable" is restrict the possible models or otherwise rule out useful possibilities?

And on the flip side, what is the advantage of such an axiom? Is it the only way to solve #339 and if not, what kinds of theorems are possible with decidable distinctness but which are not possible without it? Is decidable distinctness independent of the existing axioms? Is it worth examining whether `ax-i12` itself is even too strong and what kind of logic would we get if we omitted it or replaced it with an alternative?

**Comment by digama0** [comment]
> That is, does adding additional axioms about what a "variable" is restrict the possible models or otherwise rule out useful possibilities?

I would conjecture that the answer to this is "yes". Of course this is more or less equivalent to "is this axiom redundant", whenever you add a nontrivial new axiom the set of models is reduced. I would be quite surprised if this axiom is provable, but it is certainly useful, in the sense of powering "bundling" proofs where a theorem is proven by proving it with the same variable and with a $d condition to get the general case. A model where the variables have some kind of continuity to them, so that "not quite distinct" variables are a thing, would be something I have never seen before. On the one hand that's a good thing - Metamath has discovered this new ground of reasoning at the object level about distinctness of variables, and this allows new and interesting properties and logics. But on the other, of course there isn't going to be much literature on the world omitting this axiom.

Given that Metamath can so easily handle logical subsystems, I don't think there is any harm to having this axiom and maybe tracking which theorems actually need it. I'd call it the "bundling axiom" FWIW.

**Comment by digama0** [comment]
I think that ax-12 should be stated using `F/_ x y ->` instead of `A. x x = y \/`, especially if we are going to start tracking usage of the bundling axiom. Otherwise it's smuggling in a weak form of the bundling axiom with those disjunctions.

**Comment by jkingdon** [comment]
OK, so if we look at https://github.com/metamath/set.mm/pull/192#issuecomment-351952043 the bundling axiom reads `|- ( A. x x = y \/ A. z A. x ( z = y -> A. x z = y ) )` and if I look at http://us2.metamath.org:88/mpeuni/df-nfc.html it seems like that would be with a distinct variable constraint on `x` and `z`.

So if we wanted to state it without distinct variable constraints it would read `|- ( A. x x = y \/ ( A. x x = z \/ A. z A. x ( z = y -> A. x z = y ) ) )` or in other words exactly the same (well, modulo a little commutativity or other rearrangements which don't change the strength) as the "strengthened version of ax-i12" mentioned above.

So perhaps we should go with that?

The idea of tracking axiom use and weakening `ax-i12` so it doesn't smuggle in a version of the bundling axiom also strikes me as OK, but also as the kind of thing that we can do as we get around to it. Whereas I feel some urgency in better separating `ax-3` from the intuitionistic parts of `iset.mm`, and the bundling axiom as shown above may be the last remaining piece needed for that.

**Comment by digama0** [comment]
That's a good point - the equality-based definition of `F/_` makes the bundling axiom essentially just strong ax-12. Conversely, weak ax-12 is
```
|- ( F/_ x y -> ( F/_ x z -> F/ x y = z ) )
```
which when expanded becomes
```
$d u x  $d u y  $d v x  $d v z
|- ( A. u A. x ( u = y -> A. x u = y ) ->
     ( A. v A. x ( v = z -> A. x v = z ) -> A. x ( y = z -> A. x y = z ) ) )
```
which is pretty obviously provable (using a4im or something). I guess what is happening is that `F/_` is basically defined as something that satisfies ax-12, so "strong ax-12" is actually the bundling axiom and "weak ax-12" is provable.

**Comment by jkingdon** [comment]
Good point about how any non-redundant axiom rules out possibilities. Just out of curiosity, I did a little internet searching about axioms for geometry. We all know about geometries which don't accept the parallel postulate. But it turns out there are also some which don't accept Pasch's axiom (at least interesting enough to write a few papers about).

Anyway, to get back to iset.mm, now that #369 is merged this issue can be considered resolved. If people want to investigate which proofs require `ax-bnd`, try to prove the independence of `ax-bnd`, etc, that can all be done within iset.mm in the usual way.

As for whether the "version of ax-12 with only one disjunction and a DV condition implies the two-disjunction version" (or in other words, whether replacing ax-i12 with http://us2.metamath.org:88/ileuni/dveeq2or.html would let us prove ax-i12) I have a certain amount of experience with using ax-i12 to remove distinct variable constraints and that might tend to argue for "no", but I could easily see it going the other way. We can make a list of open problems (on Intuitionistic Logic Explorer web pages, in github issues, whereever) if people are interested in doing so.
