### ISSUE TITLE
CCHOICE and countably infinite versus countable

### ISSUE THREAD

**Issue by jkingdon** [metamath/set.mm#3687]
Most literature references that I've seen regarding countable choice either (a) assume excluded middle, for example ZF, and thus are not directly applicable to iset.mm, or (b) just express countable choice in terms of a family of inhabited sets which is countably infinite (that is, equinumerous to ω) and don't mention at all whether it also applies to a family which is countable (that is, ∃𝑓 𝑓:ω–onto→(𝐴 ⊔ 1o)) as well.

Right now, iset.mm has a definition of `CCHOICE` which applies to the countably infinite case - https://us.metamath.org/ileuni/ccfunen.html

The question is whether `CCHOICE` also implies a similar theorem for countable collections, for example:

```
    ccfun.cc $e |- ( ph -> CCHOICE ) $.
    ccfun.a $e |- ( ph -> E. g g : _om -onto-> ( A |_| 1o ) ) $.
    ccfun.m $e |- ( ph -> A. x e. A E. w w e. x ) $.
    ccfun $p |- ( ph -> E. f ( f Fn A /\ A. x e. A ( f ` x ) e. x ) ) $=
      ? $.
```

Although this might seem like a simple matter of finding a countably infinite set which contains the given one and applying `ccfun` to that, my attempts to do so weren't working in ways that have me a bit worried.

My first approach was to wonder whether `( A |_| _om )` is countably infinite, but I didn't see a proof for that.

My second approach was to construct:

```
    ccfunlem.f $e |- ( ph -> F : _om -onto-> ( A |_| 1o ) ) $.
    ccfunlem.g $e |- G = ( n e. _om |-> ( { n } X. ( K ` ( F ` n ) ) ) ) $.
    ccfunlem.k $e |- K = case ( ( _I |` A ) , ( 1o X. { { (/) } } ) ) $.
```

Now `ran G` is a countably infinite collection of inhabited sets, so one can apply `ccfun` to get a choice function on it.

But we are looking for a choice function on ` A `, and given an element of ` A `, there might be multiple natural numbers which ` F ` maps to that element and no way to choose one of them that I noticed.

A construction similar to the one in https://us.metamath.org/ileuni/ennnfone.html (in which we build up our answer one element at a time, adding a new element only when necessary) seems like the sort of thing we'd need, but that relies on decidable equality.

I'm a little surprised I didn't find discussion of this question in mathoverflow or the other literature I consulted - perhaps it is out there and I just didn't find it? Or perhaps there is indeed a proof which I missed which makes choice functions available for both countably infinite and countable (and thus makes it unneccessary to talk of multiple inequivalent definitions of countable choice)?

**Comment by jkingdon** [comment]
My current assumption is that the existence of a choice function for any countable collection of inhabited sets requires more than countable choice. If I look at something like the definition of the Axiom of Countable Choice, AC<sub>ω</sub>, in section 10.2 of [[AczelRathjen]](https://us.metamath.org/ileuni/mmil.html#AczelRathjen) they only discuss an infinitely countable collection and the same is true of places like Lemma: 8.1.27 (a countably infinite collection of countable sets has a sequence of enumerations, given countable choice).

At least based on a browse through that work, it would seem like the question everyone is asking about is the union of a sequence of countable sets (that is, a countably infinite number of them), rather than the union of countably many countable sets.

**Comment by digama0** [comment]
> But we are looking for a choice function on `A`, and given an element of `A`, there might be multiple natural numbers which `F` maps to that element and no way to choose one of them that I noticed.

Luckily, the natural numbers come with a canonical choice function: choose the minimal one. Any inhabited subset of natural numbers should have a minimum element (constructively), you take the intersection of all the ordinals considered as sets.

**Comment by jkingdon** [comment]
> Any inhabited subset of natural numbers should have a minimum element (constructively),

You mean like https://us.metamath.org/ileuni/nnregexmid.html ?

**Comment by benjub** [comment]
> > Any inhabited subset of natural numbers should have a minimum element (constructively),
> 
> You mean like https://us.metamath.org/ileuni/nnregexmid.html ?

A way to formalize Mario's original claim that you do not need the axiom of choice or any variant is to assume that the subset of natural numbers has decidable membership: "An inhabited decidable subset of natural numbers has a minimum element."

**Comment by jkingdon** [comment]
> A way to formalize Mario's original claim that you do not need the axiom of choice or any variant is to assume that the subset of natural numbers has decidable membership: "An inhabited decidable subset of natural numbers has a minimum element."

~~Oh, I think that works, using https://us.metamath.org/ileuni/ctssdc.html .~~

~~I've started in on this, and it is enough formalizing that it might take me a day or two to work this out, but at first glance it seems like it will work. Thanks for the suggestion.~~

Update: I don't think ctssdc helps the way I thought it would. Although the set `s` from that theorem is decidable, the set which wasn't decidable was the set of indexes which map to a particular element of ` A ` .

**Comment by digama0** [comment]
Yes, the theorem I was thinking of assumes that the set has decidable membership. In this case, that amounts to a requirement that `A` has decidable equality. If you don't have that, then I think you will not be able to prove the original claim. It might be better to have `A` index a collection of sets instead of *being* a collection of sets, since there are some examples where the indexing set has decidable equality even if the sets themselves don't.

**Comment by jkingdon** [comment]
See https://us.metamath.org/ileuni/cc3.html or https://us.metamath.org/ileuni/cc4.html for examples where the choice is on one set which is indexed by a second set, a countably infinite one. I'm going to consider cc3 and cc4 as sufficient solutions and close this issue, since they should make it possible to prove what you need to prove in this area.
