### ISSUE TITLE
Typo in the description for Theorem rexbidvaALT

### ISSUE THREAD

**Issue by walkingsophie** [metamath/set.mm#3690]
![image](https://github.com/metamath/set.mm/assets/43860774/c5b0c15a-e3b7-431d-b610-6c60b164fbbb)

The description should say "Alternate proof of rexbidva" instead of "Alternate proof of rexbida"

**Comment by jkingdon** [comment]
Thanks for reporting this! I made a pull request at https://github.com/metamath/set.mm/pull/3691

If you want to submit the pull request yourself next time, we have a guide to doing so at https://github.com/metamath/set.mm/wiki/Getting-started-with-contributing
