### ISSUE TITLE
Making SymGrp a structure restriction of EndoFMnd

### ISSUE THREAD

**Issue by avekens** [metamath/set.mm#3843]
As discussed in #3838, `SymGrp`  currently cannot be expressed as structure restriction of `EndoFMnd` because of the specific definition of `SymGrp`:

```
SymGrp = ( x e. _V |-> [_ { h | h : x -1-1-onto-> x } / b ]_
      { <. ( Base ` ndx ) , b >. ,
        <. ( +g ` ndx ) , ( f e. b , g e. b |-> ( f o. g ) ) >. ,
        <. ( TopSet ` ndx ) , ( Xt_ ` ( x X. { ~P x } ) ) >. } )
```

 If this definition was replaced by 
```
SymGrp = ( x e. _V |-> { <. ( Base ` ndx ) ,  { h | h : x -1-1-onto-> x }  >. ,
        <. ( +g ` ndx ) , ( f e. ( x ^m x ) , g e. ( x ^m x ) |-> ( f o. g ) ) >. ,
        <. ( TopSet ` ndx ) , ( Xt_ ` ( x X. { ~P x } ) ) >. } )
```
then we would have
```
( SymGrp ` A ) = ( ( EndoFMnd ` A ) |`s { h | h : A -1-1-onto-> A } ) 
                       = ( ( EndoFMnd ` A ) |`s ( Base ` ( SymGrp ` A )  ) )
```
and we could reuse a lot of theorems for `EndoFMnd` also for `SymGrp`.

I think only a small number of basic theorems for `SymGrp` would be affected by this change.

**Comment by icecream17** [comment]
personally I would use the latter since it's simpler
```
SymGrp = ( x e. _V |-> ( ( EndoFMnd ` x ) |`s { h | h : x -1-1-onto-> x } ) )
```

**Comment by avekens** [comment]
Since PR #3838 has been merged and ` EndoFMnd ` is officially available now (but still in a mathbox), I would suggest to move the definition of ` EndoFMnd ` and related theorems to the main body of set.mm (as proposed by @tirix and Gérard Lang) and then to adapt the definition for ` SymGrp `  as proposed by @icecream17 . Afterwards, I think some theorems for ` SymGrp `  can be shortened using corresponding theorems for ` EndoFMnd ` .

**Comment by tirix** [comment]
> I would suggest to move the definition of EndoFMnd and related theorems to the main body of set.mm (as proposed by @tirix and Gérard Lang) and then to adapt the definition for SymGrp as proposed by @icecream17 .

Yes, I'm favorable to that!

**Comment by benjub** [comment]
I haven't followed the recent developments here, so maybe this has already been looked at:

Since set.mm has defined the notion of category, it may be worth using the general construction (which may already be formalized in set.mm): if C is a category and X is an object of C, then End(C, X) is a monoid and Aut(C, X) is a group. Then, apply this with `C := Set`, the category of sets and functions.

This would be something like
```
$a |- End = ( c e. Cat |-> ( x e. ( Base ` c ) |-> ... ) ) $.
```

**Comment by avekens** [comment]
> Since set.mm has defined the notion of category, it may be worth using the general construction (which may already be formalized in set.mm): if C is a category and X is an object of C, then End(C, X) is a monoid and Aut(C, X) is a group. Then, apply this with `C := Set`, the category of sets and functions.
> 
> This would be something like
> 
> ```
> $a |- End = ( c e. Cat |-> ( x e. ( Base ` c ) |-> ... ) ) $.
> ```

I do not understand exactly what you mean. I had a look in the literature (Wikipedia, [Adamek]), but could not find anything about this approach. Maybe you can provide a reference. I cannot find someting in this direction within set.mm either.

**Comment by benjub** [comment]
> > Since set.mm has defined the notion of category, it may be worth using the general construction (which may already be formalized in set.mm): if C is a category and X is an object of C, then End(C, X) is a monoid and Aut(C, X) is a group. Then, apply this with `C := Set`, the category of sets and functions.
> > This would be something like
> > ```
> > $a |- End = ( c e. Cat |-> ( x e. ( Base ` c ) |-> ... ) ) $.
> > ```
> 
> I do not understand exactly what you mean. I had a look in the literature (Wikipedia, [Adamek]), but could not find anything about this approach. Maybe you can provide a reference. I cannot find someting in this direction within set.mm either.

I hope that #3907 clarifies the above. Then,
```
ph -> U e. V
ph -> C = ( SetCat ` U )
ph -> X e. U
=>
ph -> ( C End X ) is the monoid of endofunctions on X
```
Since SetCat is relativized to U (https://us.metamath.org/mpeuni/df-setc.html) (which is necessary since we cannot consider the category of all sets in our extensible structure framework), this may be a bit cumbersome.

**Comment by avekens** [comment]
Done with #3900, but also see #3907.
