### ISSUE TITLE
Hypotheses with an "is a set" property using the universal class _V

### ISSUE THREAD

**Issue by avekens** [metamath/set.mm#3893]
The conventions for set.mm state that hypotheses of theorems in deduction form with an "is a set" property should not use the universal class `_V`: 

> Notice that this does not hold for hypotheses of theorems in deduction form: Here still ` |- ( ph -> A e. V ) ` should be used rather than ` |- ( ph -> A e. _V ) `.

Currently, there are 173 hypotheses using the universal class `_V` in such cases, e.g., ~euotd. The number of affected theorems is smaller, because some theorems have more than one of these hypotheses.

The question is: should these theorems be modified, replacing `_V` by `V`? If there are more than one of these hypotheses for a theorem, then different class variables (`V`, `W`, `U` etc.) should be used.

The replacement can be performed semiautomatically by using a script (expand the OLD theorem and perform a minimization for each affected theorem afterwards).

I can remember a discussion about this some time ago (which resulted in the above mentioned convention), but I cannot find anything written about it. Does anybody know where to find something about it?

**Comment by tirix** [comment]
I agree with the direction here.

You might think about #944 ?

**Comment by avekens** [comment]
#944 is about '( ? e. _V -> ' , that means `e. _V` is used in the antecedent of an implication, not as consequent (of a hypothesis) as mentioned above.

**Comment by tirix** [comment]
> #944 is about '( ? e. _V -> ' , that means e. _V is used in the antecedent of an implication, not as consequent (of a hypothesis) as mentioned above.

Indeed! 
I don't remember any other such discussion, and could not find any when searching.

**Comment by jkingdon** [comment]
Sounds like a good change to me.  If you are able to get to it, doing this in iset.mm as well would be appreciated. Because iset.mm has https://us.metamath.org/ileuni/elex.html and other theorems relevant to this discussion, the tradeoffs in iset.mm are the same as in set.mm.

**Comment by avekens** [comment]
With PR #4137, this issue is done: there are no hypotheses in the form |- ( ph -> * e. _V ) $. anymore in set.mm (main body). 

There are still some of such hypotheses in the mathboxes: these have to be converted before the corresponding theorems are moved to main.

Furthermore, there are still hypotheses in a similar form, like:

    en2i.3:  ( x e. A -> C e. _V )
    en2i.4: ( y e. B -> D e. _V )
    elfvmptrab.v: ( X e. V -> M e. _V )
    elovmporab.v: ( ( X e. _V /\ Y e. _V ) -> M e. _V )

or

    isofrlem.2: ( ph -> ( H " x ) e. _V )
    fvmptopab.2: ( ph -> { <. x , y >. | x ( F Z ) y } e. _V )`
    f1opw2.2: ( ph -> ( `' F " a ) e. _V )
    f1opw2.3: ( ph -> ( F " b ) e. _V )
    ...

These do not fall unter the "Is-a-set" convention, and I do not see an obvious advantage to change them. Therefore, I did not revise them.
