### ISSUE TITLE
Category theory

### ISSUE THREAD

**Issue by digama0** [metamath/set.mm#39]
Some work is needed to unify existing developments of category theory in FL's mathbox with the rest of extensible structure-based formalism in main set.mm.

**Comment by tirix** [comment]
It looks like this exists in set.mm since January 2017. Can we close this issue @digama0 ?

**Comment by digama0** [comment]
I think you are right. Obviously our work is never done, but it has most of the basic theorems and this issue is kind of open ended. So let's close it and open other issues if something specific comes up.
