### ISSUE TITLE
Interchanging factors in integrals and sums (Lemmas for AKS)

### ISSUE THREAD

**Issue by metakunt** [metamath/set.mm#3947]
@digama0 has proven itgfsum. For my lemma, I need to prove that I can interchange integrals and sums provided that the correct conditions hold.

I have already found useful lemmas for future work, like integration by parts. However I'd need to interchange sums and integral.

I have done a writeup of a lemma I want to prove. I don't even know if those conditions are correct. The qed step could have likely a stronger result regarding the sums. I am yet unsure if I need that a stronger result as in itgfsum, but I am confident that I need the result below.
```
h1::itgfsum3factcom12.1 |- ( ph -> A e. dom vol )
h2::itgfsum3factcom12.2 |- ( ph -> B e. Fin )
h3::itgfsum3factcom12.3 |- (  ( ph /\ ( x e. A /\ k e. B ) )
                      -> C e. V )
h4::itgfsum3factcom12.4 |- ( ( ph /\ k e. B ) -> ( x e. A |-> C ) e. L^1 )
h5::itgfsum3factcom12.5 |- (  ( ph /\ ( x e. A /\ k e. B ) )
                      -> D e. W )
h6::itgfsum3factcom12.6 |- ( ( ph /\ k e. B ) -> ( x e. A |-> D ) e. L^1 )
h7::itgfsum3factcom12.7 |- (  ( ph /\ ( x e. A /\ k e. B ) )
                      -> E e. U )
h8::itgfsum3factcom12.8 |- ( ( ph /\ k e. B ) -> ( x e. A |-> E ) e. L^1 )

qed::    |- (  ph ->  S. A ( C x. sum_ k e. B ( D x. E ) ) _d x = sum_ k e. B ( D x. S. A ( C x. E ) _d x  ) )
                      
```

For my lemma
```math
A = ( 0 , 1 )
```
```math
B = \{0,\dots, n-m\}
```
```math
C = x^{m-1}
```
```math
D=(-1)^{k}\cdot\binom{n-m}{k}
```
```math
E=x^{k}
```
My conditions should hold. The functions are all bounded on $(0,1)$ and the sum is finite.
Lemma is on top of page 4: https://www3.nd.edu/~andyp/notes/AKS.pdf
@digama0 has also shown in itgfsum that under those conditions the sum is in $L^1$. I assume similar conditions will hold for this lemma.

If anyone has an idea how to tackle this I'd love to hear it. It would be best if I could somehow apply itgfsum 3 times, but itgfsum only shows that
```math
\int_{a}^{b} \sum_{k=1}^{m} f(x,k) dx = \sum_{k=1}^{m} \int_{a}^{b} f(x,k) dx 
```
I need 
```math
\int_{a}^{b} f(x,k) \sum_{k=1}^{m} g(x,k)\cdot h(x,k) dx = \sum_{k=1}^{m} g(x,k) \int_{a}^{b} f(x,k)\cdot h(x,k) dx 
```

My current idea is to first use itgfsum on $h(x,k)$ which gives 
```math
\int_{a}^{b} \sum_{k=1}^{m} h(x,k) dx = \sum_{k=1}^{m} \int_{a}^{b} h(x,k) dx 
```
However then I am stuck as I can't move the other functions in and out.
I have already looked at a search which has both integrals and sums and found only those applications

https://us.metamath.org/mpeuni/circlemeth.html
https://us.metamath.org/mpeuni/df-itg1.html
https://us.metamath.org/mpeuni/df-itg.html
https://us.metamath.org/mpeuni/itg1val.html
https://us.metamath.org/mpeuni/itg1val2.html
https://us.metamath.org/mpeuni/dfitg.html
https://us.metamath.org/mpeuni/circlevma.html
https://us.metamath.org/mpeuni/circlemethhgt.html
https://us.metamath.org/mpeuni/itg1addlem4.html
https://us.metamath.org/mpeuni/itgfsum.html
https://us.metamath.org/mpeuni/itgspltprt.html

Only itgfsum seems promising, but I couldn't find an appropriate application to prove my lemma and at my current knowledge it seems unreachable.  On the positive side, the application of integration by parts seems reachable.

I have to give mad credit to Glauco Siliprandi, he has proven lots of Fourier lemmas and those proofs are for my taste otherworldly, so I know it can be done, I just don't know how.

**Comment by metakunt** [comment]
On the flipside I have found out that $f(x,k)$ is constant on k and $g(x,k)$ is constant on x. 
This might help as they are constants I can move them in and out of the integral and sum respectively. I can move $f$ in the sum and $g$ in the integral.. Only $h(x,k)$ depends on both x and k.

I guess this could help, start with 
```math
\int_{a}^{b} \sum_{k=1}^{m} h(x,k) dx = \sum_{k=1}^{m} \int_{a}^{b} h(x,k) dx 
```
and then use equality building theorems to move $f$ and $g$ successfully into their positions. Finally use eqtrd to show equality.

Would this work, if so, that would be huge.

**Comment by metakunt** [comment]
Ok, I think I've figured it out. I start with
```math
\int_{a}^{b} \sum_{k=1}^{m} f(x)\cdot g(k)\cdot h(x,k) dx = \sum_{k=1}^{m} \int_{a}^{b}f(x)\cdot g(k)\cdot h(x,k) dx 
```
I move $f(x)$ out of the sum and $g(k)$ out of the integral, which gives me.
```math
\int_{a}^{b} f(x)\sum_{k=1}^{m}  g(k)\cdot h(x,k) dx = \sum_{k=1}^{m} g(k) \int_{a}^{b}f(x)\cdot h(x,k) dx 
```

I hope this one is correct. Besides the previous theorem that I wanted to prove likely would have inherited the same dv conditions as this. I don't even think the above made much sense since you can't move stuff out of integral or sums that depend on its corresponding variable.

Is this correct?

**Comment by icecream17** [comment]
yeah that would work:

fsummulc2
itgmulc2

**Comment by metakunt** [comment]
Well, and I guess the above theorem is then wrong, or it inherits the same dv conditions as needed. I should have thought a little bit more on that problem. Thanks @icecream17 I can start implementing it now.
