### ISSUE TITLE
 Isosceles Triangle Theorem (metamath 100 #65)

### ISSUE THREAD

**Issue by digama0** [metamath/set.mm#40]
A triangle has two equal sides iff it has two equal angles. This can also be stated w.r.t a specific vertex on the triangle. Metamath 100 theorem # 65.

**Comment by david-a-wheeler** [comment]
I've been struggling (even with hints), so I'm trying to build up my chops in other ways and intend to return to this later.

**Comment by digama0** [comment]
Do you have a formulation of the statement to prove? Perhaps I can help.

On Wed, Aug 24, 2016 at 12:15 AM, David A. Wheeler <notifications@github.com

**Comment by david-a-wheeler** [comment]
This would be much easier with Euclidean plane Geometry, issue #49. The "lite" version uses the complex numbers instead, a la ang180.

**Comment by david-a-wheeler** [comment]
Completed by Saveliy Skresanov - congrats!
