### ISSUE TITLE
ax-strcoll and ax-sscoll in iset.mm are inconsistent

### ISSUE THREAD

**Issue by CatsAreFluffy** [metamath/set.mm#4077]
Assuming `phi` is true and `a` is inhabited and after simplifying, [~ax-strcoll](https://us.metamath.org/ileuni/ax-strcoll.html) is `E. b A. y y e. b`, which is equivalent to `_V e. _V`, which contradicts [~vprc](https://us.metamath.org/ileuni/vprc.html). Comparing to axiom 7'' of https://plato.stanford.edu/entries/set-theory-constructive/axioms-CZF-IZF.html, after expanding [~ax-strcoll](https://us.metamath.org/ileuni/ax-strcoll.html) has `A. x e. a E. y ( ph -> y e. b )`, where the similar term in axiom 7'' is `A. x e. a E. y e. b ph`. Similar concerns apply to [~ax-sscoll](https://us.metamath.org/ileuni/ax-sscoll.html). These axioms are in @benjub's mathbox, and they are not currently used outside their respective sections.

**Comment by benjub** [comment]
Thanks. I'm going to look at it this weekend.
