### ISSUE TITLE
finite elements of ℕ∞ are isolated

### ISSUE THREAD

**Issue by jkingdon** [metamath/set.mm#4152]
That is, to the use the words of https://mathstodon.xyz/@MartinEscardo/113001536506411322 :

> for every n : ℕ and x : ℕ∞, it is decidable whether n ＝ x

or in iset.mm notation

```
A. n e. _om A. x e. NN+oo DECID ( i e. _om |-> if ( i e. n , 1o , (/) ) ) = x
```

The intuition behind this theorem, if I understand correctly, is that you only need to look at finitely many elements of the sequence ` x ` to figure out whether it is equal to ` n ` . So the proof probably involves induction up to ` n ` .

**Comment by benjub** [comment]
I don't think induction is necessary: let $n \in \omega$ and let $x \in \mathbb{N}_\infty$. Then, $x(n)=0 \vee x(n)=1$. In the second case, $x \neq  \bar{n}$, and in the first case,  if $n=0$ then $x = \bar{n}$, else again $x(n-1)=0 \vee x(n-1)=1$, and in the first case, $x \neq \bar{n}$ and in the second case, $x = \bar{n}$.
