### ISSUE TITLE
df-cdeq

### ISSUE THREAD

**Issue by icecream17** [metamath/set.mm#4158]
https://us.metamath.org/mpeuni/df-cdeq.html

Would it also work to prove the syntax _theorem_, i.e. ccdeq would have three f-hypotheses (vx vy wph) and show wi((weq cv(vx) cv(vy)) wph)? That would seem to flatten the syntax structure equivalently

**Comment by benjub** [comment]
We could, but syntax theorems do not shorten later proofs, unless they are special instances, see https://us.metamath.org/mpeuni/bj-1.html

By the way, it was not agreed to move https://us.metamath.org/mpeuni/bj-0.html and https://us.metamath.org/mpeuni/bj-1.html to the main section, even as examples.
