### ISSUE TITLE
Convention: capitalize "Theorem" in expressions like "Theorem ~ syl ".

### ISSUE THREAD

**Issue by benjub** [metamath/set.mm#4163]
It is usual in the math literature to capitalize the words "Theorem", "Definition", "Axiom", etc. when referring to a numbered statement, e.g., "by Theorem 1.2", or "see Proposition 2.1 of [Megill]".  Statements in Metamath databases are not numbered but labeled, so it makes sense to me to write things like "Definition ~ xxx ", etc., with a capital letter, thereby following the dominant convention.

I propose to use that convention consistently and to add it to our conventions for set.mm-like databases.

Thanks to @avekens's search https://github.com/metamath/set.mm/pull/4160#discussion_r1730292920, we know that there are about 250 changes to make in the current version of set.mm, which I can do if I get enough approvals to this issue.

If you simply agree, a "+1" reaction suffices.

@all doesn't work, so @avekens @tirix @jkingdon @digama0 @icecream17 @wlammen and everyone

**Edit:** Two precisions, following the first reactions:
* I am not proposing to add "Theorem" or "Definition" in front of all labels; only, where that word is already there, to capitalize it.
* Here are two examples, and to show that I am not cherry-picking, I am choosing two reputable open-access math journals, "Forum of Mathematics, Pi" and "Annales de la Faculté des Sciences de Toulouse", and for each of them, I am blindly taking the article accessible through the first link (as of the day I'm writing this):
  *  https://www.cambridge.org/core/journals/forum-of-mathematics-pi/article/theta-functions-fourth-moments-of-eigenforms-and-the-supnorm-problem-ii/15A4F6C14D49E228B1E3C9B8EFCBDCBB and
  * https://afst.centre-mersenne.org/articles/10.5802/afst.1761/
 
 and in the pdf's, I search for the first occurrence of "theorem", case insensitive, in that context. They are, respectively:
  * "Theorem 1.2 specializes to Theorem 1.1 upon taking..." (with hyperlinks on the numbers), and
  * "...which is proved in Theorem 5.10." (with a hyperlink on the number).

**Comment by jkingdon** [comment]
Not sure I have an opinion yet but I guess to my eyes the hyperlinking maybe also achieves what capitalization would. Or maybe another way to say it is I'm not sure I've noticed anything wrong with what we have been doing.

**Comment by icecream17** [comment]
I think `Theorem ~ syl` is not a very good example since most of the time, it's just `~ syl`, but +1

**Comment by benjub** [comment]
@icecream17 : you're right: I took `~ syl` in the example since that's the first label that came to my mind... Also, I am not proposing to **add** "Theorem" or "Axiom" in front of labels, but only, where that word already exists, to capitalize it (I'm going to edit the proposal accordingly).

@jkingdon : I wouldn't say the other ways were wrong, but only that we are increasing consistency and conformance to common conventions. I'm going to edit the proposal to add examples from the literature, with hyperlink and capitalization.

**Comment by avekens** [comment]
I like @benjub's suggestion: +1
Here are other examples in literature which follow the proposed convention:
* B. Bollobas "Modern Graph Theory"
* N. Bourbaki "Algebra I"
* S. Lang "Algebra"
* J. Adamek "Abstract and Concrete Categories"

**Comment by tirix** [comment]
If Bourbaki does it, then there's not much to argue! +1
