### ISSUE TITLE
Pairwise disjointness of hom sets?

### ISSUE THREAD

**Issue by zwang123** [metamath/set.mm#4197]
The current definition `df-cat` does not seem to forbid categories with overlapping Hom sets, which seems to be contradicting the axiom CAT 1 in [[Lang](https://us.metamath.org/mpeuni/mmset.html#Lang)] p. 53, the claimed justification of `df-cat`.

For example, the following might be provable. (I have not tried yet though.)
( Maybe ``$e |- .x. = (/) $.`` or `` $e |- C = { <. ( Base ` ndx ) , B >. , <. ( Hom ` ndx ) , H >. } $.`` works as well. )
```
$e |- B = 2o $. 
$e |- H = ( ( B X. B ) X. 1o ) $. 
$e |- .x. = ( ( ( B X. B ) X. B ) X. ( ( 1o  X. 1o ) X. 1o ) ) $.
$e |- C = { <. ( Base ` ndx ) , B >. ,
         <. ( Hom ` ndx ) , H >. ,
         <. ( comp ` ndx ) , .x. >. } $. 
$( A structure with objects being ` (/) ` and ` 1o ` ,
   and morphisms being ` (/) ` is a category? $)
$p |- ( C e. Cat /\ (/) =/= 1o 
        /\ ( ( (/) H 1o ) i^i ( (/) H (/) ) ) =/= (/) ) $=
( ) ? $.
```

That is to say
```
|- E. c e. Cat
        -. ( ( ( X ( Homf ` c ) Y ) i^i ( Z ( Homf ` c ) W ) ) =/= (/) -> ( X = Z /\ Y = W ) ) 
```

One of the consequences is the inability of extracting the domain and/or codomain solely from the morphism itself. With Homa defined, I am not sure if this is a serious problem, but the fact (if I am not wrong) that Hom sets might overlap should be at least noted in the description.

If we need to comply with CAT 1, a proposal is

```
df-cat $a |- Cat = { c | [. ( Base ` c ) / b ]. [. ( Hom ` c ) / h ].
      [. ( comp ` c ) / o ]. A. x e. b
      ( E. g e. ( x h x ) A. y e. b
        ( A. f e. ( y h x ) ( g ( <. y , x >. o x ) f ) = f /\
          A. f e. ( x h y ) ( f ( <. x , x >. o y ) g ) = f ) /\
        A. y e. b A. z e. b A. f e. ( x h y ) A. g e. ( y h z )
      ( ( g ( <. x , y >. o z ) f ) e. ( x h z ) /\ A. w e. b
    ( ( ( ( x h y ) i^i ( z h w ) ) =/= (/) -> ( x = z /\ y = w ) ) 
      /\ A. k e. ( z h w )
         ( ( k ( <. y , z >. o w ) g ) ( <. x , y >. o w ) f ) =
         ( k ( <. x , z >. o w ) ( g ( <. x , y >. o z ) f ) ) ) ) ) } $.
```

P.S.: The real motivation is that I am considering the possibility of recovering the underlying category from a Grothendieck topology. It seems that the objects can be recovered from all morphisms if hom sets are pairwise disjoint or all morphisms are explicitly attached to its domain and codomain like Homa.

**Comment by zwang123** [comment]
I realized requiring pairwise disjointness might be problematic and disqualify the currently defined SetCat as a category since a function defined in set.mm is not distinguished by its codomain…

**Comment by benjub** [comment]
> I realized requiring pairwise disjointness might be problematic and disqualify the currently defined SetCat as a category since a function defined in set.mm is not distinguished by its codomain…

You're right, it's like in the case of functions. Some encodings of functions comprise the data of domain and codomain, e.g., a function is a triple (A, F, B) where $F \subseteq A \times B$ is such that... Similarly, you have a version for categories in https://us.metamath.org/mpeuni/df-homa.html

**Comment by tirix** [comment]
So axiom CAT 1 in [[Lang](https://us.metamath.org/mpeuni/mmset.html#Lang)] p. 53 does not hold for our formalization? 
Maybe it would it be interesting to add this information, at least as a comment, to set.mm.

**Comment by digama0** [comment]
This is a deliberate design. Requiring hom sets to be disjoint makes it harder to instantiate categories which already have a natural notion of what a hom is unless you dress it up in some pair to ensure injectivity; so when creating a category you don't need to supply disjoint hom data (like functions in Set or group homomorphisms in Grp) and the tagging construction is instead given in df-homa (which is itself useful for building things like the arrow category). This is basically a special case of our general theory on disjointification c.f. ~disjsnxp . See also df-arw, which talks explicitly about this issue.

From a type theory perspective the axiom CAT1 mentioned is a bit nonsense, hom sets with different source/target are different types so it makes no sense to compare elements between them.

I do agree it would be good to mention this in the definition df-cat though, especially if we are referencing [Lang] p. 53 in the comment.

**Comment by benjub** [comment]
Closing as completed by #4201.
