### ISSUE TITLE
Revision of the proof of the Cauchy-Schwarz inequality

### ISSUE THREAD

**Issue by avekens** [metamath/set.mm#4217]
Currently, ~sii, the proof of the Cauchy-Schwarz inequality (No. 78 of the Metamath 100 theorems) is  in the deprecated PART 18  COMPLEX TOPOLOGICAL VECTOR SPACES, section "18.5.3  Properties of pre-Hilbert spaces", of set.mm. 

It should be revised so that it can be moved to the main part (section  "12.5.4  Subcomplex pre-Hilbert space"?).

@icecream17 thank you for this hint.

**Comment by tirix** [comment]
We have [~ ipcau](http://us.metamath.org/mpeuni/ipcau.html) which is not deprecated.

We should probably simply move the MM#100 marker from `~sii` to `~ipcau`.

**Comment by avekens** [comment]
> We have [~ ipcau](http://us.metamath.org/mpeuni/ipcau.html) which is not deprecated.

Yes, you are right!
 
> We should probably simply move the MM#100 marker from `~sii` to `~ipcau`.

We should do that, but this is not enough: we have to revise all Metamath pages which refer to this theorem (at least https://us.metamath.org/mm_100.html), and the link in https://www.cs.ru.nl/~freek/100/ should be changed, too. @david-a-wheeler could you inform Freek about this change?
Furthermore, Norm was the contributor of this theorem [~sii](https://us.metamath.org/mpeuni/sii.html) until now, but the contributor of ~ ipcau is Mario: @digama0 would you mind if Norm is declared to be the contributor of ~ ipcau, and your name is added in a "revised by" tag?

**Comment by benjub** [comment]
> the link in https://www.cs.ru.nl/~freek/100/ should be changed, too.

The link there is to our Metamath 100 page, so no need to ask for a change there.
