### ISSUE TITLE
Deprecated pages/theorems on Metamath

### ISSUE THREAD

**Issue by humanitiesclinic** [metamath/set.mm#4262]
Dear all,

I noticed that Part 18 on Complex Topological Vector Spaces and Part 19 on Hilbert Spaces are deprecated. May I know are there updated / non-deprecated versions of these parts on Metamath?

**Comment by icecream17** [comment]
According to https://github.com/metamath/set.mm/issues/2201 a decent chunk of part 18 has a replacement.

We have df-grp for groups, df-abl for abelian groups, df-cvs for (sub)complex vector spaces (also see df-clm), a section for normed complex vector spaces (starts at [isncvsngp](https://us.metamath.org/mpeuni/isncvsngp.html)), addition, inverse, division, inner-product, and norm.

https://github.com/metamath/set.mm/issues/2859 it doesn't look like part 19 has any progress

**Comment by avekens** [comment]
I think we can close this issue because it is covered by #2201 and #2859. It would be great if somebody took over these tasks, so that we can remove the deprecated parts soon.
