### ISSUE TITLE
Make Metamath 100 project public

### ISSUE THREAD

**Issue by jkingdon** [metamath/set.mm#4282]
If I visit

https://github.com/orgs/metamath/projects

I see

![image](https://github.com/user-attachments/assets/b6cdb835-2dd5-4904-976d-87a2cd6119f2)

where the "Metamath 100" project has a "private" tag (perhaps relatedly or perhaps not, the Metamath 100 one is not shown for me at https://github.com/metamath/set.mm/projects?query=is%3Aopen ). I assume the desired behavior is to make this a public project like the iset.mm one.

There's more documentation about private vs public projects at https://docs.github.com/en/issues/planning-and-tracking-with-projects/managing-your-project/managing-visibility-of-your-projects . If I follow the instructions there to change the visibility I don't see the relevant menu which I think just means I'm not an organization owner.

**Comment by BTernaryTau** [comment]
As you would expect for a private project, I cannot see it at all and did not know that it even existed.

**Comment by digama0** [comment]
It seems to have been created by @tirix . I do not know the circumstances
around the creation of this project board, but I can make it public if
that's the quorum.

**Comment by jkingdon** [comment]
> It seems to have been created by @tirix . I do not know the circumstances around the creation of this project board, but I can make it public if that's the quorum.

The circumstances were https://github.com/metamath/set.mm/pull/4211#issuecomment-2375223914 and a few other comments on that pull request. I'm assuming making it private was an accident but let's ask @tirix to comment on that.

**Comment by tirix** [comment]
Yes, I did not realize the project was private, and it looks like I also cannot change visibility.
@digama0 please change the visibility of the project at your convenience.

**Comment by david-a-wheeler** [comment]
@tirix - done. I just made the project public. Thanks for being willing to make it public. I think we normally want things public unless there's a good reason to do otherwise.

**Comment by jkingdon** [comment]
The private badge is gone at https://github.com/orgs/metamath/projects
