### ISSUE TITLE
ifexd in iset.mm is an odd theorem

### ISSUE THREAD

**Issue by jkingdon** [metamath/set.mm#4380]
In https://us.metamath.org/ileuni/ifexd.html , ` ph ` is used both as an antecedent and as the condition in the ` if ` statement. This means that the theorem could also be proved using `iftrue` and thus would only require the `𝐴 ∈ 𝑉` hypothesis not the `𝐵 ∈ 𝑊` one. This is different from [`ifexd` in set.mm](https://us.metamath.org/mpeuni/ifexd.html) which uses two different variables for the antecedent and the condition in the if.

The whole thing looks like some kind of accident or oversight but I'm not sure what the intention is.

I suppose it could be removed (since it is unused) or made more in line with set.mm (with a decidability condition added).

**Comment by jkingdon** [comment]
Any reactions, @benjub ?

**Comment by digama0** [comment]
This is almost certainly a typo, which should be changed to `ph -> if ( ps , A , B ) e. _V`. I would be surprised if this requires a decidability condition though, it should be an element of the union of `V` and `W`. (EDIT: from what I can tell, you should be able to make the `ph` and `ps` different in `ifelpwund` and `ifexd` and the proofs will go through without other modification.)

**Comment by benjub** [comment]
You're right, it's a typo I'm going to fix. The quantitative version https://us.metamath.org/ileuni/ifelpwung.html is correct.

**Comment by jkingdon** [comment]
> This is almost certainly a typo, which should be changed to `ph -> if ( ps , A , B ) e. _V`. I would be surprised if this requires a decidability condition though

Ah of course, it is analogous to something like https://us.metamath.org/ileuni/ssex.html which doesn't need decidability.
