### ISSUE TITLE
Add Metamath 100 to set.mm repository

### ISSUE THREAD

**Issue by BTernaryTau** [metamath/set.mm#4402]
This is a follow-up to #4282. I noticed that while I can see the Metamath 100 project, it does not appear under [the Projects tab for this repository](https://github.com/metamath/set.mm/projects?query=is%3Aopen) like the iset.mm project does. [Adding the Metamath 100 project to the repository](https://docs.github.com/en/issues/planning-and-tracking-with-projects/managing-your-project/adding-your-project-to-a-repository) should make it easier to find.

**Comment by jkingdon** [comment]
Apparently I have permissions to add it. Done.

Re-open this issue if it isn't showing up for everyone.
