### ISSUE TITLE
Need bibliograph entries for Sanford and Lopez-Astorga

### ISSUE THREAD

**Issue by david-a-wheeler** [metamath/set.mm#46]
How can bibliographic entries be added?  I need these:

[Sanford]
If P, then Q: Conditionals and the Foundations of Reasoning
David H. Sanford
Second edition, 2003.
https://books.google.com/books?id=h_AUynB6PA8C&pg=PA39#v=onepage&q&f=false

[Lopez-Astorga]
The First Rule of Stoic Logic and its
Relationship with the Indemonstrables*
Miguel López-Astorga
Tópicos, Revista de Filosofía 50 (2016), 9-23.
http://www.scielo.org.mx/pdf/trf/n50/n50a1.pdf
page 11.

**Comment by david-a-wheeler** [comment]
Also:

[Hitchcock]
David Hitchcock
The peculiarities of Stoic propositional logic
McMaster University
http://www.humanities.mcmaster.ca/~hitchckd/peculiarities.pdf

**Comment by david-a-wheeler** [comment]
These bibliographic entries are a requirement for the "stoic" branch:

https://github.com/metamath/set.mm/tree/stoic

**Comment by nmegill** [comment]
Hi David,

I insert bib entries into mmset.html in the format illustrated by the 
following example (which contains a number of special cases such as a URL):

<LI><A NAME="Strang"></A> [Strang] Strang, Gilbert, <I>Calculus</I>, 1st
ed., Wellesley-Cambridge Press (1991) [QA303.S8839 1991]; ISBN
978-09802327-45; available at <A
HREF="http://ocw.mit.edu/resources/res-18-001-calculus-online-textbook-spring-2005/">
http://ocw.mit.edu/resources/res-18-001-calculus-online-textbook-spring-2005/</A>
(accessed 24 Nov 2015).</LI>

The 'NAME="Strang"' and '[Strang]' must match exactly the '[Strang]' in 
the set.mm's theorem comment.  If a URL is used, we are starting to 
place '(acessed DD MMM YYYY)' after it in case the page disappears, so 
it can often be located as an archive.org snapshot.

mmset.html has many other examples to consult for formats of special cases.

The QA number and the ISBN number are optional.  Traditionally we 
haven't been putting in the ISBN number.  The QA number, when it exists, 
is really for me so I can quickly find the book in the MIT library. 
MIT's QA number (occasionally different from other libraries) is found 
via http://libraries.mit.edu/barton

If you put your bib refs in this format, send them to me and I will 
insert them into mmset.html.

Norm

**Comment by david-a-wheeler** [comment]
Here's my attempt at reformatting.  I'll email this to Norm:

<LI><A NAME="Sanford"></A> [Sanford] Sanford, David H., <I>If P, then Q: Conditionals and the Foundations of Reasoning</I>, 2nd ed., Routledge Taylor &amp; Francis Group (2003); ISBN 0-415-28369-8; available at <A HREF="https://books.google.com/books?id=h_AUynB6PA8C&pg=PA39#v=onepage&q&f=false">https://books.google.com/books?id=h_AUynB6PA8C&pg=PA39#v=onepage&q&f=false</A> (accessed 3 Jul 2016).</LI>


<LI><A NAME="Lopez-Astorga"></A> [Lopez-Astorga] Lopez-Astorga, Miguel, "The First Rule of Stoic Logic and its Relationship with the Indemonstrables", <I>Revista de Filosofía Tópicos</I> (2016); available at <A HREF="http://www.scielo.org.mx/pdf/trf/n50/n50a1.pdf"> http://www.scielo.org.mx/pdf/trf/n50/n50a1.pdf</A> (accessed  3 Jul 2016).</LI>



<LI><A NAME="Hitchcock"></A> [Hitchcock] Hitchcock, David, <I>The peculiarities of Stoic propositional logic</I>, McMaster University; available at <A HREF="http://www.humanities.mcmaster.ca/~hitchckd/peculiarities.pdf"> http://www.humanities.mcmaster.ca/~hitchckd/peculiarities.pdf</A> (accessed 3 Jul 2016).</LI>

**Comment by david-a-wheeler** [comment]
Norm added those entries (thank you!).
