### ISSUE TITLE
Add pm2.18da to iset.mm

### ISSUE THREAD

**Issue by david-a-wheeler** [metamath/set.mm#490]
I quickly brought over [many theorems that correspond to common natural deduction rules that are valid in intuitionistic logic](http://us.metamath.org/mpegif/natded.html).  However, I did not bring in pm2.18da as that didn't just copy over.  iset.mm does have pm2.18dc, so it might be easy to convert.

**Comment by jkingdon** [comment]
As described at http://us2.metamath.org/ileuni/pm2.01.html (proof by contradiction versus proof of negation being one way to describe it), 2.18da wouldn't hold as-is. Whether you want to start talking about decidable propositions in the natural deduction material, I don't know. I'm not really sure how much the decidability stuff clarifies and how much it just provides one more complication.

**Comment by david-a-wheeler** [comment]
It's not clear that it would be actually used, so I'm going to just close the issue.

**Comment by jkingdon** [comment]
Thanks for following up. Closing the issue is fine with me.
