### ISSUE TITLE
Does Travis check run before or after a tentative merge?

### ISSUE THREAD

**Issue by nmegill** [metamath/set.mm#499]
In develop commit ecfef6d, the Travis check passes

<pre>
Reading source file "set.mm"... 32541516 bytes
32541516 bytes were read into the source buffer.
The source has 147512 statements; 2150 are $a and 30795 are $p.
No errors were found.  However, proofs were not checked.  Type VERIFY PROOF *
if you want to check them.
MM> verify proof *
0 10%  20%  30%  40%  50%  60%  70%  80%  90% 100%
..................................................
All proofs in the database were verified in 4.66 s.
</pre>

If I copy the set.mm file of commit ecfef6d and run locally, I get

<pre>
Reading source file "copied-set.mm"... 32649120 bytes
32649120 bytes were read into the source buffer.
The source has 147926 statements; 2150 are $a and 30852 are $p.
No errors were found.  However, proofs were not checked.  Type VERIFY PROOF *
if you want to check them.
MM> v p *
0 10%  20%  30%  40%  50%  60%  70%  80%  90% 100%
................................
?Error on line 381432 of file "copied-set.mm" at statement 95065, label "f1od2", type
"$p":
      csb cvv sbcbidv sbcan wb fvex ax-mp sbcel1gv anbi12i bitri sbceq2g sbcbii
                                          ^^^^^^^^
This token is not the label of an assertion or optional hypothesis.
..................
</pre>

Based on file size, it looks like Travis checked the set.mm already in the develop branch before the merge.  The merged set.mm correctly fails due to a label change.

Is this the expected behavior?  I don't recall seeing this before, or maybe we have just been lucky.

(PS I fixed this error in commit 83d92df, which was because I renamed sbcel1gv to sbcel1gvOLD; Thierry, you don't need to concern yourself with it.  I will take care of updating it to the sbcel1gv replacement.)

Norm

**Comment by david-a-wheeler** [comment]
On CircleCI you can "flush cache and restart build" - can you do the same in Travis?  Sometimes old cache data causes weird problems.

**Comment by nmegill** [comment]
I think the problem is the change I made to .travis.yml on Aug. 29.  The us.metamath.org temporary mirror (the main server was down) did not allow directory listing.  So I changed it to wget the tar.bz2 instead of the directory, then extracted the files.  The problem is that set.mm (and iset.mm, nf.mm, etc.) is overwritten by the extraction.

What do you think is the best way to fix this?

**Comment by digama0** [comment]
You could move `*.mm` into a temporary folder, then move them back after the extraction.

**Comment by nmegill** [comment]
Yes, I'll try that.

**Comment by david-a-wheeler** [comment]
In the long term I think files should only be in a single place.  E.g., the metamath.exe program shouldn't have a set.mm (or if it does, it'd be in some "examples/" subdirectory used only for testing).  If we more cleanly separated code from data, I think that would be a good thing long term.

**Comment by nmegill** [comment]
We can look at that longer term, although right now a number of things like my build scripts expect those locations.

The historical reason for putting metamath.exe and set.mm in the same place is that specifying directories was too confusing, varying with compiler and OS ("/" or "\" or ":" for early Mac or "[]" for VMS), and there is also the need for quotes in the case of "/".  Getting people to use a command line was trouble enough - in the 90s even math-savvy people were often unfamiliar with computers, and even today some people have never used a command line.  It was/is easier to tell them, "double click on metamath and type 'read set.mm' followed by Enter" to get them started for the first time.

I'll make a note to provide a separate .tar.bz2 with just the metamath source.  But this problem was just a stupid mistake on my part and it's fixed.
