### ISSUE TITLE
Proposal: Move Stoic logic from David A. Wheeler's mathbox

### ISSUE THREAD

**Issue by david-a-wheeler** [metamath/set.mm#64]
I suggest adding Stoic logic, which is about 2000 years old, from the "Stoic logic indemonstrables (Chyrysippus of Soli)" section in my mathbox.  The more obvious place to put it is the  "Other axiomatizations of classical propositional calculus" section.  It could be added just before the "Predicate calculus mostly without distinct variables".

Stoic logic used 5 axioms.   Two are already there;
* modus ponendo ponens (modus ponens) - already an axiom in ~ ax-mp ,
* modus tollendo tollens (modus tollens) - already proven as a derived theorem in ~ mto ,

Here are the others, which are all provable from the existing axioms:
* modus ponendo tollens I ~ mpto1 ,
* modus ponendo tollens II ~ mpto2 , and
* modus tollendo ponens (exclusive-or version) ~ mtp-xor (original Stoic logic version)
* modus tollendo ponens (inclusive-or version) ~ mtp-or (what the name now more commonly means; I haven't found when this shift occurred, because a lot of people aren't careful to disinguish between the 2 kinds of "or"s, but I think it was in antiquity)

It would be quite possible to add "(New usage is discouraged.)"  On the other hand, these theorems have ancient names and are much better known than the ones that *are* currently used, and it wouldn't be surprising if they are quite useful - there's no specific reason their use needs to be discouraged.  They have the advantage of being "intuitive" to many people (as evidenced by their early identification).

**Comment by digama0** [comment]
cc @nmegill

On Sun, Jul 17, 2016 at 10:51 AM, David A. Wheeler <notifications@github.com

**Comment by nmegill** [comment]
Do you have any proofs using only the new axioms?  I am puzzled because 
it seems you have only inference rules with no axioms proper.

**Comment by david-a-wheeler** [comment]
I'm *not* proposing any new axioms for set.mm.  These are merely representations of the axioms that were used by the Stoics.   (I'm using "axiom" in the very general sense of "assumptions" - the Stoics developed the first form of propositional logic, using these logical inference rules as their axioms.)

These proofs simply show that these ancient axioms are derivable from the actual axioms defined in set.mm.  My goal is twofold: (1) documenting the old Stoic axioms in modern notation, and (2) proving that anything that could be proved using the ancient Stoic axioms can also be proved using the axioms actually used in set.mm (since these ancient axioms are either assumed or derivable from them).

**Comment by nmegill** [comment]
On 7/17/16 10:54 AM, Mario Carneiro wrote:
> cc @nmegill
>
> On Sun, Jul 17, 2016 at 10:51 AM, David A. Wheeler <notifications@github.com
>> wrote:
>
>> I suggest adding Stoic logic, which is about 2000 years old, from the
>> "Stoic logic indemonstrables (Chyrysippus of Soli)" section in my mathbox.
>> The more obvious place to put it is the "Other axiomatizations of
> classical
>> propositional calculus" section. It could be added just before the
>> "Predicate calculus mostly without distinct variables".

Go ahead and move them there.


>>
>> Stoic logic used 5 axioms. Two are already there;
>>
>> - modus ponendo ponens (modus ponens) - already an axiom in ~ ax-mp ,
>> - modus tollendo tollens (modus tollens) - already proven as a derived
>> theorem in ~ mto ,
>>
>> Here are the others, which are all provable from the existing axioms:
>>
>> - modus ponendo tollens I ~ mpto1 ,
>> - modus ponendo tollens II ~ mpto2 , and
>> - modus tollendo ponens (exclusive-or version) ~ mtp-xor (original
>> Stoic logic version)
>> - modus tollendo ponens (inclusive-or version) ~ mtp-or (what the name
>> now more commonly means; I haven't found when this shift occurred, because
>> a lot of people aren't careful to disinguish between the 2 kinds of "or"s,
>> but I think it was in antiquity)
>>
>> It would be quite possible to add "(New usage is discouraged.)" On the
>> other hand, these theorems have ancient names and are much better known
>> than the ones that *are* currently used, and it wouldn't be surprising if
>> they are quite useful - there's no specific reason their use needs to be
>> discouraged. They have the advantage of being "intuitive" to many people
>> (as evidenced by their early identification).

Since there are no new axioms nor special proofs, we don't need 
discouraged tags.  I'll leave it up to you.

Norm

**Comment by digama0** [comment]
Done in https://github.com/metamath/set.mm/commit/b63c9f518dceb7cb63c6c5de13bfc11a31783ac5.
