### ISSUE TITLE
Missing configure.ac file in metamath-program.zip

### ISSUE THREAD

**Issue by david-a-wheeler** [metamath/set.mm#687]
We can't easily switch to downloading the MUCH smaller metamath-program.zip
in the Travis build, because it is missing the file "configure.ac".

We instead get this error:

    autoreconf-2.69: 'configure.ac' 

Can you please put the configure.ac file in the zip file?  Or at least the generated "configure" script?

Thanks!

**Comment by nmegill** [comment]
I added configure.ac to metamath-programs.zip on us2 and us.

**Comment by david-a-wheeler** [comment]
Great! Thank you.

**Comment by david-a-wheeler** [comment]
Oh, drat!  I forgot to *also* request "Makefile.am".  So the configuration works, but the build fails.  Can you add that file also?

Thanks!

**Comment by david-a-wheeler** [comment]
Excellent. It works now, and I have a separate pull request that uses it.  Thanks!
