### ISSUE TITLE
Delete mmcomplex.html and mmnatded.html - generate them from .raw.html instead

### ISSUE THREAD

**Issue by david-a-wheeler** [metamath/set.mm#691]
I propose that we delete mmcomplex.html and mmnatded.html, and instead generate them from their .raw.html files instead (mmcomplex.raw.html and mmnatded.raw.html).

You can regenerate the "old HTML" format this way:

scripts/regen-from-raw

And you can regenerate the "new HTML" (ALTHTML) formats this way:
scripts/regen-from-raw "/ALTHTML"

Currently that script generates .demo.html files; just delete ".demo" to generate the real things.

The ALTHTML versions are a *big* improvement over our current files when viewing in Unicode (the default).  mmcomplex.html, in particular, has a much prettier display.

There was discussion about this earlier in https://github.com/metamath/set.mm/pull/685 :

>>    Excellent. I intend in an upcoming commit to delete mmcomplex.html, and create a short script for generating selected HTML files from .raw.html. Obviously you will have to change the generation process to use them. It produces an immediate upgrade in the Unicode display, which becomes significantly prettier to read.

> Don't delete mmcomplex.html yet. One issue is where we generate it. If it is generated by the build script, then even though errors will get logged I don't look at the log very often. I just do an occasional sanity check now and then because 'verify markup' will have caught essentially all errors before the build is run. So if the build generates things that may have errors not previously checked for, they may get overlooked for a period of time.
> So it might be better to generate it at the Travis level so they would be caught immediately. What do you think?

I agree, but that has since been fixed.  The Travis build now checks the .raw.html files.

> It also might be wise to use ~ label tags for theorem references in mm*.raw.html files, because there have been cases where the set.mm label was changed but some of the mm*.html files weren't updated (this could even be the case right now). But running 'markup' without '/symbols_only' can be a nuisance due to literal '[' that frequently occurs in normal text. We could escape them, but people editing .raw.html will probably forget to do that. I don't think literal '~' occurs very often. So I'm considering adding '/labels_and_symbols_only' (abbreviated with /l of course) that would ignore bib refs. '/labels_and_symbols_only' would also suppress the colored number after the label, which is distracting clutter in normal prose text.

I think that's a good long-term plan, but we don't need to wait for that step.  Let's start the switchover with just symbols, and we can change the labels later.  Switching to generated symbols is a significant improvement in the display.  Switching labels has advantages, but it's already easy in HTML to create a hyperlink, so the benefits aren't as big a deal.

**Comment by david-a-wheeler** [comment]
@nmegill - this is really a question for you.  Deleting files is trivial, the question is, are you willing to change the website build process to generate these HTML files?

You'd simply need to run this for /HTML:

~~~~
scripts/regen-from-raw
~~~~

And this for the Unicode /ALTHTML:

~~~~
scripts/regen-from-raw "/ALTHTML"
~~~~

Then we can edit the .raw.html files and the script as needed.

**Comment by nmegill** [comment]
I could do that.   But I thought you were going to generate them with Travis so that we can detect errors more efficiently.

**Comment by david-a-wheeler** [comment]
The Travis build already detects errors in the .raw.html files.  Currently we throw the generated files away.

We can generate the .html files inside Travis, but the rest of the HTML files used on metamath.org aren't generated that way.  You can either regenerate *or* get them from Travis.  Either way, though, you'll have to tweak the way the metamath.org site builds its results to *use* those results.

Do you want those HTML files to be generated as part of Travis?

**Comment by david-a-wheeler** [comment]
I'm closing this issue, since it's done.

The tweaks to make Travis work again, now that the markup options have changed, are in this separate pull request:

https://github.com/metamath/set.mm/pull/695

**Comment by nmegill** [comment]
> The Travis build already detects errors in the .raw.html files. Currently we throw the generated files away.
> 
> We can generate the .html files inside Travis, but the rest of the HTML files used on metamath.org aren't generated that way. You can either regenerate _or_ get them from Travis. Either way, though, you'll have to tweak the way the metamath.org site builds its results to _use_ those results.
> 
> Do you want those HTML files to be generated as part of Travis?

@david-a-wheeler No, you can throw them away.  I have modified the build script to always generate them from .raw.html (will be testing on us2 tonight).
