### ISSUE TITLE
Use ~ labels in .raw.html files

### ISSUE THREAD

**Issue by david-a-wheeler** [metamath/set.mm#698]
I have focused on making .raw.html files use \` ... \` so that the symbols look much better and so that the files are easier to edit.

Now that we *have* .raw.html files, we can modify them to use ~ labels instead of direct HTML hrefs.  That will make it easy for us to check that the references actually exist, *and* we can easily insert hover text so that you can hover over a label and see its summary.

**Comment by david-a-wheeler** [comment]
BTW: once this is done, we could then discuss if we want to rename some of the numbered axioms.  "ax-6" doesn't really hint at what it is, and the axioms aren't presented in that order in mmset.raw.html.  The risk of renaming is that we miss some link... but more will be caught if we use tools to catch problems.  A rename is *not* required as a follow-on to this task, but I mention it as something that would become easier.

**Comment by nmegill** [comment]
> BTW: once this is done, we could then discuss if we want to rename some of the numbered axioms. "ax-6" doesn't really hint at what it is, and the axioms aren't presented in that order in mmset.raw.html. The risk of renaming is that we miss some link... but more will be caught if we use tools to catch problems. A rename is _not_ required as a follow-on to this task, but I mention it as something that would become easier.

I made a renaming proposal in 2017:
https://groups.google.com/d/msg/metamath/G1xyJb6RjfI/JSNXPIkVAwAJ
I still agree with it.

Norm

**Comment by benjub** [comment]
@david-a-wheeler : it looks like this issue can be closed (since #703 is closed as well) ?
