### ISSUE TITLE
Does weak linearity hold for the ordinals in iset.mm?

### ISSUE THREAD

**Issue by jkingdon** [metamath/set.mm#738]
That is, can we prove `Ord A -> _E Or A` in iset.mm? (note of course that `Or` in iset.mm means weak linearity which is not, in the absence of excluded middle, equivalent to trichotomy). This would be roughly analogous to http://us2.metamath.org/mpeuni/dford5reg.html in set.mm.

I looked for an answer in the HoTT book, and as far as I noticed they only discuss weak linearity in the context of the reals.

**Comment by digama0** [comment]
No, I think my counterexample ordinal `X = { x e. 1o | ph }` from https://github.com/metamath/set.mm/issues/629#issuecomment-436954329 answers this. Weak linearity of ordinals means that `A e. B -> ( A e. C \/ C e. B )`. Take `A = X`, `B = suc X`, and `C = 1o`. Then we either have `X e. 1o` which implies `-. ph`, or `1o e. suc X`, meaning either `1o e. X` (which is false) or `1o = X` which implies `ph`.

**Comment by jkingdon** [comment]
I will consider this question answered by the above proof which is formalized in #741 .
