### ISSUE TITLE
add tfr1 (part of the transfinite recursion theorem) to iset.mm

### ISSUE THREAD

**Issue by jkingdon** [metamath/set.mm#751]
Many of the sources I consulted (Mendelson, set.mm, https://proofwiki.org/wiki/Transfinite_Recursion/Theorem_1#Domain_of_.7F.27.22.60UNIQ-MathJax-52-QINU.60.22.27.7F_is_.7F.27.22.60UNIQ-MathJax-53-QINU.60.22.27.7F ) prove tfr1 the same way (via http://us2.metamath.org/mpeuni/ordeleqon.html ), which is unintuitionizable as far as I can tell.

Here is a sketch of a proof of tfr1 and I'm looking for (1) is this on the right track? Is there a reason it won't work? Is my difficulty making some of the ideas precise related to fuzzy thinking or mistakes? and (2) can I have some tips about how to formalize it? I seem to get stuck somewhere in the general vicinity of going from the induction hypothesis to coming up with acceptable functions for the elements of the ordinal, and then gluing those functions together (along with the extra ordered pair for the ordinal itself, constructed from the acceptable functions for all its elements). I'm having trouble even putting ideas like "gluing together functions" into symbols.

We will be proving tfrlem14 (the proof of tfr1 from that is as in set.mm). It will suffice to show `( z e. dom recs ( F ) <-> z e. On )`. The forward direction is trivial from `tfrlem8` which iset.mm already has. The reverse direction we prove by transfinite induction (`tfis2` specifically). Since all the elements of `z` have acceptable functions (by the induction hypothesis), and those functions agree on their common domains (by `tfrlem5` which iset.mm already has), we can form a new function which agrees with those functions everywhere except `z` itself, and the value at `z` can be constructed by taking the union of the acceptable functions for its elements and evaluating `F` there. By transfinite induction, there is an acceptable function whose domain contains `z` and therefore `z e. dom recs ( F )`.

**Comment by jkingdon** [comment]
Crosilla (Stanford Encyclopedia of Philosophy) cites https://web.archive.org/web/20130619020751/https://www.mittag-leffler.se/preprints/files/IML-0001-40.pdf section 4.2 (theorem 3.7 is a form of recursion over natural numbers rather than ordinals but is also possibly relevant).

**Comment by jkingdon** [comment]
@digama0 Any reactions?

**Comment by digama0** [comment]
Looks good to me. My gut reaction is this is provable and you've got the right idea. Is there a place you are stuck?

**Comment by jkingdon** [comment]
Let me try to explain where I am stuck as best I can.

I'm trying to prove

```
qed:d1,d2:tfis2         |- (  x e. On
                      -> E. f
                            (  f Fn x
                            /\ A. y
                               e. x
                                  ( f ` y ) = ( F ` ( f |` y ) ) ) )
```

which will follow by transfinite induction (tfis2) from:

```
!d2::              |- (  x e. On
                      -> (  A. z
                            e. x
                               E. f
                                  (  f Fn z
                                  /\ A. y
                                     e. z
                                        ( f ` y ) = ( F ` ( f |` y ) ) )
                         -> E. f
                               (  f Fn x
                               /\ A. y
                                  e. x
                                     ( f ` y ) = ( F ` ( f |` y ) ) ) ) )
```

where the antecedent represents an appropriate function for every element
of `x` and the consequent represents the appropriate function which you
get when you glue them together. Maybe I'm just unimaginative or haven't
spent enough time playing around with things which might help, but I'm
not even really sure where to look in terms of how to define the
result of the gluing.

**Comment by digama0** [comment]
I think this should do it:

```
f := U. { f | E. z e. x E. g ( g Fn z /\ g acceptable /\
   f = ( g u. { <. z , ( F ` g ) >. } ) }
```

Each of the member functions `f` is an acceptable function on `suc z` extending `g` by one element. Since each element of the union is an acceptable function, the union is also a function, and its domain is x because if `z e. x` then there is some acceptable function with domain z (by the tfis assumption) and this one point extension will contain `z` in its domain.

**Comment by jkingdon** [comment]
Ah, good, that's putting into symbols what was sort of fuzzily sloshing around in my brain. It may take me some time to turn that into a proof but this seems like a concrete direction to head in.

**Comment by jkingdon** [comment]
Hmm, I haven't even gotten the first part of that ("Each of the member functions `f` is an acceptable function"). I started with the hypothesis of tfrlem*:

```
h1::tfrlemi1.1     |-   A
                      = { f
                        | E. x
                          e. On
                             (  f Fn x
                             /\ A. y
                                e. x
                                   ( f ` y ) = ( F ` ( f |` y ) ) ) }
```

and then I figured I would need to prove:

```
490a900::    |- (  (  (  x e. On
                            /\ A. z
                               e. x
                                  E. f
                                     (  f Fn z
                                     /\ A. y
                                        e. z
                                           ( f ` y ) = ( F ` ( f |` y ) ) ) )
                         /\ E. z
                            e. x
                               E. g
                                  (  g Fn z
                                  /\ g e. A
                                  /\   h
                                     = (  g
                                       u. { <. z , ( F ` g ) >. } ) ) )
                      -> h e. A )
```

which is going to require ``( F ` g ) e. _V`` to prove that `h` is a function (via funsng and funun) and also to prove that its domain is `suc z` (via dmun and dmsnopg). How can I show that?

**Comment by digama0** [comment]
You need to know it's in the domain of F. We don't have any assumptions about F so that's not provable, so you should add an assumption that F is defined on all ordinals and then you should be able to prove it. You could also prove something tighter in the case where the domain of F is some other thing, in which case the induction stops at the edge of F's definition, but that's probably not as interesting.

**Comment by jkingdon** [comment]
So a new hypothesis of `|- ( Fun F /\ A. x e. On E. f ( f Fn x /\ f e. dom F ) )` (since the argument to `F` isn't an ordinal itself but all the previous values, if I correctly understand `df-recs` that is)?

**Comment by digama0** [comment]
I think the exists needs to be a forall; that is, F is defined on every function with ordinal domain. You don't know in advance where it will be evaluated.

**Comment by jkingdon** [comment]
Sounds right about forall. I now have a proof of `h e. A` at https://github.com/jkingdon/set.mm/tree/iset-tfr1 . Next step is to go back to the "Since each element of the union is an acceptable function, the union is also a function, and its domain is x because if z e. x then there is some acceptable function with domain z (by the tfis assumption) and this one point extension will contain z in its domain." part of the proof.

**Comment by jkingdon** [comment]
Since it has been two months, I'll post a status report. I don't think I am stuck, in fact I'm probably through the worst of it, but if anyone sees any obstacles I don't see, or ways to make it easier, please speak up.

My work to date can be found at https://github.com/jkingdon/set.mm/tree/iset-tfr1 . Most of it leads up to `tfrlemi1` which is:

```
    $d x y z u v w f g h i j F $.  $d z u v w g h i j f A $.
    tfrlemi1.1 $e |- A = { f | E. x e. On ( f Fn x /\
                A. y e. x ( f ` y ) = ( F ` ( f |` y ) ) ) } $.
    tfrlemi1.2 $e |- ( Fun F /\ A. x e. On A. f ( f Fn x -> f e. dom F ) ) $.
    tfrlemi1 $p |- ( x e. On -> E. f ( f Fn x /\
        A. y e. x ( f ` y ) = ( F ` ( f |` y ) )
        ) ) $=
```

The next step from here is presumably `tfrlemi14` (which is the same as `tfrlem14` from set.mm with the additional hypothesis that the recursion rule is defined on all ordinals):

```
    tfrlemi14 $p |- dom recs ( F ) = On $=
```

As I said earlier in this ticket, the `x e. dom recs ( F ) -> x e. On` direction of that follows from `tfrlem8`. To prove the `x e. On -> x e. dom recs ( F )` direction, we need to show `E. g e. A x e. dom g` or in other words we need an acceptable function which contains ` x ` in its domain. Given `E. f ( f Fn x /\ A. y e. x ( f ` y ) = ( F ` ( f |` y ) ) )` from `tfrlemi1`, we will set `g = ( f u. <. x , ( F ` f ) >. )` . We'll then show that ` g e. A ` by ` tfrlemisucacc ` , that ` ( F ` f ) ` exists by the hypothesis that the recursion rule is defined on all ordinals, and that will give us `E. g e. A x e. dom g` which transforms via `dmuni` and `eluni` into ` x e. dom U. A ` which is what we need for `tfrlemi14`.

From there we should be able to prove analogues to `tfr1`, `tfr2`, and `tfr3` much as in set.mm (with the additional hypothesis that the recursion rule is defined on all ordinals).

**Comment by jkingdon** [comment]
This is done, now that #838 has been merged.

Many thanks to @digama0 ; yet another case in which my work in iset.mm would not have been possible without him.
