### ISSUE TITLE
New section "Matrices and determinants"

### ISSUE THREAD

**Issue by avekens** [metamath/set.mm#769]
This is a follow-up issue of #85 : Now Cramer's Rule is proven, and a lot of definitions and theorems about matrices, vectors and determinants are available in the Mathboxes of Stefan and me, the next step would be to move this material into the main part of set.mm. As I already suggested in #85, I propose to create a new section 10.13 titled "Matrices and determinants" (it must be located at least after 10.11, because the definition of ZRHom is required). The following subsections (from SO's Mathbox) should be moved into this new section:
19.17.43 Direct sum of left modules cdsmm 28017
1917.44 Free modules cfrlm 28032
19.17.54 Words in monoids and ordered group sum issubmd 28203
19.17.55 Transpositions in the symmetric group cpmtr 28204
19.17.56 The sign of a permutation cpsgn 28234
19.17.57 The matrix algebra cmmul 28259
19.17.58 The determinant cmdat 28303
19.17.59 The matrix adjugate/adjunct cmadu 28470
19.17.60 The inverse matrix invrvald 28484

Additionally, the following subsections from my Mathbox can be added:
19.23.7.8  Multiplication of a matrix with a "column vector"   mamuvec 29764
19.23.7.10  Replacement functions for a square matrix   cmarrep 29805
19.23.7.12  Cramer's rule   mamudm 29870

If there are no objections, I can start working on that.

**Comment by nmegill** [comment]
It sounds like a good plan to me. - Norm

**Comment by david-a-wheeler** [comment]
I'd love to see it!  Matrices are important for lots of fields, including Machine Learning (a current hot topic).

**Comment by savask** [comment]
As a similar idea to consider, maybe one could create a new part (i.e. PART 11 BASIC LINEAR ALGEBRA) and put matrices/determinants in there? Matrices hardly qualify to be in the algebraic structures section, also the topic is pretty vast by itself.

Also, may I suggest moving axillary topics to respective sections, say, words in monoids are probably better in 10.1 (Monoids), transpositions and sign function can be put in 10.2 (Groups), free modules can go to 10.6 (Left modules).

There might be some dependency considerations I'm not aware of, but in my opinion this can help keep set.mm a bit more structured.

**Comment by avekens** [comment]
Yes, it is a good idea to create a new part (I didn't dare to suggest this). Also moving some of the topics to another, better fitting place should be considered. However, I will move the stuff step by step, because it is a tedious work to extract the definitions/theorems from 2 Mathboxes, identifying and resolving the dependencies to other theorems of these mathboxes, and to place the auxiliary theorems at the right place etc.

So I propose the following structure (for the beginning):

PART 11 BASIC LINEAR ALGEBRA
11.1  Miscellaneous
This section contains definitions and theorems which may be moved to other
parts/sections in the future.
11.1.1 Extensions beyond function theory
11.1.2 Addenda for structure powers
11.1.3 Direct sum of left modules
11.1.4 Words in monoids and ordered group sum
11.1.5 Transpositions in the symmetric group
11.1.6 The sign of a permutation
11.2  Vectors and free modules
11.2.1 Free modules
11.2.2 Unit vectors
11.3 Matrices and determinants
11.3.1 The matrix algebra
11.3.2 The determinant
11.3.3 The matrix adjugate/adjunct
11.3.4 The inverse matrix
11.3.5 Multiplication of a matrix with a "column vector"
11.3.6 Replacement functions for a square matrix
11.3.7 Cramer's rule

I will post a first pull request with an initial step shortly

**Comment by avekens** [comment]
So now the first step for restructuring/rearraning the definitions and theorems for "Basic linear Algebra" is done, we have the following structrure of the new Part 11:

PART 11  BASIC LINEAR ALGEBRA
      11.1  Miscellaneous
            11.1.1  Direct sum of left modules   cdsmm 17583
            11.1.2  Transpositions in the symmetric group   cpmtr 17598
            11.1.3  The sign of a permutation   cpsgn 17642
      11.2  Vectors and free modules
            11.2.1  Free modules   cfrlm 17702
            11.2.2  Unit vectors   cuvc 17728
      11.3  Matrices and determinants
            11.3.1  The matrix algebra   cmmul 17750
            *11.3.2  Multiplication of a matrix with a "column vector"   cmvmul 17821
            11.3.3  Replacement functions for a square matrix   cmarrep 17835
            11.3.4  Submatrices   csubma 17855
            11.3.5  The determinant   cmdatold 17863
            11.3.6  The determinant of 2 x 2 -matrices   m2detleiblem1 17902
            11.3.7  The matrix adjugate/adjunct   cmaduold 17910
            11.3.8  The Laplace expansion of determinants (special case)   symgmatr01lem 17933
            11.3.9  The inverse matrix   invrvald 17956
            11.3.10  Cramer's rule   slesolvec 17959

As Mario suggested, some of these sections (especially 11.1) should be moved to Part 10 BASIC ALGEBRAIC STRUCTURES. 

Regarding 11.1, I proprose to create a new section 10.3 after "Groups" (or alternatively 10.4 after "Abelian groups") named "Symmetric groups" with the following subsections:

10.4 Symmetric groups
10.4.1 Definition and basic properties
10.4.2 Cayley's theorem
10.4.3 Permutations fixing one element
10.4.4  Transpositions in the symmetric group   
10.4.5  The sign of a permutation   

Subsections 10.4.1-3 are comming from subsection 10.2.6  "Symmetric groups and Cayley's Theorem" of section 10.2 "Groups". Moving these subsections backwards is possible without breaking any dependencies (I checked this).

Subsection 11.1.1 "Direct sum of left modules"  can become subsection 10.6.5 of section 10.6. "Left modules". 

I'm not sure if it is a good idea to move section 11.2 "Vectors and free modules" also into part 10. Free modules are used to represent "column vectors" which are essential for linear algebra, so I think this section could remai  in Part 11. Furthermore, we would have only a single section "Matrices and determinants" left in Part 11 BASIC LINEAR ALGEBRA if we moved this section. However, we could split it into two sections "Matrices" and "Determinants" as follows:

      11.1  Matrices
            11.1.1  The matrix algebra   cmmul 17750
            11.1.2  Multiplication of a matrix with a "column vector"   cmvmul 17821
            11.1.3  Replacement functions for a square matrix   cmarrep 17835
            11.1.4  Submatrices   csubma 17855
      11.2  Determinants
            11.2.1  Definition and basic properties  cmdatold 17863
            11.2.2 The determinant of 2 x 2 -matrices   m2detleiblem1 17902
            11.2.3  The matrix adjugate/adjunct   cmaduold 17910
            11.2.4  The Laplace expansion of determinants (special case)   symgmatr01lem 17933
            11.2.5  The inverse matrix   invrvald 17956
            11.2.6 Cramer's rule   slesolvec 17959

Before I start step 2 for restructuring/rearraning, I want to ask for your opinion about my proposals and the alternatives:

1. Is it OK to create a new section "Symmetric groups" and to move subsection 10.2.6  "Symmetric groups and Cayley's Theorem" of section 10.2 "Groups" into it?
2. Should the new section "Symmetric groups" be placed before or after section "Abelian groups"?
3. Should section 11.2 "Vectors and free modules" be moved into Part 10 BASIC ALGEBRAIC STRUCTURES? Or should it remain in Part 11 BASIC LINEAR ALGEBRA?
4. Is it OK to split section "Matrices and determinants" into two sections "Matrices" and "Determinants"?

**Comment by savask** [comment]
In my opinion, part "basic algebraic structures" is roughly what one learns in a abstract algebra course, so basically prerequisites for other areas. With that philosophy in mind, having a separate section for symmetric groups is a bit too much, since it contains "basic" theorems of group theory (to be honest, I would even merge the "abelian groups" section into "groups").

I really like the idea of splitting the linear algebra section into "matrices" and "determinants" and of moving Stefan's theorems into the main part. May I bring up the question of terminology: right now set.mm uses a term "unit vector" to mean a vector from the standard basis. I've never seen that term used this way (for me a unit vector is a vector of length 1), so maybe it makes sense to change the phrasing?

Also, perhaps a bit unrelated, shouldn't #85 be closed now?

**Comment by avekens** [comment]
By pull request #808 , this issue is done! I will continue working on linear algebra in my Mathbox. Maybe some of these results could be moved to the main part of set.mm later.
