### ISSUE TITLE
Quotient lifting pattern

### ISSUE THREAD

**Issue by digama0** [metamath/set.mm#79]
Currently, there are several places where maps from a quotient are used, e.g. [frgpupval](http://us.metamath.org/mpegif/frgpupval.html), [orbstaval](http://us.metamath.org/mpegif/orbstaval.html), [pi1coval](http://us.metamath.org/mpegif/pi1coval.html), and others where the quotient is implicit with a function e.g. [cygznlem2](http://us.metamath.org/mpegif/cygznlem2.html). Currently, the well-definedness condition is being rederived in each case, but they have a common structure that can be extracted.

These can be replaced by the pattern

```
|- F = ran ( x e. X |-> <. A , B >. )
```

which is the function such that ``( F ` A(x) ) = B(x)``, provided that the well-definedness condition `A(x) = A(y) -> B(x) = B(y)` is satisfied. In the special case where the function is being defined over an equivalence relation, this can be replaced with

```
|- F = ran ( x e. X |-> <. [ x ] R , B >. )
```

where now the well-definedness condition is `x R y -> B(x) = B(y)`, and it satisfies ``( F ` [ x ] R ) = B(x)`` in this case.

This idiom has the advantage that it requires no dummy variables other than the essential ones, and does not need an `iota` construction.

**Comment by david-a-wheeler** [comment]
On October 9, 2016 9:03:35 PM EDT, Mario Carneiro <notifications@github.com> wrote:
>Currently, there are several places where maps from a quotient...
>This idiom has the advantage that it requires no dummy variables other
>than the essential ones, and does not need an `iota` construction...


That makes sense. However, I'm concerned that these kind of conventions are either undocumented or can be found only if you read the raw text in set.mm.  Is there a way we can make these conventions more visible to those who only read the HTML?


--- David A.Wheeler

**Comment by digama0** [comment]
"Adaptive idioms" of this type occur in a variety of contexts, because they often are an alternative to making new definitions for patterns that are used a few times but not enough to be their own definition. They are typically accompanied by a collection of theorems that use the idiom in its general form; this is what gives it the definite idiomatic shape in the first place. It is in these theorems that the idiom is explained or identified. In this case, there would be at least four or five general theorems in use: The function `F` is a function on the quotient set, and it takes the given value on the assumption that it satisfies the well-definedness condition. Every application of the idiom will invariably want to refer to these theorems, and this is how a web reader could find the meaning of the expression.

**Comment by digama0** [comment]
Done in 058ccf3.
