### ISSUE TITLE
Script min.cmd

### ISSUE THREAD

**Issue by benjub** [metamath/set.mm#803]
If, for instance, labelA uses both labelB and labelC, then the command
MM>show usage labelB,labelC
will mention labelA twice.
Therefore, I think that min.cmd could have a line "unduplicate 1.tmp" just after the line "break 1.tmp...".  This would avoid doing the same minimization several times; as a drawback, the lines would then be sorted alphabetically.

Also, the script min.cmd is present twice: in the root directory and in /scripts , almost identical.  I think this could be a source of confusion.

**Comment by nmegill** [comment]
Alphabetical labels shouldn't be a problem, and it also should make it easier to monitor progress with tail -f on the log file.  Go ahead and add 'unduplicate'.  I didn't put it in originally out of laziness.

There should only be one copy in the scripts directory.  You can delete the one you don't use, and move the other to the scripts directory if it isn't there already.

**Comment by benjub** [comment]
This is now Pull request #805 .
