### ISSUE TITLE
Use iota consistently

### ISSUE THREAD

**Issue by digama0** [metamath/set.mm#81]
Currently, there are five variants on "the unique element such that `ph`" in use, namely (1) `U. { x | ph }`, (2) `U. { x e. A | ph }`, (3) `( iota x ph )`, (4) `( iota x ( x e. A /\ ph ) )`, (5) `( iota_ x e. A ph )`. We should adjust the library to encourage the forms (3) and (5) and eschew the others. ((1) and (3) are the same, as are (2) and (4); (5) is almost the same as (2),(4) except in the handling of non-unique properties. Personally I would prefer to define (5) to equal (4), but this is a separate issue. While this definitional difference exists, (4) can be used when the difference is important.)

**Comment by david-a-wheeler** [comment]
I agree. Consistency is good, and the recommended forms seem clear to me.

**Comment by digama0** [comment]
Done in a4a4ae3.
