### ISSUE TITLE
Relabeling

### ISSUE THREAD

**Issue by benjub** [metamath/set.mm#810]
I added a few days ago a utility theorem, sylbib, which is used in around 27 theorems.  I'm afraid I mislabeled it and it should be "sylbb" instead (in view of the two theorems immediately before, sylbi and sylib).  Can I simply change "sylbib" to "sylbb" globally in set.mm, or do I have to add a special line at the beginning, in the section "recent label changes" ? (Note that the theorem is only a few days old, if this changes anything).

**Comment by nmegill** [comment]
Because you added it very recently, it is unlikely that any new theorems added since then will depend on it (27/30K or 0.1%).  I think you should go ahead and make a global name change.

**Comment by benjub** [comment]
Thanks. Done in #811
