### ISSUE TITLE
dvelimALT

### ISSUE THREAD

**Issue by benjub** [metamath/set.mm#819]
The comment of dvelimALT says "see dvelimh for a version that doesn't use ax-12".  However, dvelimh does use ax-12...

Also, the comment of dvelimALT says "that doesn't use ax-c11n", which is not very clear, since dependency is hard to trace back (this is repeated in the comment of dvelim, which says that dvelimALT avoids ax-c11n).

Not sure how to fix these.

**Comment by nmegill** [comment]
dvelimALT is obsolete, having served its purpose a long time ago when working on the axiomatization.  The referenced ax-c11n is obsolete, and currently dvelim and dvelimALT use exactly the same axioms.  You can go ahead and delete dvelimALT in your next pull request, and remove references to it in other comments.
