### ISSUE TITLE
Find/replace description errors

### ISSUE THREAD

**Issue by EdwardMcCants** [metamath/set.mm#829]
The following four theorems have what seems to be a find/replace error in the descriptions:

- syl5eqel
- syl5eqelr
- syl5eleq
- syl5eleqr

I'm assuming that the description was intended to be "A membership and equality inference." instead of "B membership and equality inference.", but the word 'A' in the description became swept up as the variables A, B, and C in the hypotheses/theorems were switched around.

**Comment by nmegill** [comment]
Fixed in develop commit d2ff707.   Thanks for reporting.

**Comment by EdwardMcCants** [comment]
Shouldn't this issue have closed?
