### ISSUE TITLE
Prove Taylor's Theorem (metamath 100 #35)

### ISSUE THREAD

**Issue by david-a-wheeler** [metamath/set.mm#83]
[Taylor's theorem](https://en.wikipedia.org/wiki/Taylor's_theorem) has a few possible statements. One form states that if f : R -> R is a function k-times differentiable at a e. R, then there exists a function h : R -> R such that h(a)=0 and h is continuous at 0, and f(x) = (sum_ n e. (0...k) f^(n)(a) (x-a)^n / n!) + h(x) (x-a)^k . (This is called the Peano form of the remainder.)

This is Metamath 100 theorem # 35.   This is one of the most commonly-proved theorems by formalization tools (7 others), but not by Metamath.

This only needs calculus and power series work, mostly all there.

**Comment by digama0** [comment]
Done in 522d750, theorem `taylth`.
