### ISSUE TITLE
More copy/paste errors

### ISSUE THREAD

**Issue by EdwardMcCants** [metamath/set.mm#837]
This time I'm searching to find all descriptions that start with the word B (assumed to be a copy/paste error changing the variable A to B).

* syl5eqner
* syl5eqss
* syl5eqssr
* syl5eqbr
* syl5eqbrr
* syl5breq
* syl5breqr

**Comment by nmegill** [comment]
Fixed in develop commit 84b6321.  Thanks for reporting it.
