### ISSUE TITLE
L'Hôpital's Rule (metamath 100 #64)

### ISSUE THREAD

**Issue by david-a-wheeler** [metamath/set.mm#84]
Prove L'Hôpital's Rule (metamath 100 #64).  5 other formalization systems have proven it.

This one is mostly annoying for its various special cases involving
different kinds of limits. Otherwise, it's probably simpler than Taylor's theorem.

**Comment by digama0** [comment]
Done in e765c84.

**Comment by david-a-wheeler** [comment]
Very awesome. Thanks and congrats!
