### ISSUE TITLE
The Ballot Problem (metamath 100 #30)

### ISSUE THREAD

**Issue by david-a-wheeler** [metamath/set.mm#88]
Prove The Ballot Problem (metamath 100 #30).  4 other formalization tools have done so.

Mario: This is an elementary combinatorics problem in the same vein as the birthday problem. We probably have the tools for this one now if you use binomial coefficients, but if you use Catalan numbers they will need to be defined first.

**Comment by david-a-wheeler** [comment]
On Mon, 5 Dec 2016 21:09:22 +0800, Thierry Arnoux reported "I've been working on a proof for 30. The Ballot Problem recently. The inductive proof would have been the easiest way, but I'm
trying myself at the more elegant reflection method..."

**Comment by tirix** [comment]
Created Pull Request #112

**Comment by david-a-wheeler** [comment]
Congrats!
