### ISSUE TITLE
fovv and fornex

### ISSUE THREAD

**Issue by benjub** [metamath/set.mm#918]
@nmegill and @avekens If I'm not mistaken, fovv and fornex are the same theorem up to commutation of antecedents. I think either one should be deleted or its proof should be minimized with the other's.

**Comment by avekens** [comment]
@benjub you are right: they are the same! Since fornex is much older and more often used (fovv is only used once), I'll delete fvv and replace it by fornex in the one proof.

The same holds for f1dmex and f1vv...

**Comment by avekens** [comment]
Done with PR #920.
