### ISSUE TITLE
Field of real numbers

### ISSUE THREAD

**Issue by avekens** [metamath/set.mm#943]
As Benoît proposed in PR #937, there should be a definition 
`  df-refld $a |- RRfld = ( CCfld |``s RR ) $. `
for the (ordered) field of real numbers (like df-zring for the ring of integers, see #866), and all/most occurrences of ` ( CCfld |``s RR ) ` (currently about 25) should be replaced by RRfld.

Consider the convention (see ~ conventions ) to use "re" as abbreviation for real numbers in labels (and not "rr" or "rn").

PS: There is already such a definition in Benoît's mathbox (~ df-bj-rrfld )! This should be moved to the main part, top of (new) section "The ordered field of real numbers"

**Comment by benjub** [comment]
Of course, I second that !  The definition df-rrfld (or df-refld if you insist) should be credited to @tirix I think.  The reason for introducing it is of course the importance of the field of real numbers in mathematics, and if more practical arguments are needed:
* I plan to introduce real vector spaces to develop the foundations of convexity, which is a specifically real phenomenon;
* the important work done by @avekens on ZZring shows that it's easier to do this earlier rather than later.

**Comment by benjub** [comment]
Based on the above arguments and the growing section by @tirix on Euclidean spaces which keeps adding uses of ( CCfld |``s RR ), do you (@avekens, @tirix, @nmgeill, @digama0) agree to add RRfld to set.mm, before it takes too much work to replace all the occurrences of ( CCfld |``s RR )?
The syntax and definition are the obvious ones, but just to make it clear: ~crrfld and ~df-bj-rrfld. These could be added just before ~rebase.

**Comment by tirix** [comment]
I would be fine with introducing that definition.

If the amount of work is too big for you, there might be ways to split it among us.

**Comment by nmegill** [comment]
Adding this is fine with me.

**Comment by avekens** [comment]
I strongly recomment to add RRfld to (the main part of) set.mm, the sooner the better ;-).

**Comment by benjub** [comment]
@tirix, will you have time to add this definition at the beginning of the section "10.11.6  The ordered field of real numbers" ?  So far, there seems to be only 25 occurrences of ( CCfld |`s RR ) in set.mm.

**Comment by tirix** [comment]
Ok, I'll try.

**Comment by tirix** [comment]
Ok, this is part of #970. I ended up changing ~ 50 theorems.

**Comment by benjub** [comment]
Thanks @tirix !

**Comment by avekens** [comment]
Great, also many thanks to @tirix . Replacing definitions is really cumbersome, much more work than expected at the beginning. I am still working on the replacements for the support of functions, there are (maybe much) more than 100 theorems to be touched...

There are two minor open points which should be solved before this issue is closed:

- theorem ~ tgioo3 still uses ( CCfld |\`s RR ) instead of RRfld - this should be replaced (there are more theorems using ( CCfld |\` s RR ) - but they are in mathboxes, so their owners should care for it). Because ~ tgioo3 is located before the definition of RRfld, it must also be moved (which is possible because ~ tgioo3 is not used in any proof).
- the html/latex definition for RRfld is still in the region for BJ's mathbox - it should be moved in the region for the main part (after "ZMod"?).

**Comment by benjub** [comment]
I'm taking care of the second point in my pending PR.

**Comment by tirix** [comment]
I took care of the first point in #979.

**Comment by avekens** [comment]
Perfect - this issue can be closed now.
