### ISSUE TITLE
Replacing ` ? e. _V -> `

### ISSUE THREAD

**Issue by avekens** [metamath/set.mm#944]
As remarked by @nmegill in #937:

> [Instead of] using 'I e. _V' in the antecedent of [a theorem, we] generally prefer to use the more general 'I e. V' (or another variable if V is not available) to make it more general; that way we can often avoid needing extra elex and syl in case I is already a member of something. You may want to change that in a future PR.
> 
> Actually, looking thru set.mm with 'search * '|- ( ? e. _V -> ' it seems there are about 20 other theorems with this same issue. Someone may want to volunteer to clean these up.

@tirix  proposed to look for '|- ( ( ? e. _V -> '

PS: I only found 4 relevant occurrences of '( ? e. _V -> ' in the main part of set.mm - the others are in Mathboxes or OLD theorems. Looking for '/\ ? e. _V ) -> ' results in 20 hits (11 in main part).

**Comment by benjub** [comment]
Among them, I found @avekens's opabbrex which looks not very optimal.  It looks like using the theorem (which is certainly in set.mm) that a subclass of a set is a set, one can prove the closed form:

 |- ( ( ( x A y -> ph ) /\ { <. x , y >. | ph } e. V ) -> { <. x , y >. | ( x A y /\ ps ) } e. _V )

**Comment by avekens** [comment]
@benjub  good idea, I changed the theorem (and also sprmpt2, renamed sprmpt2d, of the same kind) accordingly. I had, however, to add all quantifiers A. x A. y to your proposal:

opabbrex $p |- ( ( A. x A. y ( x R y -> ph ) /\ { <. x , y >. | ph } e. V ) -> { <. x , y >. | ( x R y /\ ps ) } e. _V ) $=

I just committed my changes with PR #950...

**Comment by jkingdon** [comment]
There are also be a few examples of ` ? e. _V ->` in iset.mm (from before when I was implementing the `? e. V` convention consistently), although I have converted many of them by now.

I came to agree with the `? e. V` convention when I saw how many times we have `A e. On` or `A e. om` or something of the sort, so the number of avoided `elex` is large.

**Comment by avekens** [comment]
With PR #2195, the relevant occurrences of '( ? e. _V -> ' in the main part of set.mm are cleaned up now.
Looking for '|- ( ( ? e. _V', I found the following theorems which should be revised, too:

* ~pwfseqlem2 
* ~preqr1g
* ~fopwdom 
* ~hsmexlem2 
* ~hashtpg 
* ~evlsval 
* ~evlsval2 
* ~mpfsubrg 
* (~ wlkres, ~2spot2iun2spont - will be removed in the near future anyway)

**Comment by avekens** [comment]
With PR #2200, this issue should be done. Maybe there are some further theorems to be revised, which do not match the discussed patterns. These should be revised as soon as they are detected. There are some theorems to be revised in Part 16 GRAPH THEORY, but these will be removed/replaced in the context of issue #1418 (Revision of graph theory).
Of course there are still some "violations" of the convention in the mathboxes. These should be revised by the mathbox owners, at least before such a theorem is moved to main set.mm. The corresponding convention is already documented in PART 17 (see PR #1609), so that there should be no discussion anymore.

**Comment by avekens** [comment]
Done, since PR #2200 is merged.
