### ISSUE TITLE
Eclipse plugin emetamath

### ISSUE THREAD

**Issue by avekens** [metamath/set.mm#966]
FYI, I’ve created a plugin for Eclipse, which basically provides all functions from MMJ2 (except for search utility, but with a few more too).
http://emetamath.tirix.org/
It relies on the Eclipse built-in editor, so it has e.g. “replace all” functions (including regexp), and allows to open different proofs in different windows, so it might be handy for this kind of things.

_Originally posted by @tirix in https://github.com/metamath/set.mm/issues/866#issuecomment-502005957_

**Comment by avekens** [comment]
@tirix I installed the plugin as described, but loading the current set.mm produces errors:
![grafik](https://user-images.githubusercontent.com/30026387/60347711-46aba200-99be-11e9-8eb1-9909d0e8adde.png)
It seems that the recent change of "set" to "setvar" (see #759) causes problems. Could you have a look at this, please?

By the way, mmj2 (as downloaded from the metamath website) does also not work properly. I had to download the script definitionCheck.js from https://github.com/digama0/mmj2/tree/develop to avoid a huge amount of logs during startup of mmj2. @digama0 will there be an "official" new version of mmj2 in the near future?

**Comment by tirix** [comment]
@avekens I'd propose to track this [directly in the Emetamath project](https://github.com/tirix/Emetamath/issues). 
Do you want to open the issue there?

**Comment by benjub** [comment]
@avekens Can this issue be closed, now that it is on the Emetamath project ?

**Comment by avekens** [comment]
OK, there was an open question about mmj2 itself, which I posted in the repository for mmj2: digama0/mmj2#15.

So this issue can be closed now.
