### ISSUE TITLE
df-sbc update

### ISSUE THREAD

**Issue by nmegill** [metamath/set.mm#97]
I am ready to do the df-sbc update.  This is a massive change involving about 900 label changes:  xxx to xxxSBC for uses of the old df-sbc and xxxNSB to xxx for uses of the new df-sbc.  All pull requests need to be closed out and any recent changes by Mario applied.  I'll wait to hear from Mario and David.

Norm

**Comment by digama0** [comment]
I've been keeping develop up to date with my work with daily pushes, so what you see is all I've got. You are free to go ahead as far as I am concerned.

**Comment by david-a-wheeler** [comment]
Sounds great. Please go ahead.
